/**
 * Design Knowledge & Recommendation Adapter — Team 23
 *
 * Contract types for the universal adapter between the Design Platform and
 * existing knowledge systems (template knowledge library, canonical normalizer,
 * client memory, AI capability matrix, plugin framework).
 *
 * Design invariants:
 *   - Recommendations are advisory-only until accepted through the canonical workflow.
 *   - No raw provider payloads or provider secrets may appear in results.
 *   - No factual claim without a source citation.
 *   - No automatic project mutations.
 *   - tenant/platform scope is explicit, never inferred from defaults.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Knowledge types
// ─────────────────────────────────────────────────────────────────────────────

export type KnowledgeType =
  | "principle"
  | "style"
  | "guideline"
  | "pattern"
  | "template"
  | "blueprint"
  | "material_recommendation"
  | "component_recommendation"
  | "compliance_rule"
  | "workflow_hint"
  | "anti_pattern";

export const KNOWLEDGE_TYPES: readonly KnowledgeType[] = [
  "principle",
  "style",
  "guideline",
  "pattern",
  "template",
  "blueprint",
  "material_recommendation",
  "component_recommendation",
  "compliance_rule",
  "workflow_hint",
  "anti_pattern",
] as const;

// ─────────────────────────────────────────────────────────────────────────────
// Scope
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Scope narrows the knowledge query to a specific tenant, platform, service
 * type, or design domain. All fields are optional — absent means platform-wide.
 *
 * Callers must never hard-code tenantId, platformId, or domain values; they
 * must be derived from the request context at runtime.
 */
export interface KnowledgeScope {
  /** Tenant the query is issued on behalf of. */
  tenantId?: string;
  /** Platform identifier for multi-platform deployments. */
  platformId?: string;
  /** Service type (e.g. "graphic_design", "interior_design"). */
  serviceType?: string;
  /** Design domain (e.g. "branding", "packaging", "fashion"). */
  domain?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Confidence
// ─────────────────────────────────────────────────────────────────────────────

export type RecommendationConfidence = "high" | "medium" | "low";

export const CONFIDENCE_ORDER: Record<RecommendationConfidence, number> = {
  high: 3,
  medium: 2,
  low: 1,
};

// ─────────────────────────────────────────────────────────────────────────────
// Source & citation
// ─────────────────────────────────────────────────────────────────────────────

export interface DesignKnowledgeSource {
  /** Stable provider identifier — never changes across versions. */
  providerId: string;
  providerName: string;
  version?: string;
  /** ISO-8601 timestamp when this result was fetched. */
  retrievedAt: string;
}

export interface DesignKnowledgeCitation {
  source: DesignKnowledgeSource;
  /** Identifier within the source (template id, style key, rule id, etc.). */
  referenceId: string;
  /** Human-readable label for the citation. */
  referenceLabel: string;
  /** Optional short excerpt justifying the recommendation. */
  excerpt?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Reason
// ─────────────────────────────────────────────────────────────────────────────

export interface RecommendationReason {
  /** One-sentence plain-language summary — required. */
  summary: string;
  /** Longer explanation — optional. */
  detail?: string;
  /** Zero or more citations backing this reason. */
  citations: DesignKnowledgeCitation[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Recommendation
// ─────────────────────────────────────────────────────────────────────────────

export interface DesignRecommendation {
  /** Stable dedup key: hash of type+title+body, generated by the registry. */
  id: string;
  type: KnowledgeType;
  title: string;
  body: string;
  confidence: RecommendationConfidence;
  reason: RecommendationReason;
  /** Conditions under which this recommendation applies. */
  applicability: string[];
  /** Known limitations or caveats. */
  limitations?: string[];
  /** Alternative recommendations if this one is not suitable. */
  alternatives?: string[];
  /**
   * Whether the recommendation is backed by a source citation.
   * If false the recommendation is advisory/heuristic only and must be
   * presented as such — no factual claims may be derived from it.
   */
  hasSource: boolean;
  scope: KnowledgeScope;
  /**
   * Always true — this recommendation is advisory only.
   * It MUST NOT automatically mutate a project. The user or agent must
   * explicitly accept it through the canonical workflow.
   */
  isAdvisory: true;
}

// ─────────────────────────────────────────────────────────────────────────────
// Query
// ─────────────────────────────────────────────────────────────────────────────

export interface KnowledgeFilter {
  /** Restrict to specific knowledge types. */
  types?: KnowledgeType[];
  /** Canonical industry key (normalised before use). */
  industry?: string;
  /** Canonical style key (normalised before use). */
  style?: string;
  /** Scope filter. */
  scope?: KnowledgeScope;
  /** Maximum recommendations to return. */
  limit?: number;
  /** Minimum acceptable confidence level. */
  minConfidence?: RecommendationConfidence;
}

export interface DesignKnowledgeQuery {
  /** Free-text query describing the design context or question. */
  query: string;
  filter?: KnowledgeFilter;
  /** Explicit scope override — if absent, derived from the request context. */
  scope?: KnowledgeScope;
  /** Client / customer identifier for memory personalisation. */
  clientId?: string;
  /** Project identifier for project-memory context. */
  projectId?: string;
  /** Specific knowledge types requested. */
  requestedTypes?: KnowledgeType[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Result
// ─────────────────────────────────────────────────────────────────────────────

export interface DesignKnowledgeResult {
  /** Unique identifier for this query execution. */
  queryId: string;
  query: DesignKnowledgeQuery;
  recommendations: DesignRecommendation[];
  /** Flat deduped citation list across all recommendations. */
  citations: DesignKnowledgeCitation[];
  totalProviders: number;
  /** IDs of providers that successfully returned results. */
  resolvedProviders: string[];
  /** IDs of providers that were unavailable or timed out. */
  unavailableProviders: string[];
  executionMs: number;
  // NOTE: No raw provider payloads, no secrets, no prompt fragments.
}

// ─────────────────────────────────────────────────────────────────────────────
// Capability
// ─────────────────────────────────────────────────────────────────────────────

export interface KnowledgeCapability {
  supportedTypes: KnowledgeType[];
  supportsIndustryFilter: boolean;
  supportsStyleFilter: boolean;
  supportsTenantScope: boolean;
  supportsPlatformScope: boolean;
  maxResultsPerQuery: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Adapter interface
// ─────────────────────────────────────────────────────────────────────────────

export interface KnowledgeAdapter {
  /** Stable, unique provider identifier. */
  readonly id: string;
  /** Human-readable name. */
  readonly name: string;
  readonly capability: KnowledgeCapability;
  /**
   * Execute a knowledge query and return recommendations.
   * Must NOT return raw provider payloads or secrets.
   */
  query(q: DesignKnowledgeQuery): Promise<DesignRecommendation[]>;
  /**
   * Returns true if this provider is ready to serve requests.
   * A provider that returns false is listed in unavailableProviders.
   */
  isAvailable(): Promise<boolean>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Registry interface
// ─────────────────────────────────────────────────────────────────────────────

export interface ProviderEntry {
  adapter: KnowledgeAdapter;
  /** Lower number = higher priority. Default 100. */
  priority: number;
}

export interface KnowledgeProviderRegistry {
  /**
   * Register a provider. Throws if a provider with the same id is already
   * registered — use unregister() first if intentional replacement.
   */
  register(adapter: KnowledgeAdapter, priority?: number): void;
  /** Remove a provider by id. No-op if not found. */
  unregister(id: string): void;
  listProviders(): Array<{ id: string; name: string; priority: number }>;
  /**
   * Fan out the query to all available providers in priority order,
   * deduplicate results, enforce timeout, and return a structured result.
   */
  query(q: DesignKnowledgeQuery): Promise<DesignKnowledgeResult>;
}
