/**
 * WP-04B — Rotation-Aware Collision Resolver
 *
 * Extends the constraint solver's no_collision handler with rotation-aware
 * collision detection and resolution using the WP-04A OBB/SAT adapter.
 *
 * Design rules:
 *   - Zero-rotation pairs delegate to the existing AABB resolveCollision (WP-03C compat path).
 *   - Rotated pairs use obbSatCollideElements (WP-04A) for detection and MTV for resolution.
 *   - Locked elements absorb no push; the other element absorbs the full MTV.
 *   - pairCap, translationCapPx, and deadlineAbsolute are hard resource guards.
 *   - Input elements are never mutated.
 *   - Deterministic: same inputs always produce the same outputs.
 *
 * MTV convention (owner decision, matches WP-04A):
 *   resolvedPositionA = { x: a.x + mtv.x, y: a.y + mtv.y }
 *
 * @module rotationAwareResolver
 */

import { obbSatCollideElements } from "./obbSatAdapter.js";
import { resolveCollision } from "./collisionDetection.js";
import { LAYOUT_LIMITS } from "./constants.js";
import type {
  LayoutElement,
  ConstraintViolation,
  ConstraintType,
} from "../../types/layout-composer/index.js";

// ── Resource defaults ──────────────────────────────────────────────────────────

/** Maximum collision pairs resolved per no_collision invocation. */
const DEFAULT_PAIR_CAP = LAYOUT_LIMITS.MAX_ELEMENTS * 2;

/** Maximum cumulative translation per element in px across a single solve pass. */
const DEFAULT_TRANSLATION_CAP_PX = 10_000;

// ── Types ──────────────────────────────────────────────────────────────────────

export interface ResolverOptions {
  /** Maximum pairs to evaluate. Default: MAX_ELEMENTS × 2. */
  pairCap?: number;
  /** Maximum cumulative translation per element in pixels. Default: 10 000. */
  translationCapPx?: number;
  /**
   * Wall-clock deadline as absolute epoch milliseconds (Date.now() + budget).
   * Resolution stops early when Date.now() > deadlineAbsolute.
   * Omit or pass Infinity to disable.
   */
  deadlineAbsolute?: number;
  /** Constraint id — used in warning violations. */
  constraintId: string;
  /** Solver iteration — included in warning detail. */
  iteration: number;
}

export interface RotationAwareResult {
  /** Per-element cumulative adjustments. Only populated for elements that moved. */
  adjustments: Record<string, { dx: number; dy: number }>;
  /** Warnings generated by cap or deadline enforcement. */
  warnings: ConstraintViolation[];
  pairsChecked: number;
  pairsResolved: number;
}

// ── Per-pair resolution ────────────────────────────────────────────────────────

/**
 * Resolves a single collision pair.
 *
 * Routing:
 *   - Both rotations = 0 → WP-03C AABB compatibility path (resolveCollision).
 *   - Either rotation ≠ 0 → WP-04A OBB/SAT path (obbSatCollideElements + MTV).
 *
 * Returns an empty map when there is no collision or both elements are locked.
 * Input elements are not mutated.
 */
export function resolveRotationAwarePair(
  a: LayoutElement,
  b: LayoutElement,
): Record<string, { dx: number; dy: number }> {
  const aRot = a.rotation ?? 0;
  const bRot = b.rotation ?? 0;
  const hasRotation = aRot !== 0 || bRot !== 0;

  if (!hasRotation) {
    // Zero-rotation compatibility path — WP-03C AABB resolver
    return resolveCollision(a, b);
  }

  // Rotation-aware narrow phase — WP-04A OBB/SAT
  const result = obbSatCollideElements(a, b);
  if (!result.collides) return {};
  if (a.locked && b.locked) return {};

  // MTV convention: resolvedPositionA = originalPositionA + mtv
  const mtv = result.minimumTranslationVector!;
  const adjustments: Record<string, { dx: number; dy: number }> = {};

  if (a.locked) {
    // A is fixed — push B opposite to A's MTV
    adjustments[b.id] = { dx: -mtv.x, dy: -mtv.y };
  } else if (b.locked) {
    // B is fixed — push A in the MTV direction
    adjustments[a.id] = { dx: mtv.x, dy: mtv.y };
  } else {
    // Neither locked — split the push evenly
    adjustments[a.id] = { dx:  mtv.x / 2, dy:  mtv.y / 2 };
    adjustments[b.id] = { dx: -mtv.x / 2, dy: -mtv.y / 2 };
  }

  return adjustments;
}

// ── Batch resolver ─────────────────────────────────────────────────────────────

/**
 * Resolves all collision pairs among `elements`, applying resource guards.
 *
 * Pair iteration stops when pairCap or deadlineAbsolute is reached.
 * Each element's cumulative translation is tracked against translationCapPx.
 * Adjustments are accumulated per element across all resolved pairs.
 *
 * Always returns a RotationAwareResult; `warnings` is populated when any
 * cap fires.
 */
export function resolveRotationAwareCollisions(
  elements: LayoutElement[],
  opts: ResolverOptions,
): RotationAwareResult {
  const pairCap        = opts.pairCap        ?? DEFAULT_PAIR_CAP;
  const translationCap = opts.translationCapPx ?? DEFAULT_TRANSLATION_CAP_PX;
  const deadlineAbs    = opts.deadlineAbsolute ?? Infinity;
  const cType: ConstraintType = "no_collision";

  const adjustments: Record<string, { dx: number; dy: number }> = {};
  const totalTranslation: Record<string, number> = {};
  const warnings: ConstraintViolation[] = [];
  const warnedElements = new Set<string>();

  let pairsChecked = 0;
  let pairsResolved = 0;
  let cappedByPairLimit = false;
  let timedOut = false;

  outer:
  for (let i = 0; i < elements.length; i++) {
    for (let j = i + 1; j < elements.length; j++) {
      if (pairsChecked >= pairCap) {
        cappedByPairLimit = true;
        break outer;
      }
      if (Date.now() > deadlineAbs) {
        timedOut = true;
        break outer;
      }

      pairsChecked++;

      const a = elements[i];
      const b = elements[j];
      const pairAdj = resolveRotationAwarePair(a, b);
      if (Object.keys(pairAdj).length === 0) continue;

      pairsResolved++;

      for (const [id, { dx, dy }] of Object.entries(pairAdj)) {
        const dist = Math.hypot(dx, dy);
        const runningTotal = (totalTranslation[id] ?? 0) + dist;

        if (runningTotal > translationCap) {
          // Translation cap hit — warn once per element
          if (!warnedElements.has(id)) {
            warnedElements.add(id);
            warnings.push({
              constraintId: opts.constraintId,
              constraintType: cType,
              elementIds: [id],
              message: `Element "${id}" hit translation cap (${translationCap}px) during rotation-aware collision resolution`,
              severity: "warning",
              detail: {
                translationCapPx: translationCap,
                accumulated: runningTotal,
                iteration: opts.iteration,
              },
            });
          }
          continue;
        }

        const curr = adjustments[id] ?? { dx: 0, dy: 0 };
        adjustments[id] = { dx: curr.dx + dx, dy: curr.dy + dy };
        totalTranslation[id] = runningTotal;
      }
    }
  }

  if (cappedByPairLimit) {
    warnings.push({
      constraintId: opts.constraintId,
      constraintType: cType,
      elementIds: elements.map((e) => e.id),
      message: `Collision resolution stopped at pair cap (${pairCap}) on iteration ${opts.iteration}`,
      severity: "warning",
      detail: {
        pairCap,
        pairsChecked,
        pairsResolved,
        iteration: opts.iteration,
      },
    });
  } else if (timedOut) {
    warnings.push({
      constraintId: opts.constraintId,
      constraintType: cType,
      elementIds: elements.map((e) => e.id),
      message: `Collision resolution timed out after ${pairsChecked} pairs on iteration ${opts.iteration}`,
      severity: "warning",
      detail: {
        pairsChecked,
        pairsResolved,
        iteration: opts.iteration,
      },
    });
  }

  return { adjustments, warnings, pairsChecked, pairsResolved };
}
