/**
 * Generates CREATE TABLE IF NOT EXISTS DDL for all tables in ai_platform
 * that exist in dev but not in prod, then writes to migration_prod.sql
 *
 * Run from repo root: npx tsx lib/db/src/scripts/generateMigrationDDL.ts
 */
import pg from "pg";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const { Pool } = pg;
const __dirname = path.dirname(fileURLToPath(import.meta.url));

function makePool(url: string) {
  return new Pool({
    connectionString: url,
    ssl: { rejectUnauthorized: false },
    options: "-c search_path=ai_platform,public",
    max: 3,
  });
}

const devPool = makePool(process.env.SUPABASE_DEV_DATABASE_URL!);
const prodPool = makePool(process.env.SUPABASE_PROD_DATABASE_URL!);

const dev = await devPool.connect();
const prod = await prodPool.connect();

// ─── 1. Compute missing tables ────────────────────────────────────────────────
const [devTablesRes, prodTablesRes] = await Promise.all([
  dev.query<{ table_name: string }>(
    `SELECT table_name FROM information_schema.tables WHERE table_schema='ai_platform' ORDER BY table_name`
  ),
  prod.query<{ table_name: string }>(
    `SELECT table_name FROM information_schema.tables WHERE table_schema='ai_platform' ORDER BY table_name`
  ),
]);

const prodSet = new Set(prodTablesRes.rows.map((r) => r.table_name));
const missingTables = devTablesRes.rows
  .map((r) => r.table_name)
  .filter((t) => !prodSet.has(t));

console.log(`Dev: ${devTablesRes.rows.length} | Prod: ${prodSet.size} | Missing: ${missingTables.length}`);
console.log("Missing:", missingTables.join(", "));

// ─── 2. Generate DDL ──────────────────────────────────────────────────────────
const lines: string[] = [
  "-- Auto-generated migration: dev → prod (additive only)",
  `-- Generated: ${new Date().toISOString()}`,
  "-- Missing tables: " + missingTables.length,
  "",
  "SET search_path TO ai_platform, public;",
  "",
];

function mapType(col: {
  data_type: string; udt_name: string;
  character_maximum_length: number|null; numeric_precision: number|null;
  numeric_scale: number|null; column_default: string|null;
  is_identity: string; identity_generation: string|null;
}): string {
  if (col.is_identity === "YES") {
    return col.identity_generation === "ALWAYS"
      ? "BIGINT GENERATED ALWAYS AS IDENTITY"
      : "BIGINT GENERATED BY DEFAULT AS IDENTITY";
  }
  const dt = col.data_type;
  if (col.column_default?.startsWith("nextval(") && dt === "integer") return "SERIAL";
  if (col.column_default?.startsWith("nextval(") && dt === "bigint")  return "BIGSERIAL";
  if (dt === "character varying") return col.character_maximum_length ? `VARCHAR(${col.character_maximum_length})` : "TEXT";
  if (dt === "character") return `CHAR(${col.character_maximum_length ?? 1})`;
  if (dt === "numeric") return (col.numeric_precision != null && col.numeric_scale != null) ? `NUMERIC(${col.numeric_precision},${col.numeric_scale})` : "NUMERIC";
  if (dt === "ARRAY") {
    const base = col.udt_name.startsWith("_") ? col.udt_name.slice(1) : col.udt_name;
    // map common pg type names
    const pgToSql: Record<string, string> = { int4: "INTEGER", int8: "BIGINT", text: "TEXT", bool: "BOOLEAN", float8: "DOUBLE PRECISION", jsonb: "JSONB", json: "JSON", uuid: "UUID", timestamptz: "TIMESTAMPTZ", timestamp: "TIMESTAMP" };
    return (pgToSql[base] ?? base.toUpperCase()) + "[]";
  }
  if (dt === "USER-DEFINED") return col.udt_name;
  if (dt === "timestamp without time zone") return "TIMESTAMP";
  if (dt === "timestamp with time zone") return "TIMESTAMPTZ";
  if (dt === "time without time zone") return "TIME";
  if (dt === "time with time zone") return "TIMETZ";
  if (dt === "double precision") return "DOUBLE PRECISION";
  return dt.toUpperCase();
}

for (const table of missingTables) {
  const [colsRes, pkRes, uqRes, chkRes] = await Promise.all([
    dev.query<{
      column_name: string; data_type: string; udt_name: string;
      character_maximum_length: number|null; numeric_precision: number|null;
      numeric_scale: number|null; is_nullable: string;
      column_default: string|null; is_identity: string; identity_generation: string|null;
    }>(
      `SELECT column_name, data_type, udt_name, character_maximum_length,
              numeric_precision, numeric_scale, is_nullable, column_default,
              is_identity, identity_generation
       FROM information_schema.columns
       WHERE table_schema='ai_platform' AND table_name=$1
       ORDER BY ordinal_position`,
      [table]
    ),
    dev.query<{ column_name: string }>(
      `SELECT kcu.column_name FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
       WHERE tc.constraint_type='PRIMARY KEY' AND tc.table_schema='ai_platform' AND tc.table_name=$1
       ORDER BY kcu.ordinal_position`,
      [table]
    ),
    dev.query<{ constraint_name: string; column_name: string }>(
      `SELECT tc.constraint_name, kcu.column_name
       FROM information_schema.table_constraints tc
       JOIN information_schema.key_column_usage kcu
         ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema
       WHERE tc.constraint_type='UNIQUE' AND tc.table_schema='ai_platform' AND tc.table_name=$1
       ORDER BY tc.constraint_name, kcu.ordinal_position`,
      [table]
    ),
    dev.query<{ constraint_name: string; check_clause: string }>(
      `SELECT cc.constraint_name, cc.check_clause
       FROM information_schema.check_constraints cc
       JOIN information_schema.table_constraints tc
         ON cc.constraint_name=tc.constraint_name AND cc.constraint_schema=tc.constraint_schema
       WHERE tc.table_schema='ai_platform' AND tc.table_name=$1`,
      [table]
    ),
  ]);

  const pkCols = pkRes.rows.map((r) => r.column_name);
  const uqMap = new Map<string, string[]>();
  for (const r of uqRes.rows) {
    if (!uqMap.has(r.constraint_name)) uqMap.set(r.constraint_name, []);
    uqMap.get(r.constraint_name)!.push(r.column_name);
  }

  const colDefs: string[] = [];
  for (const col of colsRes.rows) {
    const type = mapType(col);
    const nullable = col.is_nullable === "YES" ? "" : " NOT NULL";
    let def = "";
    if (col.column_default && !col.column_default.startsWith("nextval(") && col.is_identity !== "YES") {
      def = ` DEFAULT ${col.column_default}`;
    }
    colDefs.push(`  ${col.column_name} ${type}${def}${nullable}`);
  }

  // Attach PK
  if (pkCols.length === 1) {
    const idx = colDefs.findIndex((c) => c.trimStart().startsWith(pkCols[0] + " "));
    if (idx >= 0) colDefs[idx] += " PRIMARY KEY";
  } else if (pkCols.length > 1) {
    colDefs.push(`  PRIMARY KEY (${pkCols.join(", ")})`);
  }

  // Unique constraints
  for (const [name, cols] of uqMap) {
    colDefs.push(`  CONSTRAINT ${name} UNIQUE (${cols.join(", ")})`);
  }

  // Check constraints (skip IS NOT NULL auto-checks)
  for (const chk of chkRes.rows) {
    if (!chk.check_clause.includes("IS NOT NULL")) {
      colDefs.push(`  CONSTRAINT ${chk.constraint_name} CHECK (${chk.check_clause})`);
    }
  }

  lines.push(`-- table: ${table}`);
  lines.push(`CREATE TABLE IF NOT EXISTS ai_platform.${table} (`);
  lines.push(colDefs.join(",\n"));
  lines.push(`);`);
  lines.push("");
}

// ─── 3. Write SQL ─────────────────────────────────────────────────────────────
const sqlPath = path.join(__dirname, "migration_prod.sql");
fs.writeFileSync(sqlPath, lines.join("\n"), "utf8");
console.log(`\n✅ Written to ${sqlPath} (${lines.length} lines)`);

dev.release(); prod.release();
await devPool.end(); await prodPool.end();
