export const DESIGN_TEMPLATE_SCHEMA_VERSION = "1.0";

export const DESIGN_LIMITS = {
  MAX_CANVAS_WIDTH: 8000,
  MAX_CANVAS_HEIGHT: 8000,
  MAX_ELEMENT_COUNT: 200,
  MAX_VARIABLE_COUNT: 50,
  MIN_FONT_SIZE: 6,
} as const;
