/**
 * Controlled local export fixture.
 *
 * This is intentionally not scraped and is not a claim that the live Niro
 * Granite website is an authorized machine-readable source. It exercises the
 * approved official-feed shape until a written feed/API authorization exists.
 */
export const NIRO_GRANITE_FIXTURE: ReadonlyArray<Record<string, unknown>> = [
  {
    externalId: "NG-FLR-001",
    productCode: "NG-FLR-001",
    productName: "Calacatta Gold Polished",
    brand: "Niro Granite",
    category: "flooring",
    subcategory: "porcelain tile",
    materialType: "porcelain",
    description: "Large-format porcelain tile with a polished finish.",
    color: ["white", "gold"],
    finish: ["polished"],
    texture: "smooth",
    pattern: "veined",
    priceTier: "premium",
    unit: "m²",
    dimensions: { width: 600, height: 600, thickness: 10, unit: "mm" },
    technicalData: { waterAbsorption: "<0.5%" },
    certifications: ["ISO 13006"],
    sourceUrl: "https://www.nirogranite.com/products/NG-FLR-001",
    thumbnailReference: "https://www.nirogranite.com/images/NG-FLR-001.jpg",
    previewReferences: ["https://www.nirogranite.com/images/NG-FLR-001-detail.jpg"],
    country: "ID",
    locale: "id-ID",
    sourceUpdatedAt: "2026-01-10T00:00:00.000Z",
    sourceMetadata: { exportVersion: "v1", suppliedAs: "controlled-local-fixture" },
  },
  {
    externalId: "NG-FLR-002",
    productCode: "NG-FLR-002",
    productName: "Pietra Grey Honed",
    brand: "Niro Granite",
    category: "flooring",
    subcategory: "porcelain tile",
    materialType: "porcelain",
    description: "Grey stone-look porcelain with a honed finish.",
    color: ["grey"],
    finish: ["honed"],
    texture: "smooth",
    pattern: "stone",
    priceTier: "standard",
    unit: "m²",
    dimensions: { width: 800, height: 800, thickness: 10, unit: "mm" },
    sourceUrl: "https://www.nirogranite.com/products/NG-FLR-002",
    country: "ID",
    locale: "id-ID",
    sourceUpdatedAt: "2026-01-11T00:00:00.000Z",
    sourceMetadata: { exportVersion: "v1", suppliedAs: "controlled-local-fixture" },
  },
  {
    externalId: "NG-WLL-001",
    productCode: "NG-WLL-001",
    productName: "Subway White Gloss",
    brand: "Niro Granite",
    category: "wall tile",
    subcategory: "ceramic",
    materialType: "ceramic",
    color: ["white"],
    finish: ["gloss"],
    priceTier: "economy",
    unit: "m²",
    dimensions: { width: 75, height: 150, unit: "mm" },
    sourceUrl: "https://www.nirogranite.com/products/NG-WLL-001",
    country: "ID",
    locale: "id-ID",
    sourceUpdatedAt: "2026-01-12T00:00:00.000Z",
    sourceMetadata: { exportVersion: "v1", suppliedAs: "controlled-local-fixture" },
  },
  {
    externalId: "NG-HW-001",
    productCode: "NG-HW-001",
    productName: "Matte Black Door Handle Set",
    brand: "Niro Granite",
    category: "hardware",
    subcategory: "door hardware",
    materialType: "stainless steel",
    color: ["black"],
    finish: ["matte"],
    priceTier: "standard",
    unit: "pcs",
    technicalData: { installation: "surface mounted" },
    sourceUrl: "https://www.nirogranite.com/products/NG-HW-001",
    country: "ID",
    locale: "id-ID",
    sourceUpdatedAt: "2026-01-13T00:00:00.000Z",
    sourceMetadata: { exportVersion: "v1", suppliedAs: "controlled-local-fixture" },
  },
  {
    externalId: "NG-INVALID-001",
    productCode: "NG-INVALID-001",
    brand: "Niro Granite",
    category: "flooring",
    sourceUrl: "http://unsafe.example.invalid/item",
    country: "ID",
    locale: "id-ID",
    sourceMetadata: { exportVersion: "v1", suppliedAs: "controlled-local-fixture" },
  },
];