#!/usr/bin/env tsx
/**
 * Workspace Health Checker — Phase 5.1.5
 *
 * Validates the monorepo build system before codegen or build:
 *   - No manually edited generated files
 *   - No stale dist/ directories
 *   - No duplicate exports in generated packages
 *   - No orphan files in generated directories
 *
 * Exit 0 = healthy. Exit 1 = issues found (with clear messages).
 *
 * Usage:
 *   tsx scripts/src/workspace-check.ts          — full check (fails on issues)
 *   tsx scripts/src/workspace-check.ts --health  — print health JSON and exit 0
 */

import fs from "node:fs";
import path from "node:path";
import { parse as parseYaml } from "yaml";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const GENERATED_DIRS = [
  "lib/api-client-react/src/generated",
  "lib/api-zod/src/generated",
];
const DIST_DIRS = [
  "artifacts/api-server/dist",
];
const SOURCE_DIRS = [
  "artifacts/api-server/src",
];
const ORVAL_HEADER = "Generated by orval";

// ── Types ─────────────────────────────────────────────────────────────────────

interface CheckResult {
  name: string;
  status: "ok" | "warn" | "fail";
  message: string;
  details?: string[];
}

interface HealthReport {
  timestamp: string;
  overall: "healthy" | "degraded" | "unhealthy";
  checks: CheckResult[];
  generatedStatus: Record<string, GeneratedStatus>;
  distStatus: Record<string, DistStatus>;
}

interface GeneratedStatus {
  exists: boolean;
  fileCount: number;
  lastModified: string | null;
  hasOrvalHeader: boolean;
}

interface DistStatus {
  exists: boolean;
  fileCount: number;
  stale: boolean;
  lastModified: string | null;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function abs(rel: string): string {
  return path.join(ROOT, rel);
}

function walkFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...walkFiles(full));
    else files.push(full);
  }
  return files;
}

function lastModifiedMs(dir: string): number {
  const files = walkFiles(dir);
  if (files.length === 0) return 0;
  return Math.max(...files.map((f) => fs.statSync(f).mtimeMs));
}

// ── Checks ────────────────────────────────────────────────────────────────────

function checkGeneratedHeaders(): CheckResult {
  const tampered: string[] = [];

  for (const genDir of GENERATED_DIRS) {
    const full = abs(genDir);
    if (!fs.existsSync(full)) continue;
    for (const file of walkFiles(full)) {
      if (!file.endsWith(".ts")) continue;
      const content = fs.readFileSync(file, "utf8");
      // Generated files must start with the orval header comment
      if (!content.includes(ORVAL_HEADER)) {
        tampered.push(path.relative(ROOT, file));
      }
    }
  }

  if (tampered.length === 0) {
    return { name: "generated-headers", status: "ok", message: "All generated files have orval headers" };
  }

  return {
    name: "generated-headers",
    status: "fail",
    message: `${tampered.length} generated file(s) appear manually edited (missing orval header)`,
    details: tampered,
  };
}

function checkStaleDistDirs(): CheckResult {
  const stale: string[] = [];

  for (let i = 0; i < DIST_DIRS.length; i++) {
    const distDir = DIST_DIRS[i];
    const srcDir  = SOURCE_DIRS[i];
    if (!srcDir) continue;

    const distFull = abs(distDir);
    const srcFull  = abs(srcDir);

    if (!fs.existsSync(distFull)) continue; // no dist = not stale, just not built
    if (!fs.existsSync(srcFull))  continue;

    const distTime = lastModifiedMs(distFull);
    const srcTime  = lastModifiedMs(srcFull);

    if (srcTime > distTime + 5_000) { // 5s grace period
      stale.push(distDir);
    }
  }

  if (stale.length === 0) {
    return { name: "stale-dist", status: "ok", message: "All dist directories are up to date" };
  }

  return {
    name: "stale-dist",
    status: "warn",
    message: `${stale.length} dist director(ies) may be stale — run pnpm run build:api to rebuild`,
    details: stale,
  };
}

function checkDuplicateExports(): CheckResult {
  // A name may legitimately appear twice in the same file as a const+type pair
  // (orval's `export const X = {...} as const` + `export type X = (typeof X)[...]`
  // enum pattern). Only flag: (a) the same name+kind declared more than once
  // anywhere, or (b) the same name declared in more than one distinct file.
  const issues: string[] = [];

  for (const genDir of GENERATED_DIRS) {
    const full = abs(genDir);
    if (!fs.existsSync(full)) continue;

    // name -> kind -> file -> occurrence count (catches same-file same-kind dups)
    const byNameKind = new Map<string, Map<string, Map<string, number>>>();
    // name -> Set<file> (any kind), to detect cross-file duplicates
    const byNameFiles = new Map<string, Set<string>>();

    for (const file of walkFiles(full)) {
      if (!file.endsWith(".ts")) continue;
      const content = fs.readFileSync(file, "utf8");
      const relFile = path.relative(ROOT, file);
      const matches = content.matchAll(/^export\s+(const|function|class|interface|type|enum)\s+(\w+)/gm);
      for (const m of matches) {
        const kind = m[1];
        const name = m[2];

        const kindMap = byNameKind.get(name) ?? new Map<string, Map<string, number>>();
        const fileCounts = kindMap.get(kind) ?? new Map<string, number>();
        fileCounts.set(relFile, (fileCounts.get(relFile) ?? 0) + 1);
        kindMap.set(kind, fileCounts);
        byNameKind.set(name, kindMap);

        const fileSet = byNameFiles.get(name) ?? new Set<string>();
        fileSet.add(relFile);
        byNameFiles.set(name, fileSet);
      }
    }

    // (a) same name+kind declared more than once, either repeated within a
    // single file or spread across multiple files (real duplicate declaration)
    for (const [name, kindMap] of byNameKind) {
      for (const [kind, fileCounts] of kindMap) {
        const totalOccurrences = [...fileCounts.values()].reduce((a, b) => a + b, 0);
        const repeatedInSameFile = [...fileCounts.entries()].filter(([, count]) => count > 1);
        if (repeatedInSameFile.length > 0) {
          for (const [file, count] of repeatedInSameFile) {
            issues.push(`'${name}' (${kind}) declared ${count} times in ${file}`);
          }
        } else if (totalOccurrences > 1) {
          issues.push(`'${name}' (${kind}) declared in multiple files: ${[...fileCounts.keys()].join(", ")}`);
        }
      }
    }

    // (b) same name declared across more than one distinct file (any kind mix)
    for (const [name, files] of byNameFiles) {
      if (files.size > 1) {
        const already = issues.some((i) => i.startsWith(`'${name}' `));
        if (!already) {
          issues.push(`'${name}' exported from multiple files: ${[...files].join(", ")}`);
        }
      }
    }
  }

  if (issues.length === 0) {
    return { name: "duplicate-exports", status: "ok", message: "No duplicate exports found in generated files" };
  }

  return {
    name: "duplicate-exports",
    status: "fail",
    message: `${issues.length} duplicate export(s) found in generated files`,
    details: issues.slice(0, 20), // cap output
  };
}

function checkGeneratedDirsExist(): CheckResult {
  const missing: string[] = [];

  for (const genDir of GENERATED_DIRS) {
    if (!fs.existsSync(abs(genDir))) {
      missing.push(genDir);
    }
  }

  if (missing.length === 0) {
    return { name: "generated-dirs", status: "ok", message: "All generated directories exist" };
  }

  return {
    name: "generated-dirs",
    status: "fail",
    message: `${missing.length} generated director(ies) missing — run pnpm run build:generated`,
    details: missing,
  };
}

function checkOpenApiSpec(): CheckResult {
  const specPath = abs("lib/api-spec/openapi.yaml");
  if (!fs.existsSync(specPath)) {
    return { name: "openapi-spec", status: "fail", message: "lib/api-spec/openapi.yaml not found" };
  }

  const content = fs.readFileSync(specPath, "utf8");

  // Real YAML parse — the `yaml` package throws on duplicate keys within the
  // same mapping (e.g. two `tags:` in one operation), which is exactly the
  // GitHub-import concatenation bug this check exists to catch. A regex-based
  // heuristic here previously false-flagged legitimate repeated `tags:` across
  // unrelated path blocks — always prefer a real parser for structural checks.
  let spec: { paths?: Record<string, Record<string, { operationId?: string }>> };
  try {
    spec = parseYaml(content, { maxAliasCount: 10000, merge: true });
  } catch (err) {
    return {
      name: "openapi-spec",
      status: "fail",
      message: "OpenAPI spec failed to parse as YAML (likely duplicate keys from a concatenated file)",
      details: [err instanceof Error ? err.message : String(err)],
    };
  }

  // Detect duplicate operationId across the whole spec (must be globally unique)
  const operationIds: string[] = [];
  for (const methods of Object.values(spec.paths ?? {})) {
    for (const op of Object.values(methods)) {
      if (op?.operationId) operationIds.push(op.operationId);
    }
  }
  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const id of operationIds) {
    if (seen.has(id)) duplicates.push(id);
    seen.add(id);
  }

  if (duplicates.length > 0) {
    return {
      name: "openapi-spec",
      status: "fail",
      message: "OpenAPI spec has duplicate operationIds",
      details: [`Duplicate operationIds: ${duplicates.join(", ")}`],
    };
  }

  return { name: "openapi-spec", status: "ok", message: `OpenAPI spec is clean (${operationIds.length} operations)` };
}

// ── Health report ─────────────────────────────────────────────────────────────

function buildHealthReport(checks: CheckResult[]): HealthReport {
  const generatedStatus: Record<string, GeneratedStatus> = {};
  for (const genDir of GENERATED_DIRS) {
    const full = abs(genDir);
    const exists = fs.existsSync(full);
    const files = exists ? walkFiles(full).filter((f) => f.endsWith(".ts")) : [];
    const lastMod = files.length > 0
      ? new Date(Math.max(...files.map((f) => fs.statSync(f).mtimeMs))).toISOString()
      : null;
    const hasOrvalHeader = files.every((f) => fs.readFileSync(f, "utf8").includes(ORVAL_HEADER));
    generatedStatus[genDir] = { exists, fileCount: files.length, lastModified: lastMod, hasOrvalHeader };
  }

  const distStatus: Record<string, DistStatus> = {};
  for (let i = 0; i < DIST_DIRS.length; i++) {
    const distDir = DIST_DIRS[i];
    const srcDir  = SOURCE_DIRS[i];
    const full = abs(distDir);
    const exists = fs.existsSync(full);
    const files = exists ? walkFiles(full) : [];
    const lastMod = files.length > 0
      ? new Date(Math.max(...files.map((f) => fs.statSync(f).mtimeMs))).toISOString()
      : null;
    let stale = false;
    if (srcDir && exists) {
      const distTime = lastModifiedMs(full);
      const srcTime  = lastModifiedMs(abs(srcDir));
      stale = srcTime > distTime + 5_000;
    }
    distStatus[distDir] = { exists, fileCount: files.length, stale, lastModified: lastMod };
  }

  const hasFails = checks.some((c) => c.status === "fail");
  const hasWarns = checks.some((c) => c.status === "warn");
  const overall = hasFails ? "unhealthy" : hasWarns ? "degraded" : "healthy";

  return {
    timestamp: new Date().toISOString(),
    overall,
    checks,
    generatedStatus,
    distStatus,
  };
}

// ── Main ──────────────────────────────────────────────────────────────────────

const isHealthMode = process.argv.includes("--health");

const checks: CheckResult[] = [
  checkOpenApiSpec(),
  checkGeneratedDirsExist(),
  checkGeneratedHeaders(),
  checkStaleDistDirs(),
  checkDuplicateExports(),
];

if (isHealthMode) {
  const report = buildHealthReport(checks);
  console.log(JSON.stringify(report, null, 2));
  process.exit(0);
}

// Standard check mode: print results and fail if any check failed
let hasFailures = false;
for (const check of checks) {
  const icon = check.status === "ok" ? "✅" : check.status === "warn" ? "⚠️ " : "❌";
  console.log(`${icon} [${check.name}] ${check.message}`);
  if (check.details) {
    for (const d of check.details) console.log(`   • ${d}`);
  }
  if (check.status === "fail") hasFailures = true;
}

if (hasFailures) {
  console.error("\n❌ Workspace check failed — fix the issues above before building.");
  process.exit(1);
} else {
  console.log("\n✅ Workspace is healthy.");
  process.exit(0);
}
