/**
 * executionSummaryService.ts — V4.1 AI Execution Summary Layer
 *
 * Pure, deterministic, NON-LLM adapter that turns an existing CanonicalEvent
 * (see canonicalEventService.ts) into a customer-safe ExecutionSummary: a
 * short, human title, a plain-language "why it matters" note, and a
 * derived "next step" — all built from a fixed template library, never
 * generated by a model and never varying between calls for the same input.
 *
 * Hard security rules (never violate):
 *   - Never read/expose: prompts, reasoning, system prompts, raw provider
 *     output, stack traces, API keys/secrets, cost or margin data, or any
 *     internal error text.
 *   - Only reads fields already present on CanonicalEvent (itself already
 *     scrubbed by canonicalEventService) plus the small, explicit
 *     SummaryContext below. No DB access happens in this file.
 *   - customerAction only ever points at a tab/action that already exists in
 *     the customer portal (Files, Reviews, Payments, Support) — never a
 *     fabricated route.
 *
 * Determinism contract: buildExecutionSummary(event, context) is a pure
 * function of its arguments. Same event + same context => same output,
 * every time, for every caller (REST, SSE snapshot, SSE fan-out).
 */
import type { CanonicalEvent, CanonicalEventType } from "./canonicalEventService.js";

// ─────────────────────────────────────────────────────────────────────────────
// Public model
// ─────────────────────────────────────────────────────────────────────────────

export type SummaryStatus = "info" | "success" | "warning" | "error";

/** The only customer-portal destinations a summary is allowed to point at. */
export type CustomerActionKind = "view_review" | "view_files" | "view_payments" | "contact_support";

export interface CustomerAction {
  kind: CustomerActionKind;
  label: string;
}

export interface ExecutionSummary {
  /** Ties this summary back to the CanonicalEvent it was derived from. */
  sourceEventId: string;
  eventType: CanonicalEventType;
  /** Short customer-facing headline, e.g. "Brand Analysis Completed". */
  title: string;
  /** One or two plain-language sentences — reuses the event's own vetted publicMessage. */
  summary: string;
  /** Plain-language explanation of why this step matters to the customer's project. */
  whyItMatters: string;
  /** What happens next, in plain language. Null when there is nothing further to say. */
  nextStep: string | null;
  /** Coarse status for badge styling. */
  status: SummaryStatus;
  /** Optional call-to-action, only ever pointing at an existing portal tab/action. */
  customerAction: CustomerAction | null;
  /** Always true — marks this object as derived/template output, never raw. */
  isDerived: true;
  artifactCount: number;
}

export interface WorkflowStepContext {
  stepName: string;
  status: string;
}

/** Small, explicit, customer-safe context — no raw DB rows, no secrets. */
export interface SummaryContext {
  /** Ordered per the real pipeline (mirrors STEP_PIPELINE). */
  steps: WorkflowStepContext[];
  /** Latest review status observed for the project, if any. */
  latestReviewStatus: string | null;
  /** Whether files are currently unlocked for download. */
  filesUnlocked: boolean;
  /** Count of artifacts created so far — used only for the artifactCount field, never invented. */
  artifactCount: number;
}

export const EMPTY_SUMMARY_CONTEXT: SummaryContext = {
  steps: [],
  latestReviewStatus: null,
  filesUnlocked: false,
  artifactCount: 0,
};

// ─────────────────────────────────────────────────────────────────────────────
// Public step-name dictionary
// Internal step keys (creative_project_steps.stepName / STEP_PIPELINE) are
// NEVER renamed — this is a display-only translation layer.
// ─────────────────────────────────────────────────────────────────────────────

const PUBLIC_STEP_LABELS: Record<string, string> = {
  "Brand Strategy": "Brand Analysis",
  "Creative Direction": "Creative Direction",
  "Copy Production": "Copywriting",
  "Quality Control": "Quality Review",
};

export function publicStepLabel(stepName: string): string {
  return PUBLIC_STEP_LABELS[stepName] ?? stepName;
}

// ─────────────────────────────────────────────────────────────────────────────
// "Why it matters" library — keyed by the internal step name.
// ─────────────────────────────────────────────────────────────────────────────

const WHY_IT_MATTERS_BY_STEP: Record<string, string> = {
  "Brand Strategy":
    "This sets the strategic direction — positioning, audience, and messaging — that every later step is built on.",
  "Creative Direction":
    "This defines the visual and tonal identity that will be used consistently across all your deliverables.",
  "Copy Production":
    "This produces the actual wording your audience will read, aligned to the strategy and creative direction above.",
  "Quality Control":
    "This is the final internal check to make sure everything meets your brief before it's shared with you.",
};

const WHY_IT_MATTERS_BY_SOURCE: Record<CanonicalEvent["source"], string> = {
  project: "This marks a milestone in your overall project timeline.",
  step: "This is one of the production steps your AI team completes on the way to your final deliverables.",
  worker: "This shows which AI specialist is actively working on your project right now.",
  artifact: "This is a deliverable being produced for your brand — it will end up in your Brand Asset Library.",
  review: "Your decision here directly controls whether production continues or a revision is made.",
};

function whyItMatters(event: CanonicalEvent): string {
  const stepName = event.metadata.stepName;
  if (stepName && WHY_IT_MATTERS_BY_STEP[stepName]) return WHY_IT_MATTERS_BY_STEP[stepName];
  return WHY_IT_MATTERS_BY_SOURCE[event.source];
}

// ─────────────────────────────────────────────────────────────────────────────
// Title template library — keyed by eventType. Values are functions of the
// (already customer-safe) public step label so they read naturally, e.g.
// "Brand Analysis Completed" instead of a generic "Step Completed".
// ─────────────────────────────────────────────────────────────────────────────

type TitleTemplate = (label: string) => string;

const STEP_TITLES: Record<string, TitleTemplate> = {
  "step.queued": (l) => `${l} Queued`,
  "step.started": (l) => `${l} In Progress`,
  "step.completed": (l) => `${l} Completed`,
  "step.failed": (l) => `${l} Needs Attention`,
  "step.blocked": (l) => `${l} Paused`,
  "worker.assigned": (l) => `${l} — AI Assigned`,
  "worker.started": (l) => `${l} In Progress`,
  "worker.completed": (l) => `${l} Completed`,
  "worker.failed": (l) => `${l} Needs Attention`,
};

const ARTIFACT_TITLES: Partial<Record<CanonicalEventType, string>> = {
  "artifact.queued": "Visual Asset Queued",
  "artifact.generating": "Visual Asset In Progress",
  "artifact.created": "New Visual Ready for Review",
  "artifact.approved": "Visual Asset Approved",
  "artifact.revision_requested": "Visual Asset Revision Requested",
  "artifact.failed": "Visual Asset Needs Attention",
};

const REVIEW_TITLES: Partial<Record<CanonicalEventType, string>> = {
  "review.requested": "Your Review Is Needed",
  "review.started": "Review Opened",
  "review.approved": "Review Approved",
  "review.revision_requested": "Revision Requested",
  "review.completed": "Review Cycle Completed",
};

const PROJECT_TITLES: Partial<Record<CanonicalEventType, string>> = {
  "project.created": "Project Created",
  "project.workflow_started": "AI Production Started",
  "project.completed": "Project Completed",
  "project.failed": "Project Needs Attention",
};

function deriveTitle(event: CanonicalEvent): string {
  const label = event.metadata.stepName ? publicStepLabel(event.metadata.stepName) : null;
  if (label && STEP_TITLES[event.eventType]) return STEP_TITLES[event.eventType](label);
  if (event.source === "artifact") return ARTIFACT_TITLES[event.eventType] ?? "Visual Asset Update";
  if (event.source === "review") return REVIEW_TITLES[event.eventType] ?? "Review Update";
  if (event.source === "project") return PROJECT_TITLES[event.eventType] ?? "Project Update";
  // Fallback — still deterministic, still safe (uses only the eventType string).
  return event.eventType.replace(/[._]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

// ─────────────────────────────────────────────────────────────────────────────
// Status mapping — coarse bucket for UI badges.
// ─────────────────────────────────────────────────────────────────────────────

function deriveStatus(event: CanonicalEvent): SummaryStatus {
  if (event.severity === "error") return "error";
  if (event.severity === "warning") return "warning";
  const successTypes: ReadonlySet<CanonicalEventType> = new Set([
    "step.completed",
    "worker.completed",
    "artifact.approved",
    "artifact.created",
    "review.approved",
    "project.completed",
  ]);
  return successTypes.has(event.eventType) ? "success" : "info";
}

// ─────────────────────────────────────────────────────────────────────────────
// Next-step derivation — driven by real workflow context, never a hardcoded
// universal order. Falls back to null (no next step known) rather than
// guessing.
// ─────────────────────────────────────────────────────────────────────────────

function nextPipelineStep(context: SummaryContext, currentStepName: string): WorkflowStepContext | null {
  const idx = context.steps.findIndex((s) => s.stepName === currentStepName);
  if (idx === -1) return null;
  return context.steps[idx + 1] ?? null;
}

function deriveNextStep(event: CanonicalEvent, context: SummaryContext): string | null {
  switch (event.eventType) {
    case "step.completed":
    case "worker.completed": {
      const stepName = event.metadata.stepName;
      if (!stepName) return null;
      const next = nextPipelineStep(context, stepName);
      if (next) return `${publicStepLabel(next.stepName)} will begin next.`;
      return "Your creative assets will be ready for review shortly.";
    }
    case "step.failed":
    case "worker.failed":
      return "Our team has been notified and will follow up shortly.";
    case "step.blocked":
      return "Production will resume automatically once our team reviews the project budget.";
    case "artifact.created":
      return context.latestReviewStatus ? null : "This will be shared with you for review shortly.";
    case "artifact.revision_requested":
      return "Our design team will revise this asset based on the feedback given.";
    case "artifact.failed":
      return "Our team has been notified and will regenerate this asset.";
    case "review.requested":
      return "Please review and either approve it or request a revision.";
    case "review.approved":
      return context.filesUnlocked
        ? "Your files are ready to download."
        : "Final files will be unlocked once production wraps up.";
    case "review.revision_requested":
      return "Our team will revise the work based on your feedback.";
    case "project.workflow_started":
      return context.steps.length > 0
        ? `${publicStepLabel(context.steps[0].stepName)} will start shortly.`
        : "Your AI team will begin production shortly.";
    case "project.completed":
      return context.filesUnlocked
        ? "All your deliverables are ready in the Files tab."
        : "Your final files will be unlocked shortly.";
    case "project.failed":
      return "Our team has been notified and will follow up with you shortly.";
    default:
      return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Customer action derivation — only ever one of the fixed kinds above, each
// of which maps to a tab/action that already exists in the customer portal.
// ─────────────────────────────────────────────────────────────────────────────

function deriveCustomerAction(event: CanonicalEvent, context: SummaryContext): CustomerAction | null {
  switch (event.eventType) {
    case "review.requested":
      return { kind: "view_review", label: "Review Now" };
    case "review.approved":
      return context.filesUnlocked ? { kind: "view_files", label: "Download Files" } : null;
    case "project.completed":
      return context.filesUnlocked ? { kind: "view_files", label: "View Files" } : null;
    case "step.failed":
    case "worker.failed":
    case "artifact.failed":
    case "project.failed":
      return { kind: "contact_support", label: "Contact Support" };
    case "step.blocked":
      return { kind: "contact_support", label: "Contact Support" };
    default:
      return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Public builder API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build a single ExecutionSummary for one CanonicalEvent. Pure and
 * deterministic — never touches the DB, never calls a model.
 */
export function buildExecutionSummary(
  event: CanonicalEvent,
  context: SummaryContext = EMPTY_SUMMARY_CONTEXT,
): ExecutionSummary {
  return {
    sourceEventId: event.eventId,
    eventType: event.eventType,
    title: deriveTitle(event),
    // Reuse the already-vetted, customer-safe publicMessage as the summary
    // body rather than re-deriving text — it is itself deterministic and
    // has never contained a banned field.
    summary: event.publicMessage,
    whyItMatters: whyItMatters(event),
    nextStep: deriveNextStep(event, context),
    status: deriveStatus(event),
    customerAction: deriveCustomerAction(event, context),
    isDerived: true,
    artifactCount: context.artifactCount,
  };
}

/** Batch version — same context reused for every event, no repeated derivation cost. */
export function buildExecutionSummaries(
  events: CanonicalEvent[],
  context: SummaryContext = EMPTY_SUMMARY_CONTEXT,
): ExecutionSummary[] {
  return events.map((e) => buildExecutionSummary(e, context));
}

/** Convenience pairing helper used by API/SSE wiring. */
export interface EventWithSummary {
  event: CanonicalEvent;
  summary: ExecutionSummary;
}

export function pairEventsWithSummaries(
  events: CanonicalEvent[],
  context: SummaryContext = EMPTY_SUMMARY_CONTEXT,
): EventWithSummary[] {
  return events.map((event) => ({ event, summary: buildExecutionSummary(event, context) }));
}

// Fields that must never appear anywhere on an ExecutionSummary. Used only by
// tests as a machine-checkable guardrail — the type system already prevents
// this in normal code, but this keeps the contract explicit and testable.
export const BANNED_SUMMARY_FIELDS = [
  "prompt",
  "reasoning",
  "systemPrompt",
  "system_prompt",
  "apiKey",
  "api_key",
  "secret",
  "stackTrace",
  "stack_trace",
  "errorMessage",
  "error_message",
  "cost",
  "margin",
  "rawOutput",
  "raw_output",
] as const;
