/**
 * File redirect policy.
 *
 * Download tokens may contain either an internal relative path or a URL
 * generated by a trusted storage/app origin. This policy deliberately uses
 * exact origins; hostname suffix/substring checks are not safe here.
 */

import type { Response } from "express";

const ALLOWED_PROTOCOLS = new Set(["http:", "https:"]);
const INTERNAL_BASE = "http://internal-file-target.invalid";

export type TrustedFileRedirectTarget = string & {
  readonly __trustedFileRedirectTarget: unique symbol;
};

type RedirectValidation =
  | { valid: true; target: TrustedFileRedirectTarget }
  | { valid: false; reason: string };

function configuredOrigins(): Set<string> {
  const values = [
    process.env["PUBLIC_APP_URL"],
    process.env["SUPABASE_URL"],
    process.env["SUPABASE_URL_DEV"],
    process.env["SUPABASE_URL_PROD"],
    process.env["VITE_SUPABASE_URL"],
    process.env["VITE_SUPABASE_URL_DEV"],
    ...(process.env["ALLOWED_ORIGINS"] ?? "").split(","),
  ].filter((value): value is string => Boolean(value?.trim()));

  // Local development needs to be able to use a local storage proxy/app
  // without making production permissive.
  if (process.env["NODE_ENV"] !== "production") {
    const port = process.env["PORT"] ?? "8080";
    values.push(`http://localhost:${port}`, `http://127.0.0.1:${port}`);
  }

  if (process.env["REPLIT_DEV_DOMAIN"]) {
    values.push(`https://${process.env["REPLIT_DEV_DOMAIN"]}`);
  }

  const origins = new Set<string>();
  for (const value of values) {
    try {
      const parsed = new URL(value.trim());
      if (ALLOWED_PROTOCOLS.has(parsed.protocol)) {
        origins.add(parsed.origin);
      }
    } catch {
      // Invalid configuration cannot become a trusted origin.
    }
  }
  return origins;
}

function decodeForValidation(value: string): string | null {
  let decoded = value;
  // Decode more than once so encoded protocol-relative and backslash variants
  // cannot pass validation and be interpreted differently by a user agent.
  for (let i = 0; i < 3; i += 1) {
    try {
      const next = decodeURIComponent(decoded);
      if (next === decoded) return decoded;
      decoded = next;
    } catch {
      return null;
    }
  }
  return decoded;
}

/**
 * Validate a redirect target.
 *
 * Safe targets:
 * - absolute http(s) URLs whose exact origin is configured/trusted;
 * - root-relative internal paths.
 *
 * Protocol-relative URLs, malformed URLs, unsupported schemes, backslashes,
 * encoded bypasses, and unconfigured external origins are rejected.
 */
export function validateFileRedirectTarget(rawTarget: string): RedirectValidation {
  if (typeof rawTarget !== "string" || rawTarget.trim().length === 0) {
    return { valid: false, reason: "Redirect target is required" };
  }

  const target = rawTarget.trim();
  const decoded = decodeForValidation(target);
  if (decoded === null) {
    return { valid: false, reason: "Redirect target contains invalid encoding" };
  }

  if (
    decoded.startsWith("//") ||
    decoded.startsWith("\\") ||
    decoded.includes("\\") ||
    /^[a-z][a-z\d+.-]*:/i.test(decoded) && !/^[a-z][a-z\d+.-]*:\/\//i.test(decoded)
  ) {
    return { valid: false, reason: "Protocol-relative or unsupported redirect target" };
  }

  // Root-relative paths are internal by definition. Reject encoded forms of
  // protocol-relative paths before URL() has a chance to normalise them.
  if (decoded.startsWith("/")) {
    try {
      const parsed = new URL(decoded, INTERNAL_BASE);
      if (parsed.origin !== INTERNAL_BASE) {
        return { valid: false, reason: "Redirect target is not internal" };
      }
    } catch {
      return { valid: false, reason: "Malformed internal redirect target" };
    }
    return { valid: true, target: target as TrustedFileRedirectTarget };
  }

  let parsed: URL;
  try {
    parsed = new URL(target);
  } catch {
    return { valid: false, reason: "Malformed redirect target" };
  }

  if (!ALLOWED_PROTOCOLS.has(parsed.protocol)) {
    return { valid: false, reason: `Protocol '${parsed.protocol}' is not allowed` };
  }
  if (parsed.username || parsed.password) {
    return { valid: false, reason: "Redirect target must not contain credentials" };
  }
  if (!configuredOrigins().has(parsed.origin)) {
    return { valid: false, reason: "Redirect target origin is not trusted" };
  }

  return { valid: true, target: target as TrustedFileRedirectTarget };
}

/**
 * Emit the redirect only for a target created by validateFileRedirectTarget.
 * Keeping the response sink here prevents route handlers from writing raw
 * request/token data into a Location header.
 */
export function sendTrustedFileRedirect(
  response: Response,
  target: TrustedFileRedirectTarget,
): void {
  response.setHeader("Location", target);
  response.status(302).end();
}