/**
 * Creates the 4 tables that failed in the main migration due to missing sequences.
 * Uses GENERATED BY DEFAULT AS IDENTITY instead of nextval() sequences.
 */
import pgModule from "/home/runner/workspace/node_modules/.pnpm/pg@8.22.0/node_modules/pg/lib/index.js";
// @ts-ignore
const Pool = (pgModule as any).Pool;

const PROD_URL =
  process.env.SUPABASE_PROD_DATABASE_URL ||
  process.env.SUPABASE_DATABASE_URL;

if (!PROD_URL) throw new Error("No prod DB URL found");

const prodPool = new Pool({
  connectionString: PROD_URL,
  ssl: { rejectUnauthorized: false },
});

const DDL_STATEMENTS = `

-- design_templates
CREATE TABLE IF NOT EXISTS ai_platform."design_templates" (
  "id" int8 GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" text,
  "category" varchar(100),
  "tags" text[],
  "thumbnail_url" text,
  "is_public" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "created_by" varchar(255),
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  CONSTRAINT "design_templates_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS idx_design_templates_tenant_status
  ON ai_platform."design_templates" ("tenant_id", "is_active");

-- design_template_versions
CREATE TABLE IF NOT EXISTS ai_platform."design_template_versions" (
  "id" int8 GENERATED BY DEFAULT AS IDENTITY,
  "template_id" int8 NOT NULL,
  "version" int4 DEFAULT 1,
  "canvas_data" jsonb,
  "thumbnail_url" text,
  "created_by" varchar(255),
  "created_at" timestamptz DEFAULT now(),
  CONSTRAINT "design_template_versions_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS idx_design_template_versions_template_id
  ON ai_platform."design_template_versions" ("template_id");

-- design_render_batches
CREATE TABLE IF NOT EXISTS ai_platform."design_render_batches" (
  "id" int8 GENERATED BY DEFAULT AS IDENTITY,
  "tenant_id" varchar(255) NOT NULL,
  "project_id" int8,
  "status" varchar(50) DEFAULT 'pending',
  "total_items" int4 DEFAULT 0,
  "completed_items" int4 DEFAULT 0,
  "failed_items" int4 DEFAULT 0,
  "created_by" varchar(255),
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  CONSTRAINT "design_render_batches_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS idx_design_render_batches_tenant
  ON ai_platform."design_render_batches" ("tenant_id");

-- design_render_items
CREATE TABLE IF NOT EXISTS ai_platform."design_render_items" (
  "id" int8 GENERATED BY DEFAULT AS IDENTITY,
  "batch_id" int8 NOT NULL,
  "input_hash" varchar(64),
  "canvas_data" jsonb,
  "output_url" text,
  "status" varchar(50) DEFAULT 'pending',
  "error_message" text,
  "render_time_ms" int4,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  CONSTRAINT "design_render_items_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS idx_design_render_items_batch_status
  ON ai_platform."design_render_items" ("batch_id", "status");

CREATE INDEX IF NOT EXISTS idx_design_render_items_input_hash
  ON ai_platform."design_render_items" ("input_hash");

`;

async function main() {
  console.log("🔍 Connecting to prod database...");
  const client = await prodPool.connect();

  try {
    // Split on semicolons, filter empty, run each statement
    // Strip comment lines, then split on semicolons
    const stripped = DDL_STATEMENTS
      .split("\n")
      .filter((line: string) => !line.trim().startsWith("--"))
      .join("\n");
    const statements = stripped
      .split(";")
      .map((s: string) => s.trim())
      .filter((s: string) => s.length > 0);

    for (const stmt of statements) {
      const label = stmt.substring(0, 80).replace(/\n/g, " ") + "...";
      try {
        await client.query(stmt);
        console.log("✅ " + label);
      } catch (err: any) {
        if (err.message.includes("already exists")) {
          console.log("⏭️  Already exists, skipping");
        } else {
          console.error("❌ " + label);
          console.error("   Error: " + err.message);
        }
      }
    }

    // Verify all 6 tables now exist
    const res = await client.query(
      `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'ai_platform'
         AND table_name IN (
           'ai_design_projects','ai_design_versions',
           'design_render_batches','design_render_items',
           'design_template_versions','design_templates'
         )
       ORDER BY table_name`
    );
    console.log("\n📊 Design Studio tables in prod:");
    for (const row of res.rows as any[]) {
      console.log("  ✅ " + row.table_name);
    }

    if (res.rows.length === 6) {
      console.log("\n🎉 All 6 design studio tables are now in prod!");
    } else {
      console.log(`\n⚠️  Only ${res.rows.length}/6 tables found.`);
    }
  } finally {
    client.release();
    await prodPool.end();
  }
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
