/**
 * Creates / repairs the 4 Design Template Engine tables in production.
 *
 * Originally written when the main migration failed due to missing sequences.
 * Updated (Team 22 idempotency fix) to:
 *   1. Use the CORRECT schema matching lib/db/src/schema/design-template-engine.ts
 *   2. Add ALTER TABLE ADD COLUMN IF NOT EXISTS guards so tables that exist
 *      with the OLD schema (from the original script run) get the missing
 *      columns without data loss.
 *   3. Be fully idempotent — safe to re-run at any time.
 *
 * Usage:
 *   NODE_ENV=production npx tsx src/scripts/fixMissingTables.ts
 */
import pgModule from "/home/runner/workspace/node_modules/.pnpm/pg@8.22.0/node_modules/pg/lib/index.js";
// @ts-ignore
const Pool = (pgModule as any).Pool;

const PROD_URL =
  process.env.SUPABASE_PROD_DATABASE_URL ||
  process.env.SUPABASE_DATABASE_URL;

if (!PROD_URL) throw new Error("No prod DB URL found (SUPABASE_PROD_DATABASE_URL or SUPABASE_DATABASE_URL)");

const prodPool = new Pool({
  connectionString: PROD_URL,
  ssl: { rejectUnauthorized: false },
});

// ── Phase 1: CREATE TABLE IF NOT EXISTS with the CORRECT schema ───────────────
// These run silently when the table already exists.

const CREATE_STATEMENTS = `

SET search_path TO ai_platform, public;

-- ── design_templates ─────────────────────────────────────────────────────────
-- Correct schema per lib/db/src/schema/design-template-engine.ts
CREATE TABLE IF NOT EXISTS ai_platform.design_templates (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id               TEXT        NOT NULL DEFAULT 'default',
  name                    TEXT        NOT NULL,
  slug                    TEXT        NOT NULL,
  description             TEXT,
  category                TEXT,
  status                  TEXT        NOT NULL DEFAULT 'draft',
  active_version_id       BIGINT,
  thumbnail_url           TEXT,
  thumbnail_storage_path  TEXT,
  created_by              TEXT        NOT NULL DEFAULT 'system',
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at              TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_design_templates_tenant_status
  ON ai_platform.design_templates (tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_design_templates_slug
  ON ai_platform.design_templates (slug);

-- ── design_template_versions ──────────────────────────────────────────────────
-- Correct schema per lib/db/src/schema/design-template-engine.ts
-- NOTE: original script used wrong column names (version, canvas_data).
--       Correct names are version_number and template_json.
CREATE TABLE IF NOT EXISTS ai_platform.design_template_versions (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id       TEXT        NOT NULL DEFAULT 'default',
  template_id     BIGINT      NOT NULL,
  version_number  INTEGER     NOT NULL,
  schema_version  TEXT        NOT NULL DEFAULT '1.0',
  template_json   JSONB       NOT NULL DEFAULT '{}',
  changelog       TEXT,
  created_by      TEXT        NOT NULL DEFAULT 'system',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_design_template_versions_template_id
  ON ai_platform.design_template_versions (template_id);

CREATE INDEX IF NOT EXISTS idx_design_template_versions_published
  ON ai_platform.design_template_versions (template_id, published_at)
  WHERE published_at IS NOT NULL;

-- ── design_render_batches ─────────────────────────────────────────────────────
-- Correct schema per lib/db/src/schema/design-template-engine.ts
CREATE TABLE IF NOT EXISTS ai_platform.design_render_batches (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id           TEXT        NOT NULL DEFAULT 'default',
  template_id         BIGINT      NOT NULL,
  template_version_id BIGINT      NOT NULL,
  name                TEXT        NOT NULL,
  status              TEXT        NOT NULL DEFAULT 'draft',
  total_items         INTEGER     NOT NULL DEFAULT 0,
  queued_items        INTEGER     NOT NULL DEFAULT 0,
  processing_items    INTEGER     NOT NULL DEFAULT 0,
  completed_items     INTEGER     NOT NULL DEFAULT 0,
  failed_items        INTEGER     NOT NULL DEFAULT 0,
  cancelled_items     INTEGER     NOT NULL DEFAULT 0,
  requested_format    TEXT        NOT NULL DEFAULT 'png',
  requested_width     INTEGER,
  requested_height    INTEGER,
  requested_by        TEXT        NOT NULL DEFAULT 'system',
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at          TIMESTAMPTZ,
  completed_at        TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_design_render_batches_tenant
  ON ai_platform.design_render_batches (tenant_id);

CREATE INDEX IF NOT EXISTS idx_design_render_batches_status
  ON ai_platform.design_render_batches (status)
  WHERE status NOT IN ('completed', 'partially_failed', 'failed', 'cancelled');

-- ── design_render_items ───────────────────────────────────────────────────────
-- Correct schema per lib/db/src/schema/design-template-engine.ts +
-- Phase 3A dispatch columns (phase3a-design-batch.sql)
CREATE TABLE IF NOT EXISTS ai_platform.design_render_items (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id               TEXT        NOT NULL DEFAULT 'default',
  batch_id                BIGINT      NOT NULL,
  template_id             BIGINT      NOT NULL,
  template_version_id     BIGINT      NOT NULL,
  row_index               INTEGER     NOT NULL,
  input_data              JSONB       NOT NULL DEFAULT '{}',
  input_hash              TEXT        NOT NULL,
  status                  TEXT        NOT NULL DEFAULT 'queued',
  attempt_count           INTEGER     NOT NULL DEFAULT 0,
  -- Phase 3A: dispatch marker columns
  dispatch_status         TEXT        NOT NULL DEFAULT 'pending',
  dispatch_attempt_count  INTEGER     NOT NULL DEFAULT 0,
  last_dispatched_at      TIMESTAMPTZ,
  queue_job_id            TEXT,
  next_retry_at           TIMESTAMPTZ,
  worker_id               TEXT,
  lease_expires_at        TIMESTAMPTZ,
  heartbeat_at            TIMESTAMPTZ,
  -- Output fields
  output_storage_path     TEXT,
  output_url              TEXT,
  output_asset_id         TEXT,
  output_width            INTEGER,
  output_height           INTEGER,
  output_format           TEXT,
  output_file_size_bytes  INTEGER,
  render_duration_ms      INTEGER,
  error_code              TEXT,
  error_message           TEXT,
  render_warnings         JSONB,
  queued_at               TIMESTAMPTZ,
  started_at              TIMESTAMPTZ,
  completed_at            TIMESTAMPTZ,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (batch_id, row_index)
);

CREATE INDEX IF NOT EXISTS idx_design_render_items_batch_status
  ON ai_platform.design_render_items (batch_id, status);

CREATE INDEX IF NOT EXISTS idx_design_render_items_input_hash
  ON ai_platform.design_render_items (input_hash);

CREATE INDEX IF NOT EXISTS idx_dri_dispatch_status
  ON ai_platform.design_render_items (batch_id, dispatch_status);

CREATE INDEX IF NOT EXISTS idx_dri_lease_recovery
  ON ai_platform.design_render_items (status, lease_expires_at)
  WHERE status = 'processing';

`;

// ── Phase 2: ALTER TABLE ADD COLUMN IF NOT EXISTS ─────────────────────────────
// Repairs tables that were created by the OLD script (wrong schema).
// Each statement is idempotent (ADD COLUMN IF NOT EXISTS).

const ALTER_STATEMENTS = `

SET search_path TO ai_platform, public;

-- design_templates: columns missing from old schema
ALTER TABLE ai_platform.design_templates ADD COLUMN IF NOT EXISTS slug                   TEXT        NOT NULL DEFAULT '';
ALTER TABLE ai_platform.design_templates ADD COLUMN IF NOT EXISTS status                 TEXT        NOT NULL DEFAULT 'draft';
ALTER TABLE ai_platform.design_templates ADD COLUMN IF NOT EXISTS active_version_id      BIGINT;
ALTER TABLE ai_platform.design_templates ADD COLUMN IF NOT EXISTS thumbnail_storage_path TEXT;
ALTER TABLE ai_platform.design_templates ADD COLUMN IF NOT EXISTS deleted_at             TIMESTAMPTZ;

-- design_template_versions: columns missing or renamed from old schema
-- NOTE: old schema had "version" (int) and "canvas_data" (jsonb).
--       Correct names are "version_number" and "template_json".
--       We ADD the correct columns; old wrong-named columns remain harmless.
ALTER TABLE ai_platform.design_template_versions ADD COLUMN IF NOT EXISTS tenant_id       TEXT        NOT NULL DEFAULT 'default';
ALTER TABLE ai_platform.design_template_versions ADD COLUMN IF NOT EXISTS version_number  INTEGER     NOT NULL DEFAULT 1;
ALTER TABLE ai_platform.design_template_versions ADD COLUMN IF NOT EXISTS schema_version  TEXT        NOT NULL DEFAULT '1.0';
ALTER TABLE ai_platform.design_template_versions ADD COLUMN IF NOT EXISTS template_json   JSONB       NOT NULL DEFAULT '{}';
ALTER TABLE ai_platform.design_template_versions ADD COLUMN IF NOT EXISTS changelog       TEXT;
ALTER TABLE ai_platform.design_template_versions ADD COLUMN IF NOT EXISTS published_at    TIMESTAMPTZ;

-- design_render_batches: columns missing from old schema
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS template_id         BIGINT      NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS template_version_id BIGINT      NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS name                TEXT        NOT NULL DEFAULT '';
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS queued_items        INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS processing_items    INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS cancelled_items     INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS requested_format    TEXT        NOT NULL DEFAULT 'png';
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS requested_width     INTEGER;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS requested_height    INTEGER;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS requested_by        TEXT        NOT NULL DEFAULT 'system';
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS started_at          TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_batches ADD COLUMN IF NOT EXISTS completed_at        TIMESTAMPTZ;

-- design_render_items: columns missing from old schema
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS tenant_id               TEXT        NOT NULL DEFAULT 'default';
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS template_id             BIGINT      NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS template_version_id     BIGINT      NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS row_index               INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS input_data              JSONB       NOT NULL DEFAULT '{}';
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS attempt_count           INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS dispatch_status         TEXT        NOT NULL DEFAULT 'pending';
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS dispatch_attempt_count  INTEGER     NOT NULL DEFAULT 0;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS last_dispatched_at      TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS queue_job_id            TEXT;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS next_retry_at           TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS worker_id               TEXT;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS lease_expires_at        TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS heartbeat_at            TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS output_storage_path     TEXT;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS output_asset_id         TEXT;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS output_width            INTEGER;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS output_height           INTEGER;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS output_format           TEXT;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS output_file_size_bytes  INTEGER;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS render_duration_ms      INTEGER;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS error_code              TEXT;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS render_warnings         JSONB;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS queued_at               TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS started_at              TIMESTAMPTZ;
ALTER TABLE ai_platform.design_render_items ADD COLUMN IF NOT EXISTS completed_at            TIMESTAMPTZ;

-- Indexes added by phase3a-design-batch.sql (idempotent here too)
CREATE INDEX IF NOT EXISTS idx_drb_active_tenant
  ON ai_platform.design_render_batches (tenant_id, status)
  WHERE status NOT IN ('completed', 'partially_failed', 'failed', 'cancelled');

`;

function runPhase(label: string, sql: string, client: any): Promise<{ ok: number; skipped: number; failed: number }> {
  const stripped = sql
    .split("\n")
    .filter((line: string) => !line.trim().startsWith("--") && line.trim() !== "")
    .join("\n");

  const statements = stripped
    .split(";")
    .map((s: string) => s.trim())
    .filter((s: string) => s.length > 0 && !s.startsWith("--"));

  let ok = 0, skipped = 0, failed = 0;

  return (async () => {
    for (const stmt of statements) {
      const preview = stmt.substring(0, 100).replace(/\n/g, " ").replace(/\s+/g, " ");
      try {
        await client.query(stmt);
        ok++;
        console.log(`  ✅ ${preview}`);
      } catch (err: any) {
        if (
          err.message?.includes("already exists") ||
          err.message?.includes("duplicate column")
        ) {
          skipped++;
          console.log(`  ⏭️  Already exists — ${preview}`);
        } else {
          failed++;
          console.error(`  ❌ ${preview}`);
          console.error(`     → ${err.message}`);
        }
      }
    }
    console.log(`\n${label}: ✅ ${ok} ok  ⏭️  ${skipped} skipped  ❌ ${failed} failed\n`);
    return { ok, skipped, failed };
  })();
}

async function main() {
  console.log("🔧 Design Template Engine — Table repair + schema correction");
  console.log("   Connecting to:", PROD_URL!.replace(/:[^:@]+@/, ":***@"));

  const client = await prodPool.connect();
  try {
    console.log("\n── Phase 1: CREATE TABLE IF NOT EXISTS (correct schema) ──");
    const r1 = await runPhase("Phase 1", CREATE_STATEMENTS, client);

    console.log("\n── Phase 2: ALTER TABLE ADD COLUMN IF NOT EXISTS (old-schema repair) ──");
    const r2 = await runPhase("Phase 2", ALTER_STATEMENTS, client);

    // ── Verification ──────────────────────────────────────────────────────────
    const res = await client.query<{ table_name: string }>(
      `SELECT table_name
         FROM information_schema.tables
        WHERE table_schema = 'ai_platform'
          AND table_name IN (
            'design_templates', 'design_template_versions',
            'design_render_batches', 'design_render_items'
          )
        ORDER BY table_name`
    );
    console.log("\n📊 Design Template Engine tables in DB:");
    for (const row of res.rows) console.log("  ✅ " + row.table_name);

    const totalFailed = r1.failed + r2.failed;
    if (res.rows.length === 4 && totalFailed === 0) {
      console.log("\n🎉 All 4 tables present and schema-correct. Ready for production.");
    } else if (res.rows.length < 4) {
      console.warn(`\n⚠️  Only ${res.rows.length}/4 tables found — check errors above.`);
      process.exit(1);
    } else if (totalFailed > 0) {
      console.warn(`\n⚠️  ${totalFailed} statement(s) failed — review errors above.`);
      process.exit(1);
    }
  } finally {
    client.release();
    await prodPool.end();
  }
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
