/**
 * Team 04 — Adaptive Question Engine: AI Clarification Adapter Interface
 *
 * Defines the contract for an OPTIONAL AI-assisted clarification layer.
 * The core question engine is fully deterministic without an adapter.
 * AI clarification is layered on top via dependency injection.
 *
 * Rules:
 * - Core engine NEVER imports AI providers directly.
 * - Adapter receives only the minimum data needed (field allowlist).
 * - Usage is always logged via the returned metadata.
 * - Hidden chain-of-thought is never stored.
 */

import type { BriefData } from "@/pages/brief";
import type { PlannedBriefQuestion } from "./types";

// ── Clarification request/response ─────────────────────────────────────────────

/**
 * A clarification question generated by the AI adapter.
 * The UI surfaces this BEFORE the standard question; user answers
 * are fed back to the session as structured input.
 */
export interface ClarificationQuestion {
  /** Stable ID — adapter-generated, scoped to the session. */
  id: string;
  /** The BriefData field this clarification is for. */
  targetField: keyof BriefData;
  /** Human-facing clarification prompt. */
  prompt: string;
  /** Short reason shown to the user explaining why clarification is needed. */
  reason: string;
  /** Optional suggested quick-reply options derived from schema. */
  suggestions?: string[];
}

/** Input sent to the AI adapter — only the allowed fields, never the full brief. */
export interface ClarificationInput {
  /** The question the user is currently answering. */
  question: PlannedBriefQuestion;
  /** Raw answer text as the user typed or selected it. */
  rawAnswer: string;
  /**
   * Allowlisted brief context: only fields relevant to understanding the answer.
   * The session hook builds this subset; the adapter never sees the full brief.
   */
  briefContext: Partial<Record<keyof BriefData, string>>;
  /** Service domain context (e.g. "fashion_design") for wording guidance. */
  serviceType: string;
}

/** Structured result from the AI adapter. */
export interface ClarificationResult {
  /**
   * True if the AI considers the answer clear and complete.
   * False means a clarification question should be shown.
   */
  isClear: boolean;
  /** Clarification question to show when isClear = false. */
  clarificationQuestion?: ClarificationQuestion;
  /** Confidence score 0–1 the adapter assigns to the parsed answer. */
  confidence: number;
  /** Structured extracted value if the adapter successfully parsed the answer. */
  parsedValue?: string;
  /** Audit metadata — always included, never hidden chain-of-thought. */
  auditMeta: ClarificationAuditMeta;
}

export interface ClarificationAuditMeta {
  /** ISO timestamp when the adapter was called. */
  calledAt: string;
  /** Which model/provider version was used (generic, no credentials). */
  modelHint: string;
  /** Whether AI assistance was used (always true for non-null results). */
  aiAssisted: true;
  /** Fields included in the allowlisted context. */
  contextFields: string[];
}

// ── Adapter interface ──────────────────────────────────────────────────────────

/**
 * The injectable AI clarification adapter.
 * Implement this interface to add AI-assisted clarification.
 * Pass null/undefined to run in pure deterministic mode.
 */
export interface AiClarificationAdapter {
  /**
   * Evaluates the raw answer and returns either a "clear" result or a
   * clarification question for the user.
   *
   * Must never throw — return a fallback result on failure.
   * Must never store hidden chain-of-thought.
   * Must use only the provided briefContext, not fetch additional data.
   */
  requestClarification(input: ClarificationInput): Promise<ClarificationResult>;

  /**
   * True if the adapter is currently available.
   * The engine calls this before requesting clarification; if false,
   * the session continues in deterministic mode without interruption.
   */
  isAvailable(): boolean;
}

// ── Null adapter ───────────────────────────────────────────────────────────────

/**
 * Null implementation — always returns "clear" with high confidence.
 * Use as the default when no AI adapter is configured.
 */
export const NULL_CLARIFICATION_ADAPTER: AiClarificationAdapter = {
  isAvailable: () => false,
  requestClarification: async (input) => ({
    isClear: true,
    confidence: 1.0,
    auditMeta: {
      calledAt: new Date().toISOString(),
      modelHint: "null-adapter",
      aiAssisted: true,
      contextFields: [],
    },
  }),
} satisfies AiClarificationAdapter;

// ── Context builder ────────────────────────────────────────────────────────────

/** Fields that are safe to share with the AI adapter for context. */
const CONTEXT_ALLOWLIST: ReadonlyArray<keyof BriefData> = [
  "companyIndustry",
  "primaryGoal",
  "stylePreference",
  "outputFormats",
] as const;

/**
 * Builds the allowlisted brief context sent to the adapter.
 * Never includes free-text fields that may contain PII.
 */
export function buildClarificationContext(
  brief: Partial<BriefData>,
): Partial<Record<keyof BriefData, string>> {
  const ctx: Partial<Record<keyof BriefData, string>> = {};
  for (const field of CONTEXT_ALLOWLIST) {
    const val = brief[field];
    if (val && typeof val === "string" && val.trim()) {
      ctx[field] = val.trim();
    }
  }
  return ctx;
}
