/**
 * Industry profile registry.
 *
 * Every INDUSTRY_OPTIONS value (src/config/brief-options.ts) gets a profile:
 * a category-group default (reusable base, keyed by the same `group` string
 * already used in INDUSTRY_OPTIONS) merged with an optional industry-specific
 * override for finer-grained recommendations. This guarantees every real
 * dropdown value resolves to a profile without duplicating the industry list,
 * and keeps the override table small (only industries that meaningfully
 * differ from their group default need an entry).
 *
 * "other" is intentionally excluded — free-text / unmatched industries are
 * handled by industry-fallback.ts.
 */

import { INDUSTRY_OPTIONS } from "@/config/brief-options";
import type { IndustryProfile } from "./types";

type ProfileSeed = Omit<IndustryProfile, "key" | "label" | "categoryGroup">;

// ── Category-group defaults (reused by every industry in that group) ───────

const GROUP_DEFAULTS: Record<string, ProfileSeed> = {
  "Perdagangan": {
    styles: ["modern", "bold", "clean"],
    colors: ["blue", "orange", "black"],
    audiences: ["b2c", "general", "retail_cust"],
    personalities: ["dipercaya", "praktis", "responsif"],
    deliverables: ["Katalog produk", "Konten promosi harian", "Banner diskon/promo"],
    toneOfVoice: ["Persuasif", "Ramah", "To the point"],
    photographyDirection: ["Foto produk terang & detail", "Konteks penggunaan produk"],
    visualDirection: ["Grid produk yang rapi", "Aksen warna untuk harga/promo"],
    contentDirection: ["Highlight promo & bestseller", "Call-to-action jelas di setiap post"],
    avoid: ["Terlalu banyak teks kecil", "Layout yang membingungkan"],
    notes: "Perdagangan/retail — fokus konversi dan kejelasan penawaran.",
  },
  "Teknologi": {
    styles: ["modern", "minimalis", "futuristic"],
    colors: ["blue", "purple", "black"],
    audiences: ["b2b", "startup", "investor", "professional"],
    personalities: ["inovatif", "kredibel", "visioner"],
    deliverables: ["Pitch deck / one-pager", "Product screenshot mockup", "Diagram arsitektur/how-it-works"],
    toneOfVoice: ["Jelas & confident", "Data-driven", "Tidak berlebihan (no hype kosong)"],
    photographyDirection: ["Product UI mockup di device", "Tim/kantor yang clean & terang"],
    visualDirection: ["Banyak whitespace", "Gradient halus sebagai aksen", "Ikonografi custom, bukan generik"],
    contentDirection: ["Fokus pada masalah yang diselesaikan", "Bukti/traksi (angka, logo klien)"],
    avoid: ["Clipart teknologi generik", "Warna neon berlebihan"],
    notes: "Teknologi/software — kredibilitas dan kejelasan proposisi nilai.",
  },
  "Keuangan": {
    styles: ["corporate", "elegant", "clean"],
    colors: ["blue", "black", "gold"],
    audiences: ["b2c", "b2b", "professional", "corporate"],
    personalities: ["terpercaya", "aman", "profesional"],
    deliverables: ["Company profile / brand guideline", "Infografis edukasi produk finansial"],
    toneOfVoice: ["Formal namun mudah dipahami", "Transparan", "Tidak membuat klaim berlebihan"],
    photographyDirection: ["Foto profesional (bukan stok generik)", "Simbol keamanan & kepercayaan"],
    visualDirection: ["Grid simetris, rapi", "Ikon yang jelas untuk fitur/produk"],
    contentDirection: ["Kejelasan syarat & ketentuan tersirat", "Testimoni/kepercayaan sebagai pilar konten"],
    avoid: ["Warna terlalu playful", "Klaim tanpa disclaimer"],
    notes: "Keuangan — kepatuhan visual terhadap kesan aman & terpercaya sangat penting.",
  },
  "Kesehatan": {
    styles: ["clean", "minimalis", "corporate"],
    colors: ["blue", "green", "white"],
    audiences: ["general", "b2c", "family"],
    personalities: ["caring", "terpercaya", "higienis"],
    deliverables: ["Company profile fasilitas", "Konten edukasi kesehatan", "Foto fasilitas & tenaga medis"],
    toneOfVoice: ["Menenangkan", "Empatik", "Berbasis fakta, bukan menakut-nakuti"],
    photographyDirection: ["Cahaya terang & bersih", "Interaksi tenaga medis-pasien yang natural"],
    visualDirection: ["Banyak whitespace, kesan steril/bersih", "Aksen hijau/biru untuk kesan sehat"],
    contentDirection: ["Edukasi lebih dulu, promosi belakangan", "Testimoni pasien (dengan izin) memperkuat trust"],
    avoid: ["Gambar medis yang menakutkan", "Klaim penyembuhan berlebihan"],
    notes: "Kesehatan — ketenangan dan kepercayaan lebih penting daripada gaya visual yang mencolok.",
  },
  "Pendidikan": {
    styles: ["modern", "playful", "clean"],
    colors: ["blue", "orange", "green"],
    audiences: ["student", "family", "general"],
    personalities: ["mendidik", "menginspirasi", "approachable"],
    deliverables: ["Brosur program/kurikulum", "Konten media sosial kampus/sekolah", "Foto aktivitas belajar"],
    toneOfVoice: ["Ramah dan memotivasi", "Jelas untuk orang tua & siswa"],
    photographyDirection: ["Aktivitas belajar yang autentik", "Ekspresi antusias siswa"],
    visualDirection: ["Warna cerah namun tetap rapi", "Ikon edukasi yang playful"],
    contentDirection: ["Highlight prestasi & fasilitas", "Testimoni siswa/orang tua"],
    avoid: ["Terlalu formal/kaku untuk target siswa muda"],
    notes: "Pendidikan — harus menyeimbangkan kredibilitas institusi dengan kehangatan.",
  },
  "Kuliner & F&B": {
    styles: ["natural", "playful", "modern"],
    colors: ["orange", "brown", "green"],
    audiences: ["general", "youth", "family", "local"],
    personalities: ["hangat", "menggugah selera", "autentik"],
    deliverables: ["Foto menu/produk", "Konten media sosial harian", "Menu board / katalog"],
    toneOfVoice: ["Hangat & menggugah selera", "Santai, tidak kaku"],
    photographyDirection: ["Food photography close-up dengan cahaya natural", "Suasana tempat/produk yang menggugah selera"],
    visualDirection: ["Warna hangat (earth tone/oranye)", "Tekstur natural (kayu, kertas kraft)"],
    contentDirection: ["Cerita di balik produk (proses, bahan)", "User-generated content dari pelanggan"],
    avoid: ["Foto makanan gelap/kurang cahaya", "Warna dingin yang menekan nafsu makan"],
    notes: "F&B — food photography berkualitas adalah prioritas nomor satu.",
  },
  "Perhotelan & Pariwisata": {
    styles: ["elegant", "premium", "natural"],
    colors: ["blue", "gold", "earth"],
    audiences: ["premium", "family", "international"],
    personalities: ["hospitable", "premium", "menenangkan"],
    deliverables: ["Foto properti/destinasi", "Company profile / brosur paket", "Konten media sosial destinasi"],
    toneOfVoice: ["Mengundang & deskriptif", "Elegan, tidak terlalu menjual"],
    photographyDirection: ["Wide shot suasana & golden hour", "Detail fasilitas premium"],
    visualDirection: ["Palet warna tenang & natural", "Tipografi elegan"],
    contentDirection: ["Cerita pengalaman (bukan hanya fasilitas)", "Highlight lokasi/keunikan destinasi"],
    avoid: ["Foto stok generik yang tidak menunjukkan lokasi asli"],
    notes: "Perhotelan/pariwisata — visual harus menjual pengalaman, bukan hanya fasilitas.",
  },
  "Logistik": {
    styles: ["corporate", "bold", "industrial"],
    colors: ["blue", "orange", "gray"],
    audiences: ["b2b", "corporate", "distributor", "international"],
    personalities: ["dapat diandalkan", "tepat waktu", "sigap"],
    deliverables: ["Company profile & kapabilitas layanan", "Infografis jalur/proses layanan", "Foto armada/gudang/fasilitas"],
    toneOfVoice: ["Tegas & meyakinkan", "Fokus pada keandalan dan skala operasi"],
    photographyDirection: ["Armada/fasilitas dalam skala nyata", "Aktivitas operasional (bongkar muat, gudang)"],
    visualDirection: ["Garis tegas & dinamis (arah pergerakan)", "Peta/rute sebagai elemen visual"],
    contentDirection: ["Cakupan wilayah & jaringan sebagai bukti skala", "Studi kasus pengiriman/klien"],
    avoid: ["Visual yang terasa kecil/tidak meyakinkan skala operasinya"],
    notes: "Logistik — kepercayaan berbasis skala, jaringan, dan ketepatan waktu.",
  },
  "Industri": {
    styles: ["industrial", "bold", "corporate"],
    colors: ["gray", "blue", "orange"],
    audiences: ["b2b", "corporate", "distributor"],
    personalities: ["kuat", "presisi", "berpengalaman"],
    deliverables: ["Company profile kapabilitas produksi", "Foto fasilitas/mesin produksi", "Katalog produk teknis"],
    toneOfVoice: ["Teknis namun tetap jelas", "Fokus pada kualitas & standar produksi"],
    photographyDirection: ["Fasilitas produksi dalam aksi", "Detail kualitas material/produk"],
    visualDirection: ["Palet warna solid & kuat", "Tekstur industrial (metal, beton)"],
    contentDirection: ["Sertifikasi/standar sebagai bukti kredibilitas", "Kapasitas produksi sebagai nilai jual"],
    avoid: ["Visual yang terlalu 'lembut' untuk industri berat"],
    notes: "Manufaktur/konstruksi — kredibilitas teknis dan skala produksi jadi fokus.",
  },
  "Properti": {
    styles: ["premium", "elegant", "modern"],
    colors: ["black", "gold", "earth"],
    audiences: ["premium", "family", "b2c", "investor"],
    personalities: ["premium", "terpercaya", "aspirational"],
    deliverables: ["Foto properti (interior/eksterior)", "Brosur/company profile proyek", "Floor plan visual"],
    toneOfVoice: ["Aspirational namun jujur/informatif", "Elegan"],
    photographyDirection: ["Wide-angle interior dengan cahaya natural", "Golden hour untuk eksterior"],
    visualDirection: ["Palet warna hangat/netral premium", "Tipografi elegan, banyak whitespace"],
    contentDirection: ["Highlight lokasi & lifestyle sekitar", "Detail spesifikasi teknis untuk calon pembeli"],
    avoid: ["Foto gelap/sempit yang membuat properti terlihat kecil"],
    notes: "Properti — visual harus menjual lifestyle dan kepercayaan investasi.",
  },
  "Jasa Profesional": {
    styles: ["corporate", "elegant", "clean"],
    colors: ["blue", "black", "gray"],
    audiences: ["b2b", "professional", "corporate"],
    personalities: ["kredibel", "profesional", "berpengalaman"],
    deliverables: ["Company profile / brand guideline", "Foto tim profesional", "Studi kasus/testimoni klien"],
    toneOfVoice: ["Formal namun personal", "Berbasis keahlian, tidak berlebihan"],
    photographyDirection: ["Portrait profesional tim", "Suasana kantor/konsultasi yang meyakinkan"],
    visualDirection: ["Rapi, simetris, minim dekorasi berlebihan"],
    contentDirection: ["Kredensial & jam terbang sebagai bukti kredibilitas", "Studi kasus nyata"],
    avoid: ["Visual yang terasa kasual untuk jasa formal"],
    notes: "Jasa profesional — kredibilitas personal/institusional adalah inti pesan.",
  },
  "Kreatif & Media": {
    styles: ["creative", "bold", "colorful"],
    colors: ["purple", "orange", "black"],
    audiences: ["b2b", "b2c", "youth", "professional"],
    personalities: ["ekspresif", "inovatif", "berani"],
    deliverables: ["Portfolio/showreel visual", "Konten media sosial", "Brand identity materials"],
    toneOfVoice: ["Ekspresif & personal", "Berani mengambil sudut pandang unik"],
    photographyDirection: ["Gaya editorial/artistik, bukan stok generik"],
    visualDirection: ["Eksperimen tipografi & layout", "Warna berani sebagai identitas"],
    contentDirection: ["Showcase karya sebagai bukti kapabilitas", "Proses kreatif sebagai cerita"],
    avoid: ["Template generik yang tidak mencerminkan keunikan kreatif"],
    notes: "Kreatif/agency/media — diferensiasi visual justru menjadi bukti kapabilitas.",
  },
  "Fashion & Kecantikan": {
    styles: ["elegant", "editorial", "premium"],
    colors: ["pastel", "black", "gold"],
    audiences: ["youth", "premium", "b2c", "general"],
    personalities: ["stylish", "aspirational", "percaya diri"],
    deliverables: ["Foto produk & lookbook", "Konten media sosial", "Katalog koleksi"],
    toneOfVoice: ["Aspirational & percaya diri", "Trendy tapi tetap on-brand"],
    photographyDirection: ["Editorial fashion photography", "Detail tekstur produk/material"],
    visualDirection: ["Palet warna sesuai identitas brand (bold/pastel)", "Tipografi fashion-forward"],
    contentDirection: ["Storytelling gaya hidup, bukan hanya produk", "Kolaborasi/UGC dari pelanggan"],
    avoid: ["Foto produk flat tanpa konteks gaya hidup"],
    notes: "Fashion & beauty — estetika editorial dan konsistensi visual sangat krusial.",
  },
  "Furnitur & Dekorasi": {
    styles: ["natural", "minimalis", "elegant"],
    colors: ["brown", "earth", "white"],
    audiences: ["b2c", "family", "premium"],
    personalities: ["hangat", "berkualitas", "timeless"],
    deliverables: ["Foto produk dalam konteks ruangan", "Katalog produk", "Konten media sosial"],
    toneOfVoice: ["Hangat & deskriptif material/kualitas"],
    photographyDirection: ["Product-in-context (ruangan nyata)", "Detail tekstur material"],
    visualDirection: ["Palet earth tone/netral", "Komposisi minim namun hangat"],
    contentDirection: ["Cerita material & craftsmanship", "Inspirasi penataan ruang"],
    avoid: ["Studio shot polos tanpa konteks ruangan"],
    notes: "Furnitur/dekorasi — konteks ruangan nyata memperkuat daya tarik produk.",
  },
  "Agribisnis": {
    styles: ["natural", "industrial", "clean"],
    colors: ["green", "brown", "earth"],
    audiences: ["b2b", "distributor", "international", "corporate"],
    personalities: ["autentik", "berkelanjutan", "dapat diandalkan"],
    deliverables: ["Company profile & kapabilitas ekspor/produksi", "Foto lahan/fasilitas produksi", "Katalog produk dengan spesifikasi"],
    toneOfVoice: ["Jujur & berbasis fakta produksi", "Menekankan kualitas & keberlanjutan"],
    photographyDirection: ["Lahan/kebun/fasilitas dalam cahaya natural", "Proses produksi/panen yang autentik"],
    visualDirection: ["Palet hijau/earth tone", "Tekstur natural (daun, tanah, kayu)"],
    contentDirection: ["Sertifikasi & standar ekspor sebagai bukti kredibilitas", "Traceability/asal produk"],
    avoid: ["Visual yang terlalu 'kota'/tidak merepresentasikan asal produk"],
    notes: "Agribisnis — keaslian dan kredibilitas produksi/ekspor jadi nilai jual utama.",
  },
  "Otomotif": {
    styles: ["bold", "modern", "industrial"],
    colors: ["black", "red", "gray"],
    audiences: ["b2c", "youth", "professional"],
    personalities: ["tangguh", "dinamis", "terpercaya"],
    deliverables: ["Foto produk/kendaraan", "Konten media sosial", "Katalog spesifikasi"],
    toneOfVoice: ["Percaya diri & energik", "Fokus performa dan keandalan"],
    photographyDirection: ["Angle dinamis kendaraan", "Detail fitur/interior"],
    visualDirection: ["Kontras tinggi, warna berani", "Garis dinamis (kesan gerak)"],
    contentDirection: ["Spesifikasi & performa sebagai konten utama", "Testimoni pengguna"],
    avoid: ["Visual statis/flat yang tidak menonjolkan performa"],
    notes: "Otomotif — dinamisme visual dan kepercayaan performa jadi fokus.",
  },
  "Kebugaran & Sport": {
    styles: ["bold", "modern", "playful"],
    colors: ["black", "orange", "green"],
    audiences: ["youth", "general", "b2c"],
    personalities: ["energik", "memotivasi", "aktif"],
    deliverables: ["Foto aktivitas/fasilitas", "Konten media sosial motivasional", "Program/paket promosi"],
    toneOfVoice: ["Energik & memotivasi", "Actionable (ajakan bertindak)"],
    photographyDirection: ["Aksi/gerakan dinamis", "Ekspresi semangat autentik"],
    visualDirection: ["Warna berani & kontras tinggi", "Tipografi bold"],
    contentDirection: ["Transformasi/hasil sebagai bukti", "Komunitas sebagai nilai jual"],
    avoid: ["Visual pasif/statis yang tidak menunjukkan energi"],
    notes: "Fitness/sport — energi dan motivasi harus terasa di setiap visual.",
  },
  "Event & Fotografi": {
    styles: ["elegant", "creative", "editorial"],
    colors: ["gold", "black", "pastel"],
    audiences: ["b2c", "premium", "family"],
    personalities: ["berkesan", "detail-oriented", "personal"],
    deliverables: ["Portfolio foto/video event", "Konten media sosial", "Paket/company profile layanan"],
    toneOfVoice: ["Hangat & personal", "Fokus pada momen dan emosi"],
    photographyDirection: ["Candid moment berkualitas tinggi", "Detail dekorasi/momen penting"],
    visualDirection: ["Palet elegan sesuai tema event", "Tipografi editorial"],
    contentDirection: ["Cerita momen (before-during-after)", "Testimoni klien"],
    avoid: ["Visual generik yang tidak menonjolkan momen personal"],
    notes: "Event/fotografi — kualitas momen personal adalah bukti kapabilitas utama.",
  },
  "Publik & Sosial": {
    styles: ["corporate", "clean", "classic"],
    colors: ["blue", "green", "white"],
    audiences: ["general", "government", "b2c"],
    personalities: ["terpercaya", "transparan", "melayani"],
    deliverables: ["Materi edukasi publik", "Infografis program/kebijakan", "Foto kegiatan/program"],
    toneOfVoice: ["Formal, jelas, dan netral", "Informatif, bukan menjual"],
    photographyDirection: ["Kegiatan/program yang autentik", "Interaksi dengan masyarakat"],
    visualDirection: ["Palet warna netral & resmi", "Ikon informatif yang jelas"],
    contentDirection: ["Transparansi program/data sebagai isi utama", "Dampak nyata ke masyarakat"],
    avoid: ["Gaya visual yang terlalu komersial/menjual untuk konteks publik"],
    notes: "Pemerintah/nonprofit — netralitas, transparansi, dan kredibilitas publik jadi acuan.",
  },
};

// ── Industry-specific overrides (only where they meaningfully diverge from
//    their group default) — includes the 4 fully worked examples from the
//    brief: coffee_shop, export_import, charcoal, ai. ─────────────────────────

const INDUSTRY_OVERRIDES: Partial<Record<string, Partial<ProfileSeed>>> = {
  coffee_shop: {
    styles: ["natural", "minimalis", "modern"],
    colors: ["brown", "green", "earth"],
    audiences: ["youth", "local", "general"],
    personalities: ["hangat", "autentik", "santai"],
    deliverables: ["Foto menu & interior kafe", "Konten media sosial harian (Instagram/TikTok)", "Menu board digital"],
    toneOfVoice: ["Santai & hangat", "Personal, seperti ngobrol dengan teman"],
    photographyDirection: ["Foto kopi & suasana kafe dengan cahaya natural", "Detail latte art / proses seduh"],
    visualDirection: ["Tekstur kayu & earth tone", "Nuansa kasual namun estetik (aesthetic cafe vibe)"],
    contentDirection: ["Cerita biji kopi/origin", "Konten UGC pelanggan yang nongkrong"],
    avoid: ["Kesan terlalu korporat/formal", "Warna dingin yang mengurangi kehangatan"],
    notes: "Coffee Shop: kehangatan personal + estetika 'aesthetic cafe' untuk menarik target anak muda lokal.",
  },
  export_import: {
    styles: ["corporate", "bold", "clean"],
    colors: ["blue", "gray", "gold"],
    audiences: ["b2b", "international", "distributor", "corporate"],
    personalities: ["dapat diandalkan", "profesional", "berskala global"],
    deliverables: ["Company profile bilingual (ID/EN)", "Katalog produk dengan spesifikasi ekspor", "Foto fasilitas/gudang & proses logistik"],
    toneOfVoice: ["Profesional & formal, sesuai standar bisnis internasional", "Jelas soal kapabilitas & sertifikasi"],
    photographyDirection: ["Fasilitas gudang/pelabuhan dalam skala nyata", "Dokumentasi proses ekspor (container, loading)"],
    visualDirection: ["Palet warna korporat & solid", "Elemen peta/rute internasional sebagai aksen"],
    contentDirection: ["Sertifikasi & kepatuhan (standar ekspor) sebagai bukti kredibilitas", "Jaringan negara tujuan sebagai bukti skala"],
    avoid: ["Visual yang terasa lokal/kecil untuk citra bisnis internasional"],
    notes: "Export Import: kredibilitas lintas negara — sertifikasi, skala operasi, dan komunikasi bilingual jadi kunci.",
  },
  charcoal: {
    styles: ["industrial", "natural", "bold"],
    colors: ["black", "brown", "earth"],
    audiences: ["b2b", "international", "distributor"],
    personalities: ["autentik", "kuat", "berkelanjutan"],
    deliverables: ["Company profile & spesifikasi produk (kadar air, ukuran, kemasan)", "Foto proses produksi briket/arang", "Katalog ekspor bilingual"],
    toneOfVoice: ["Faktual & teknis (spesifikasi produk jelas)", "Menekankan sumber bahan baku berkelanjutan"],
    photographyDirection: ["Proses produksi (pembakaran, pengeringan, pengemasan)", "Tekstur produk close-up (briket/arang)"],
    visualDirection: ["Palet hitam & earth tone yang kuat", "Tekstur kayu/karbon sebagai elemen visual"],
    contentDirection: ["Traceability sumber bahan baku", "Sertifikasi ekspor & standar kualitas (kadar air, kalori)"],
    avoid: ["Visual yang terlalu 'bersih'/steril — produk ini butuh kesan autentik-industrial"],
    notes: "Charcoal Export: kombinasi kredibilitas teknis produk dengan estetika industrial-natural yang autentik.",
  },
  ai: {
    styles: ["futuristic", "minimalis", "modern"],
    colors: ["purple", "blue", "black"],
    audiences: ["b2b", "startup", "investor", "professional"],
    personalities: ["inovatif", "cerdas", "terpercaya"],
    deliverables: ["Pitch deck dengan visualisasi teknologi", "Diagram cara kerja produk/model", "Product mockup (dashboard/app UI)"],
    toneOfVoice: ["Confident namun tidak overclaim", "Menjelaskan teknologi kompleks secara sederhana"],
    photographyDirection: ["Mockup UI di berbagai device", "Abstraksi visual data/neural network (bukan clipart robot generik)"],
    visualDirection: ["Gradient ungu-biru sebagai identitas futuristik", "Ikonografi custom untuk fitur AI"],
    contentDirection: ["Use case nyata & hasil terukur", "Kepercayaan data & keamanan sebagai isu penting"],
    avoid: ["Clipart robot generik", "Klaim 'AI' tanpa penjelasan konkret"],
    notes: "Technology/AI: kredibilitas teknis + kejelasan value proposition mengalahkan visual futuristik semata.",
  },
  technology: { styles: ["modern", "minimalis", "clean"] },
  software: { deliverables: ["Product screenshot mockup", "Landing page visual", "Diagram fitur"] },
  startup: { personalities: ["berani", "agile", "visioner"] },
  fintech: { colors: ["blue", "green", "black"] },
  hospital: { toneOfVoice: ["Menenangkan", "Profesional & terpercaya"] },
  clinic: { audiences: ["family", "general", "b2c"] },
  pharmacy: { deliverables: ["Katalog produk/obat", "Konten edukasi kesehatan"] },
  school: { audiences: ["family", "student"] },
  university: { personalities: ["akademik", "prestisius", "menginspirasi"] },
  restaurant: { deliverables: ["Foto menu unggulan", "Konten media sosial harian"] },
  fnb: {},
  cafe: { styles: ["natural", "modern", "playful"] },
  bakery: { colors: ["brown", "pastel", "white"] },
  hotel: { audiences: ["premium", "international", "family"] },
  travel: { contentDirection: ["Destinasi & itinerary sebagai konten utama"] },
  tourism: { photographyDirection: ["Wide shot destinasi wisata", "Momen aktivitas wisatawan"] },
  logistics: {},
  freight: { audiences: ["b2b", "international", "corporate"] },
  shipping: { deliverables: ["Infografis rute pelayaran", "Company profile kapabilitas fleet"] },
  warehousing: { photographyDirection: ["Fasilitas gudang skala besar"] },
  manufacturing: {},
  factory: { photographyDirection: ["Lini produksi dalam aksi"] },
  construction: { styles: ["industrial", "bold", "corporate"], colors: ["gray", "orange", "black"] },
  property: {},
  real_estate: { deliverables: ["Virtual tour visual", "Brosur unit & spesifikasi"] },
  architecture: { styles: ["minimalis", "elegant", "modern"] },
  interior: { photographyDirection: ["Interior styling detail", "Before-after ruangan"] },
  consulting: {},
  law: { styles: ["corporate", "classic", "elegant"], colors: ["black", "gold", "blue"] },
  accounting: { personalities: ["teliti", "terpercaya", "presisi"] },
  professional_svcs: {},
  creative_agency: {},
  marketing_agency: { deliverables: ["Portfolio campaign", "Case study hasil kampanye"] },
  media: { personalities: ["kredibel", "tajam", "berpengaruh"] },
  entertainment: { styles: ["bold", "colorful", "creative"] },
  fashion: {},
  beauty: { colors: ["pastel", "gold", "white"] },
  cosmetics: { photographyDirection: ["Detail tekstur produk (swatch)", "Model dengan lighting soft"] },
  jewelry: { styles: ["luxury", "elegant", "premium"], colors: ["gold", "black", "silver"] },
  furniture: {},
  agriculture: {},
  plantation: { photographyDirection: ["Lahan perkebunan luas dari drone/wide shot"] },
  seafood: { colors: ["blue", "white", "gray"] },
  fishery: { audiences: ["b2b", "distributor", "local"] },
  mining: { styles: ["industrial", "bold", "corporate"], colors: ["gray", "black", "orange"] },
  coal: { styles: ["industrial", "bold"], colors: ["black", "gray"] },
  palm_oil: { audiences: ["b2b", "international", "corporate"] },
  coconut: { colors: ["brown", "green", "white"] },
  automotive: {},
  car_dealer: { audiences: ["b2c", "professional", "premium"] },
  motorcycle: { audiences: ["youth", "b2c"] },
  fitness: {},
  gym: { deliverables: ["Konten promosi member baru", "Foto fasilitas gym"] },
  sport_center: { audiences: ["family", "general", "youth"] },
  event_organizer: {},
  wedding: { styles: ["elegant", "premium", "classic"], colors: ["gold", "pastel", "white"] },
  photography: { personalities: ["detail-oriented", "artistik", "personal"] },
  government: { styles: ["corporate", "classic", "clean"], colors: ["blue", "gray", "white"] },
  nonprofit: { toneOfVoice: ["Empatik", "Transparan soal dampak & penggunaan dana"] },
  ecommerce: { deliverables: ["Foto produk untuk marketplace", "Banner promo e-commerce"] },
  marketplace: {},
  retail: {},
  trading: { audiences: ["b2b", "distributor", "corporate"] },
  banking: { styles: ["corporate", "elegant"], colors: ["blue", "black", "gold"] },
  insurance: { toneOfVoice: ["Menenangkan", "Jelas soal manfaat & perlindungan"] },
  healthcare: {},
  education: {},
};

function mergeSeed(base: ProfileSeed, override?: Partial<ProfileSeed>): ProfileSeed {
  if (!override) return base;
  return {
    styles: override.styles ?? base.styles,
    colors: override.colors ?? base.colors,
    audiences: override.audiences ?? base.audiences,
    personalities: override.personalities ?? base.personalities,
    deliverables: override.deliverables ?? base.deliverables,
    toneOfVoice: override.toneOfVoice ?? base.toneOfVoice,
    photographyDirection: override.photographyDirection ?? base.photographyDirection,
    visualDirection: override.visualDirection ?? base.visualDirection,
    contentDirection: override.contentDirection ?? base.contentDirection,
    avoid: override.avoid ?? base.avoid,
    notes: override.notes ?? base.notes,
  };
}

/** Full industry profile registry, keyed by INDUSTRY_OPTIONS value. */
export const INDUSTRY_PROFILES: Record<string, IndustryProfile> = Object.fromEntries(
  INDUSTRY_OPTIONS.filter((opt) => opt.value !== "other").map((opt) => {
    const group = opt.group ?? "Lainnya";
    const base = GROUP_DEFAULTS[group] ?? GROUP_DEFAULTS["Jasa Profesional"];
    const seed = mergeSeed(base, INDUSTRY_OVERRIDES[opt.value]);
    const profile: IndustryProfile = { key: opt.value, label: opt.label, categoryGroup: group, ...seed };
    return [opt.value, profile];
  }),
);

export function getIndustryProfile(key: string | null): IndustryProfile | null {
  if (!key) return null;
  return INDUSTRY_PROFILES[key] ?? null;
}
