import { Router, type IRouter } from "express";
import healthRouter from "./health";
import agentsRouter from "./agents";
import registryRouter from "./registry";
import orchestratorRouter from "./orchestrator";
import workflowsRouter from "./workflows";
import promptsRouter from "./prompts";
import knowledgeRouter from "./knowledge";
import memoryRouter from "./memory";
import auditRouter from "./audit";
import analyticsRouter from "./analytics";
import settingsRouter from "./settings";

import creativeAiRouter from "./creative-ai";
import capabilitiesRouter from "./capabilities";
import feedbackRouter from "./feedback";
import clientMemoryRouter from "./client-memory";
import seedRouter from "./seed";
import testRunsRouter from "./test-runs";
import exportRouter from "./export-routes";
import clientReviewRouter from "./client-review";
import workforceRouter from "./workforce";
import publicRouter from "./public";
import operationsRouter from "./operations";
import jobsRouter from "./jobs";
import dispatcherRouter from "./dispatcher";
import clusterRouter from "./cluster";
import workspaceHealthRouter from "./workspace-health";
import eventsRouter from "./events";
import schedulesRouter from "./schedules";
import marketplaceRouter from "./marketplace";
import humanTasksRouter from "./human-tasks";
import customerPortalRouter from "./customer-portal";
import publicReviewRouter from "./public-review";
import quotationsRouter from "./quotations";
import catalogRouter from "./catalog";
import commercialGatesRouter from "./commercialGates";
import aiQuotationsRouter from "./aiQuotations";
import paymentsRouter from "./payments";
import portfolioRouter from "./portfolio";
import filesRouter from "./files";
import customerWorkspaceRouter from "./customer-workspace";
import adminCustomerWorkspaceRouter from "./admin-customer-workspace";

const router: IRouter = Router();

router.use(healthRouter);
router.use(agentsRouter);
router.use(registryRouter);
router.use(orchestratorRouter);
router.use(workflowsRouter);
router.use(promptsRouter);
router.use(knowledgeRouter);
router.use(memoryRouter);
router.use(auditRouter);
router.use(analyticsRouter);
router.use(settingsRouter);
router.use(creativeAiRouter);
router.use(capabilitiesRouter);
router.use(feedbackRouter);
router.use(clientMemoryRouter);
router.use(seedRouter);
router.use(testRunsRouter);
router.use(exportRouter);
router.use(clientReviewRouter);
router.use(workforceRouter);
router.use(operationsRouter);
router.use(jobsRouter);
router.use(dispatcherRouter);
router.use(clusterRouter);
router.use(workspaceHealthRouter);
router.use(eventsRouter);
router.use(schedulesRouter);
router.use(marketplaceRouter);
router.use(humanTasksRouter);
router.use(customerPortalRouter);
router.use(publicReviewRouter);
router.use(quotationsRouter);
router.use(catalogRouter);
router.use(commercialGatesRouter);
router.use(aiQuotationsRouter);
router.use(paymentsRouter);
router.use(portfolioRouter);
router.use(filesRouter);
router.use(customerWorkspaceRouter);
router.use(adminCustomerWorkspaceRouter);

export default router;
