import { Router, type IRouter } from "express";
import healthRouter from "./health";
import agentsRouter from "./agents";
import registryRouter from "./registry";
import orchestratorRouter from "./orchestrator";
import workflowsRouter from "./workflows";
import promptsRouter from "./prompts";
import knowledgeRouter from "./knowledge";
import memoryRouter from "./memory";
import auditRouter from "./audit";
import analyticsRouter from "./analytics";
import settingsRouter from "./settings";

import creativeAiRouter from "./creative-ai";
import imageBatchRouter from "./image-batch";
import capabilitiesRouter from "./capabilities";
import feedbackRouter from "./feedback";
import clientMemoryRouter from "./client-memory";
import seedRouter from "./seed";
import testRunsRouter from "./test-runs";
import exportRouter from "./export-routes";
import clientReviewRouter from "./client-review";
import workforceRouter from "./workforce";
import publicRouter from "./public";
import operationsRouter from "./operations";
import jobsRouter from "./jobs";
import dispatcherRouter from "./dispatcher";
import clusterRouter from "./cluster";
import workspaceHealthRouter from "./workspace-health";
import eventsRouter from "./events";
import schedulesRouter from "./schedules";
import marketplaceRouter from "./marketplace";
import humanTasksRouter from "./human-tasks";
import customerPortalRouter from "./customer-portal";
import publicReviewRouter from "./public-review";
import cpReviewRouter from "./cp-review";
import quotationsRouter from "./quotations";
import catalogRouter from "./catalog";
import commercialGatesRouter from "./commercialGates";
import aiQuotationsRouter from "./aiQuotations";
import automationRouter from "./automation";
import paymentsRouter from "./payments";
import portfolioRouter from "./portfolio";
import portfolioPublicRouter from "./portfolio-public";
import portfolioBatchRouter from "./portfolio-batch";
import filesRouter from "./files";
import customerWorkspaceRouter from "./customer-workspace";
import customerWorkspaceSseRouter from "./customer-workspace-sse";
import customerWorkspaceDocumentsRouter from "./customer-workspace-documents";
import adminCustomerWorkspaceRouter from "./admin-customer-workspace";
import salesFunnelRouter from "./salesFunnel";
import promotionsRouter from "./promotions";
import couponsRouter from "./coupons";
import referralsRouter from "./referrals";
import affiliatesRouter from "./affiliates";
import customerHealthRouter from "./customerHealth";
import commercialAnalyticsRouter from "./commercialAnalytics";
import storageRouter from "./storage";
import observabilityRouter from "./observability";
import internalAuthRouter from "./internal-auth";
import internalCatalogRouter from "./internal-catalog";
import brandKitEnterpriseRouter from "./brand-kit-enterprise";
import assetLibraryRouter from "./asset-library";
import zipDeliveryRouter from "./zip-delivery";
import brandIntelligenceRouter from "./brand-intelligence";
import assetIntelligenceRouter from "./asset-intelligence";
import templatesRouter from "./templates";
import templateEngineRouter from "./template-engine";
import portfolioGalleryRouter from "./portfolio-gallery";
import productionPipelineRouter from "./production-pipeline";
import designStudioRouter from "./design-studio";
import designTemplatesRouter from "./design-templates";
import designTemplatesAiAssistRouter from "./design-templates-ai-assist";
import creativeMarketplaceRouter from "./creative-marketplace";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(internalAuthRouter);
router.use(internalCatalogRouter);
router.use(agentsRouter);
router.use(registryRouter);
router.use(orchestratorRouter);
router.use(workflowsRouter);
router.use(promptsRouter);
router.use(knowledgeRouter);
router.use(memoryRouter);
router.use(auditRouter);
router.use(analyticsRouter);
router.use(settingsRouter);
router.use(creativeAiRouter);
router.use(imageBatchRouter);
router.use(capabilitiesRouter);
router.use(feedbackRouter);
router.use(clientMemoryRouter);
router.use(seedRouter);
router.use(testRunsRouter);
router.use(exportRouter);
router.use(clientReviewRouter);
router.use(workforceRouter);
router.use(operationsRouter);
router.use(jobsRouter);
router.use(dispatcherRouter);
router.use(clusterRouter);
router.use(workspaceHealthRouter);
router.use(eventsRouter);
router.use(schedulesRouter);
router.use(marketplaceRouter);
router.use(humanTasksRouter);
router.use(customerPortalRouter);
router.use(publicReviewRouter);
router.use(cpReviewRouter);
router.use(quotationsRouter);
router.use(catalogRouter);
router.use(commercialGatesRouter);
router.use(aiQuotationsRouter);
router.use(automationRouter);
router.use(paymentsRouter);
router.use(portfolioRouter);
router.use(portfolioPublicRouter);
router.use(portfolioBatchRouter);
router.use(filesRouter);
router.use(customerWorkspaceRouter);
router.use(brandKitEnterpriseRouter);
router.use(assetLibraryRouter);
router.use(zipDeliveryRouter);
router.use(brandIntelligenceRouter);
router.use(assetIntelligenceRouter);
router.use(templatesRouter);
router.use(templateEngineRouter);
router.use(portfolioGalleryRouter);
router.use(productionPipelineRouter);
router.use(customerWorkspaceSseRouter);
router.use(customerWorkspaceDocumentsRouter);
router.use(adminCustomerWorkspaceRouter);
router.use(salesFunnelRouter);
router.use(promotionsRouter);
router.use(couponsRouter);
router.use(referralsRouter);
router.use(affiliatesRouter);
router.use(customerHealthRouter);
router.use(commercialAnalyticsRouter);
router.use(observabilityRouter);
router.use(designStudioRouter);
router.use(designTemplatesRouter);
router.use(designTemplatesAiAssistRouter);
router.use(creativeMarketplaceRouter);

export default router;
