/**
 * Workspace Health Route — Phase 5.1.5
 *
 * GET /api/internal/workspace-health
 *
 * Returns a snapshot of the monorepo build system health:
 * generated file status, OpenAPI spec status, package info, dist status.
 *
 * This endpoint is intentionally auth-protected (admin key required) because
 * it exposes internal file paths and timestamps.
 */

import { Router } from "express";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const router = Router();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..", "..", "..", "..");

const GENERATED_DIRS = [
  "lib/api-client-react/src/generated",
  "lib/api-zod/src/generated",
] as const;

const DIST_DIRS = ["artifacts/api-server/dist"] as const;
const SOURCE_DIRS = ["artifacts/api-server/src"] as const;

function abs(rel: string) {
  return path.join(ROOT, rel);
}

function walkFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...walkFiles(full));
    else files.push(full);
  }
  return files;
}

function lastModifiedMs(dir: string): number {
  const files = walkFiles(dir);
  return files.length === 0 ? 0 : Math.max(...files.map((f) => fs.statSync(f).mtimeMs));
}

router.get("/internal/workspace-health", (_req, res): void => {
  const report: Record<string, unknown> = {
    timestamp: new Date().toISOString(),
    nodeVersion: process.version,
    env: process.env["NODE_ENV"] ?? "unknown",
  };

  // Generated status
  const generatedStatus: Record<string, unknown> = {};
  for (const genDir of GENERATED_DIRS) {
    const full = abs(genDir);
    const exists = fs.existsSync(full);
    const files = exists ? walkFiles(full).filter((f) => f.endsWith(".ts")) : [];
    const lastMod = files.length > 0
      ? new Date(Math.max(...files.map((f) => fs.statSync(f).mtimeMs))).toISOString()
      : null;
    const hasOrvalHeaders = files.length > 0
      && files.every((f) => fs.readFileSync(f, "utf8").includes("Generated by orval"));

    generatedStatus[genDir] = {
      exists,
      fileCount: files.length,
      lastModified: lastMod,
      hasOrvalHeaders,
      status: !exists ? "missing" : !hasOrvalHeaders ? "tampered" : "ok",
    };
  }
  report["generatedStatus"] = generatedStatus;

  // OpenAPI spec status
  const specPath = abs("lib/api-spec/openapi.yaml");
  const specExists = fs.existsSync(specPath);
  let operationCount = 0;
  let specTampered = false;
  if (specExists) {
    const content = fs.readFileSync(specPath, "utf8");
    operationCount = [...content.matchAll(/operationId:/g)].length;
    // Check for duplicate operationIds
    const ids = [...content.matchAll(/operationId:\s*(\w+)/g)].map((m) => m[1]);
    const seen = new Set<string>();
    for (const id of ids) {
      if (seen.has(id)) { specTampered = true; break; }
      seen.add(id);
    }
  }
  report["openapiStatus"] = {
    exists: specExists,
    lastModified: specExists ? new Date(fs.statSync(specPath).mtimeMs).toISOString() : null,
    operationCount,
    hasDuplicateOperationIds: specTampered,
    status: !specExists ? "missing" : specTampered ? "invalid" : "ok",
  };

  // Dist status
  const distStatus: Record<string, unknown> = {};
  for (let i = 0; i < DIST_DIRS.length; i++) {
    const distDir = DIST_DIRS[i];
    const srcDir  = SOURCE_DIRS[i];
    const full = abs(distDir);
    const exists = fs.existsSync(full);
    const files = exists ? walkFiles(full) : [];
    const lastMod = files.length > 0
      ? new Date(Math.max(...files.map((f) => fs.statSync(f).mtimeMs))).toISOString()
      : null;
    let stale = false;
    if (srcDir && exists) {
      stale = lastModifiedMs(abs(srcDir)) > lastModifiedMs(full) + 5_000;
    }
    distStatus[distDir] = { exists, fileCount: files.length, stale, lastModified: lastMod };
  }
  report["distStatus"] = distStatus;

  // Package versions (from package.json files)
  const packageVersions: Record<string, string> = {};
  const pkgPaths = [
    "package.json",
    "lib/api-spec/package.json",
    "lib/api-client-react/package.json",
    "lib/api-zod/package.json",
    "lib/db/package.json",
    "artifacts/api-server/package.json",
    "artifacts/ai-platform/package.json",
  ];
  for (const pkgPath of pkgPaths) {
    const full = abs(pkgPath);
    if (fs.existsSync(full)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(full, "utf8")) as { name?: string; version?: string };
        if (pkg.name) packageVersions[pkg.name] = pkg.version ?? "0.0.0";
      } catch { /* ignore */ }
    }
  }
  report["packageVersions"] = packageVersions;

  // Workspace cache status (node_modules presence)
  report["workspaceCache"] = {
    rootNodeModules: fs.existsSync(abs("node_modules")),
    pnpmLockExists: fs.existsSync(abs("pnpm-lock.yaml")),
  };

  // Overall health
  const genStatuses = Object.values(generatedStatus) as Array<{ status: string }>;
  const allGenOk = genStatuses.every((g) => g.status === "ok");
  const specOk = (report["openapiStatus"] as { status: string }).status === "ok";
  report["overall"] = allGenOk && specOk ? "healthy" : "degraded";

  res.json(report);
});

export default router;
