/**
 * Phase 5.2 — Cluster request body schemas (manual, not generated).
 * Note: RegisterClusterWorkerBody is now generated by orval.
 * This file only contains RenewLeaseBody which has a different generated name (RenewWorkerLeaseBody).
 */
import * as zod from "zod";

export const RenewLeaseBody = zod.object({
  heartbeatToken: zod.string().min(1),
  leaseTtlMs:     zod.number().int().min(5000).max(300_000).optional(),
});
