/**
 * Phase 5.5 — Event Bus request body schemas (manual, not generated).
 * Note: ListEventsQueryParams and PublishEventBody are now generated by orval.
 * This file only contains schemas NOT in the generated output.
 */
import * as zod from "zod";

export const CreateSubscriptionBody = zod.object({
  subscriptionName:  zod.string().min(1),
  eventType:         zod.string().min(1),
  targetType:        zod.string().optional(),
  targetId:          zod.string().optional(),
  handlerType:       zod.enum([
    "create_job",
    "audit_log",
    "notification_hook",
    "update_project_status",
    "call_webhook",
  ]),
  handlerConfig:     zod.record(zod.unknown()).optional().default({}),
  retryPolicy:       zod.record(zod.unknown()).optional().default({}),
});

export const UpdateSubscriptionBody = zod.object({
  status:        zod.enum(["active", "paused", "disabled"]).optional(),
  handlerType:   zod.enum([
    "create_job",
    "audit_log",
    "notification_hook",
    "update_project_status",
    "call_webhook",
  ]).optional(),
  handlerConfig: zod.record(zod.unknown()).optional(),
  retryPolicy:   zod.record(zod.unknown()).optional(),
});
