/**
 * Phase 6.5 — Human Task Center schemas.
 * All schemas are generated by orval from the OpenAPI spec.
 * This file is intentionally empty — kept as a placeholder for future manual schemas.
 */
export {};
