/**
 * Image Preview Pipeline — Two-Stage Image Generation schemas.
 * Manual Zod schemas (not generated by orval).
 *
 * Pipeline: Brief → Preview (4 cheap concepts) → Customer selects 1 → Final render (QC'd)
 */
import * as zod from "zod";

// ── Shared enums ──────────────────────────────────────────────────────────────

export const RenderSessionStatusEnum = zod.enum([
  "planning",
  "preview_generating",
  "preview_ready",
  "waiting_customer",
  "concept_selected",
  "final_generating",
  "quality_check",
  "completed",
  "failed",
]);

export const PackageTierEnum = zod.enum(["standard", "premium", "enterprise"]);

// ── Preview concept (an asset in preview stage) ───────────────────────────────

export const PreviewConceptSchema = zod.object({
  id: zod.number(),
  projectId: zod.string(),
  renderSessionId: zod.number().nullable(),
  conceptIndex: zod.number().nullable(),
  imageUrl: zod.string().nullable(),
  thumbnailUrl: zod.string().nullable(),
  prompt: zod.string(),
  aspectRatio: zod.string().nullable(),
  status: zod.string(),
  aiExplanation: zod.string().nullable(),
  metadata: zod.record(zod.unknown()).nullable(),
  estimatedFinalCostUsd: zod.number().nullable(),
  estimatedRenderTimeMs: zod.number().nullable(),
  cost: zod.number().nullable(),
  createdAt: zod.string(),
});

// ── Render session ────────────────────────────────────────────────────────────

export const RenderSessionSchema = zod.object({
  id: zod.number(),
  projectId: zod.string(),
  sessionStatus: RenderSessionStatusEnum,
  packageTier: PackageTierEnum,
  previewCount: zod.number(),
  previewCostUsd: zod.number(),
  finalCostUsd: zod.number(),
  qcCostUsd: zod.number(),
  totalCostUsd: zod.number(),
  selectedConceptId: zod.number().nullable(),
  customerFeedback: zod.string().nullable(),
  requestedFinalCount: zod.number(),
  metadata: zod.record(zod.unknown()).nullable(),
  createdAt: zod.string(),
  updatedAt: zod.string(),
  previewConcepts: zod.array(PreviewConceptSchema).optional(),
  finalAssets: zod.array(zod.object({
    id: zod.number(),
    imageUrl: zod.string().nullable(),
    thumbnailUrl: zod.string().nullable(),
    status: zod.string(),
    qcScore: zod.number().nullable(),
    qcNotes: zod.string().nullable(),
    cost: zod.number().nullable(),
    createdAt: zod.string(),
  })).optional(),
});

// ── Request bodies ────────────────────────────────────────────────────────────

/** POST /creative-ai/projects/:id/sessions */
export const StartPreviewSessionBody = zod.object({
  packageTier: PackageTierEnum.optional().default("standard"),
  previewCount: zod.number().int().min(1).max(8).optional().default(4),
  requestedFinalCount: zod.number().int().min(1).max(20).optional().default(1),
});

export const StartPreviewSessionParams = zod.object({
  id: zod.string().uuid(),
});

export const StartPreviewSessionResponse = zod.object({
  sessionId: zod.number(),
  projectId: zod.string(),
  sessionStatus: RenderSessionStatusEnum,
  packageTier: PackageTierEnum,
  previewCount: zod.number(),
  message: zod.string(),
});

/** GET /creative-ai/projects/:id/sessions */
export const ListProjectSessionsParams = zod.object({
  id: zod.string().uuid(),
});

export const ListProjectSessionsResponse = zod.array(RenderSessionSchema);

/** GET /creative-ai/sessions/:sessionId */
export const GetRenderSessionParams = zod.object({
  sessionId: zod.coerce.number().int().positive(),
});

export const GetRenderSessionResponse = RenderSessionSchema;

/** POST /creative-ai/sessions/:sessionId/select-concept */
export const SelectConceptParams = zod.object({
  sessionId: zod.coerce.number().int().positive(),
});

export const SelectConceptBody = zod.object({
  conceptAssetId: zod.number().int().positive(),
  feedback: zod.string().optional(),
});

export const SelectConceptResponse = zod.object({
  sessionId: zod.number(),
  selectedConceptId: zod.number(),
  sessionStatus: RenderSessionStatusEnum,
  message: zod.string(),
});

/** POST /creative-ai/sessions/:sessionId/generate-final */
export const GenerateFinalParams = zod.object({
  sessionId: zod.coerce.number().int().positive(),
});

export const GenerateFinalBody = zod.object({
  requestedCount: zod.number().int().min(1).max(20).optional(),
});

export const GenerateFinalResponse = zod.object({
  sessionId: zod.number(),
  sessionStatus: RenderSessionStatusEnum,
  requestedCount: zod.number(),
  message: zod.string(),
});

/** POST /creative-ai/sessions/:sessionId/more-previews */
export const MorePreviewsParams = zod.object({
  sessionId: zod.coerce.number().int().positive(),
});

export const MorePreviewsBody = zod.object({
  count: zod.number().int().min(1).max(4).optional().default(4),
});

export const MorePreviewsResponse = zod.object({
  sessionId: zod.number(),
  sessionStatus: RenderSessionStatusEnum,
  count: zod.number(),
  message: zod.string(),
});

/** GET /creative-ai/analytics/preview-pipeline */
export const PreviewPipelineAnalyticsQuery = zod.object({
  days: zod.coerce.number().int().min(1).max(365).optional().default(30),
});

export const PreviewPipelineAnalyticsResponse = zod.object({
  totalSessions: zod.number(),
  completedSessions: zod.number(),
  avgPreviewsPerSession: zod.number().nullable(),
  previewAcceptedRate: zod.number().nullable(),
  previewRejectedRate: zod.number().nullable(),
  avgPreviewCostUsd: zod.number().nullable(),
  avgFinalCostUsd: zod.number().nullable(),
  totalCostSavedUsd: zod.number().nullable(),
  revisionRate: zod.number().nullable(),
  renderSuccessRate: zod.number().nullable(),
});
