/**
 * Phase 8 — AI Skills Marketplace & Tool Ecosystem request body schemas
 * (manual, not generated by orval).
 */
import * as zod from "zod";

export const PackageType = zod.enum(["skill", "tool"]);

export const InstallPackageBody = zod.object({
  tenantId: zod.string().min(1).default("default"),
  packageType: PackageType,
  packageId: zod.number().int().positive(),
  configuration: zod.record(zod.string(), zod.unknown()).optional(),
});

export const UpgradePackageBody = zod.object({
  tenantId: zod.string().min(1).default("default"),
});

export const TogglePackageBody = zod.object({
  tenantId: zod.string().min(1).default("default"),
});

export const UninstallPackageQuery = zod.object({
  tenantId: zod.string().min(1).default("default"),
});

export const ListInstalledQuery = zod.object({
  tenantId: zod.string().min(1).default("default"),
  packageType: PackageType.optional(),
});

export const PackageRouteParams = zod.object({
  packageType: PackageType,
  id: zod.coerce.number().int().positive(),
});

export const ToolIdParam = zod.coerce.number().int().positive();
