/**
 * Phase 6 — AI Scheduler request body / query schemas (manual, not generated).
 * Note: CreateScheduleBody, UpdateScheduleBody, ListSchedulesQueryParams,
 * ListScheduleRunsQueryParams, and UpdateSchedulerSettingsBody are now generated by orval.
 * This file is intentionally empty — kept as a placeholder for future manual schemas.
 */
export {};
