/**
 * events.ts — DesignCommand and DesignEvent envelopes
 *
 * All messages flowing through the Universal Design Platform are wrapped in
 * one of two typed envelopes:
 *
 *   DesignCommand — intent sent FROM a consumer TO the platform
 *                   ("please do X for project P")
 *   DesignEvent   — fact emitted BY the platform
 *                   ("X happened to project P at time T")
 *
 * Both envelopes carry:
 *   - a stable eventType / commandType string (versioned by the producer)
 *   - project + tenant context (never accepted from untrusted input)
 *   - actor + correlation chain for distributed tracing
 *   - a payloadVersion for per-type payload evolution
 *   - a typed, generic payload (consumers bind T to their domain type)
 *
 * Rules:
 *   - Event IDs are UUIDs generated by the emitter; never reused.
 *   - causationId links an event to the command that caused it.
 *   - payloadVersion evolves independently of the envelope contractVersion.
 *   - The core engine never reads the payload — only the envelope fields.
 */

import { z } from "zod";

// ── Shared envelope base ──────────────────────────────────────────────────────

const DesignEnvelopeBaseSchema = z.object({
  /** UUID generated by the producer; globally unique. */
  eventId: z.string().uuid(),
  /** UTC ISO-8601 timestamp of when the message was produced. */
  occurredAt: z.string().datetime(),
  /** Project this message relates to. */
  projectId: z.string().uuid(),
  /** Tenant that owns the project. */
  tenantId: z.string().min(1),
  /** Actor that initiated the command or event. */
  actor: z.object({
    actorId: z.string().min(1),
    actorType: z.string().min(1),
  }),
  /** Distributed-tracing correlation ID (spans the entire request chain). */
  correlationId: z.string().uuid(),
  /**
   * ID of the upstream event or command that caused this message.
   * Null for root commands (no upstream cause).
   */
  causationId: z.string().uuid().nullable().optional(),
  /**
   * Version of the design-contracts envelope schema.
   * Must satisfy isCompatibleVersion() at the consumer.
   */
  contractVersion: z.number().int().positive(),
  /**
   * Version of the typed payload (T). Starts at 1 and increments when the
   * payload shape changes. Independent of contractVersion.
   */
  payloadVersion: z.number().int().positive().default(1),
});

// ── DesignCommand ─────────────────────────────────────────────────────────────

/**
 * Typed command envelope. T is the payload type (defined per command type).
 *
 * commandType naming convention: "<verb>_<noun>" in SCREAMING_SNAKE_CASE.
 * Examples: "START_STAGE", "SUBMIT_BRIEF", "REQUEST_REVISION", "APPROVE_ARTIFACT".
 */
export const DesignCommandSchema = <T extends z.ZodTypeAny>(payloadSchema: T) =>
  DesignEnvelopeBaseSchema.extend({
    /** Stable command type string. */
    commandType: z.string().min(1).max(100),
    /** Typed command payload. */
    payload: payloadSchema,
  });

export type DesignCommand<T = unknown> = z.infer<ReturnType<typeof DesignCommandSchema>> & {
  commandType: string;
  payload: T;
};

/**
 * Untyped command schema for validation at the envelope level
 * (when the consumer doesn't know the payload type yet).
 */
export const GenericDesignCommandSchema = DesignEnvelopeBaseSchema.extend({
  commandType: z.string().min(1).max(100),
  payload: z.unknown(),
});

export type GenericDesignCommand = z.infer<typeof GenericDesignCommandSchema>;

// ── DesignEvent ───────────────────────────────────────────────────────────────

/**
 * Typed event envelope. T is the payload type (defined per event type).
 *
 * eventType naming convention: "<noun>_<past_tense_verb>" in SCREAMING_SNAKE_CASE.
 * Examples: "STAGE_STARTED", "ARTIFACT_GENERATED", "REVIEW_APPROVED", "PROJECT_COMPLETED".
 */
export const DesignEventSchema = <T extends z.ZodTypeAny>(payloadSchema: T) =>
  DesignEnvelopeBaseSchema.extend({
    /** Stable event type string. */
    eventType: z.string().min(1).max(100),
    /** Typed event payload. */
    payload: payloadSchema,
  });

export type DesignEvent<T = unknown> = z.infer<ReturnType<typeof DesignCommandSchema>> & {
  eventType: string;
  payload: T;
};

/**
 * Untyped event schema for validation at the envelope level.
 */
export const GenericDesignEventSchema = DesignEnvelopeBaseSchema.extend({
  eventType: z.string().min(1).max(100),
  payload: z.unknown(),
});

export type GenericDesignEvent = z.infer<typeof GenericDesignEventSchema>;

// ── Well-known event types (non-exhaustive, not enforced by core) ─────────────
// Plugins may emit additional domain-specific event types. The core engine
// routes by projectId+tenantId, not by eventType.

export const WELL_KNOWN_DESIGN_EVENTS = {
  // Project lifecycle
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_STATUS_CHANGED: "PROJECT_STATUS_CHANGED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  PROJECT_CANCELLED: "PROJECT_CANCELLED",
  // Stage lifecycle
  STAGE_STARTED: "STAGE_STARTED",
  STAGE_COMPLETED: "STAGE_COMPLETED",
  STAGE_FAILED: "STAGE_FAILED",
  STAGE_SKIPPED: "STAGE_SKIPPED",
  // Artifact lifecycle
  ARTIFACT_GENERATED: "ARTIFACT_GENERATED",
  ARTIFACT_SUPERSEDED: "ARTIFACT_SUPERSEDED",
  // Review
  REVIEW_SUBMITTED: "REVIEW_SUBMITTED",
  REVIEW_APPROVED: "REVIEW_APPROVED",
  REVIEW_REJECTED: "REVIEW_REJECTED",
  REVISION_REQUESTED: "REVISION_REQUESTED",
  // Capability
  CAPABILITY_INVOKED: "CAPABILITY_INVOKED",
  CAPABILITY_COMPLETED: "CAPABILITY_COMPLETED",
  CAPABILITY_FAILED: "CAPABILITY_FAILED",
} as const;

export type WellKnownDesignEvent = (typeof WELL_KNOWN_DESIGN_EVENTS)[keyof typeof WELL_KNOWN_DESIGN_EVENTS];

export const WELL_KNOWN_DESIGN_COMMANDS = {
  START_STAGE: "START_STAGE",
  SKIP_STAGE: "SKIP_STAGE",
  SUBMIT_BRIEF: "SUBMIT_BRIEF",
  INVOKE_CAPABILITY: "INVOKE_CAPABILITY",
  SUBMIT_REVIEW: "SUBMIT_REVIEW",
  APPROVE_ARTIFACT: "APPROVE_ARTIFACT",
  REQUEST_REVISION: "REQUEST_REVISION",
  CANCEL_PROJECT: "CANCEL_PROJECT",
} as const;

export type WellKnownDesignCommand = (typeof WELL_KNOWN_DESIGN_COMMANDS)[keyof typeof WELL_KNOWN_DESIGN_COMMANDS];
