/**
 * metadata.ts — ContractMetadata
 *
 * Canonical metadata attached to any contract object that records:
 *   - who created/updated it
 *   - when it was created/updated
 *   - what engine or process generated it
 *
 * All fields are optional so that existing contracts are not forced to carry
 * mandatory new fields — this is a purely additive enhancement.
 *
 * Attach ContractMetadata to any contract via the `contractMetadata` field:
 *
 *   myContract = {
 *     ...coreFields,
 *     contractMetadata: {
 *       source: "ai",
 *       generator: "creative-ai",
 *       generatorVersion: "2.1.0",
 *       createdAt: new Date().toISOString(),
 *       createdBy: "usr_123",
 *     },
 *   };
 */

import { z } from "zod";

// ── Metadata source enum ───────────────────────────────────────────────────────

/**
 * Describes what process or actor created/updated the contract object.
 *
 * - human        — directly authored by a human user or admin.
 * - ai           — generated by an AI model or agent (e.g. creative-ai).
 * - import       — ingested from an external file or data import process.
 * - migration    — produced by an automated database/schema migration.
 * - external-api — received from a third-party API or integration.
 */
export const CONTRACT_METADATA_SOURCES = [
  "human",
  "ai",
  "import",
  "migration",
  "external-api",
] as const;

export type ContractMetadataSource = (typeof CONTRACT_METADATA_SOURCES)[number];

// ── Generator names (well-known values; not an exhaustive enum) ───────────────

/**
 * Well-known generator names. Teams may use any string; these constants
 * establish the canonical vocabulary for platform-owned generators.
 */
export const WELL_KNOWN_GENERATORS = [
  "creative-ai",
  "presentation-engine",
  "document-engine",
  "workflow-engine",
  "design-template-engine",
  "brief-assistant",
  "human",
] as const;

export type WellKnownGenerator = (typeof WELL_KNOWN_GENERATORS)[number];

// ── ContractMetadata schema ────────────────────────────────────────────────────

export const ContractMetadataSchema = z.object({
  /**
   * ISO-8601 timestamp of when the contract object was first created.
   * Optional — may not be available for imported or migrated records.
   */
  createdAt: z.string().datetime().optional(),
  /**
   * ISO-8601 timestamp of the most recent update to the contract object.
   */
  updatedAt: z.string().datetime().optional(),
  /**
   * Actor ID (user, system, or service account) that created this object.
   * Opaque string — not validated against the user table.
   */
  createdBy: z.string().max(200).optional(),
  /**
   * Actor ID that last updated this object.
   */
  updatedBy: z.string().max(200).optional(),
  /**
   * Source classification: who or what process authored the contract.
   */
  source: z.enum(CONTRACT_METADATA_SOURCES).optional(),
  /**
   * Name of the engine or tool that generated this contract.
   * Examples: "creative-ai", "presentation-engine", "document-engine".
   * Opaque to the core engine — used for audit and diagnostics only.
   */
  generator: z.string().max(100).optional(),
  /**
   * Semantic version of the generator (e.g. "2.1.0").
   * Lets downstream consumers reproduce or debug generation behaviour.
   */
  generatorVersion: z.string().max(50).optional(),
});

export type ContractMetadata = z.infer<typeof ContractMetadataSchema>;
