// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/apex-admin/AdminDesktop.tsx": () => import("../components/mockups/apex-admin/AdminDesktop.tsx"),
  "./components/mockups/apex-admin/AdminMobile.tsx": () => import("../components/mockups/apex-admin/AdminMobile.tsx"),
  "./components/mockups/apex-portal/PortalDesktop.tsx": () => import("../components/mockups/apex-portal/PortalDesktop.tsx"),
  "./components/mockups/apex-portal/PortalMobile.tsx": () => import("../components/mockups/apex-portal/PortalMobile.tsx"),
  "./components/mockups/cp-portal/ClientDashboard.tsx": () => import("../components/mockups/cp-portal/ClientDashboard.tsx"),
  "./components/mockups/cp-portal/Dashboard.tsx": () => import("../components/mockups/cp-portal/Dashboard.tsx"),
  "./components/mockups/cp-portal/Invoice.tsx": () => import("../components/mockups/cp-portal/Invoice.tsx"),
  "./components/mockups/cp-portal/Landing.tsx": () => import("../components/mockups/cp-portal/Landing.tsx"),
  "./components/mockups/cp-portal/MyProjects.tsx": () => import("../components/mockups/cp-portal/MyProjects.tsx"),
  "./components/mockups/cp-portal/NewRequest.tsx": () => import("../components/mockups/cp-portal/NewRequest.tsx"),
  "./components/mockups/cp-portal/Notifications.tsx": () => import("../components/mockups/cp-portal/Notifications.tsx"),
  "./components/mockups/cp-portal/Profile.tsx": () => import("../components/mockups/cp-portal/Profile.tsx"),
  "./components/mockups/cp-portal/ProjectDetail.tsx": () => import("../components/mockups/cp-portal/ProjectDetail.tsx"),
  "./components/mockups/cp-portal/Quotation.tsx": () => import("../components/mockups/cp-portal/Quotation.tsx"),
  "./components/mockups/cp-portal/QuotationReview.tsx": () => import("../components/mockups/cp-portal/QuotationReview.tsx"),
  "./components/mockups/cp-portal/ServiceDetail.tsx": () => import("../components/mockups/cp-portal/ServiceDetail.tsx"),
  "./components/mockups/cp-portal/ServicesCatalog.tsx": () => import("../components/mockups/cp-portal/ServicesCatalog.tsx"),
  "./components/mockups/cp-portal/SubmitBrief.tsx": () => import("../components/mockups/cp-portal/SubmitBrief.tsx"),
  "./components/mockups/cp-portal/SuccessOnboarding.tsx": () => import("../components/mockups/cp-portal/SuccessOnboarding.tsx"),
  "./components/mockups/cp-portal/Workspace.tsx": () => import("../components/mockups/cp-portal/Workspace.tsx")
};
