// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cp-portal/Dashboard.tsx": () => import("../components/mockups/cp-portal/Dashboard.tsx"),
  "./components/mockups/cp-portal/Invoice.tsx": () => import("../components/mockups/cp-portal/Invoice.tsx"),
  "./components/mockups/cp-portal/MyProjects.tsx": () => import("../components/mockups/cp-portal/MyProjects.tsx"),
  "./components/mockups/cp-portal/NewRequest.tsx": () => import("../components/mockups/cp-portal/NewRequest.tsx"),
  "./components/mockups/cp-portal/Notifications.tsx": () => import("../components/mockups/cp-portal/Notifications.tsx"),
  "./components/mockups/cp-portal/Profile.tsx": () => import("../components/mockups/cp-portal/Profile.tsx"),
  "./components/mockups/cp-portal/Quotation.tsx": () => import("../components/mockups/cp-portal/Quotation.tsx"),
  "./components/mockups/cp-portal/Workspace.tsx": () => import("../components/mockups/cp-portal/Workspace.tsx")
};
