/**
 * Seed V4.3 Template Library — 60 templates across 20 categories and 13 industries.
 * Idempotent (uses onConflictDoUpdate).
 * Run: pnpm seed:templates
 */
import { db, aiTemplatesTable } from "@workspace/db";

const STYLES = ["Modern", "Classic", "Minimalist", "Bold", "Elegant", "Professional", "Creative", "Corporate"];
const PACKAGES = ["starter", "standard", "professional", "enterprise"];

type TemplateRow = typeof aiTemplatesTable.$inferInsert;

const TEMPLATES: Omit<TemplateRow, "createdAt" | "updatedAt">[] = [
  // ── Company Profile ──────────────────────────────────────────────────────────
  {
    templateCode: "CP-MOD-001",
    name: "Company Profile Modern",
    description: "Sleek modern company profile with bold typography and clean sections. Ideal for tech and fintech brands.",
    category: "Company Profile",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#8B5CF6", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Innovative", "Modern"], voices: ["Authoritative", "Formal"], audiences: ["B2B", "Enterprise", "Corporate"], industries: ["Technology", "Finance", "Startup"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/white?text=Modern+CP", hero: "https://placehold.co/1200x630/6366F1/white?text=Company+Profile+Modern", gallery: ["https://placehold.co/800x600/6366F1/white?text=Page+1", "https://placehold.co/800x600/8B5CF6/white?text=Page+2"] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 1, views: 340, selections: 45, previewsGenerated: 120, conversions: 18,
  },
  {
    templateCode: "CP-CLS-002",
    name: "Company Profile Classic",
    description: "Timeless classic design with serif typography and structured layout. Perfect for law firms, consulting, and finance.",
    category: "Company Profile",
    style: "Classic",
    industry: "Legal",
    colorTheme: { primary: "#1E3A5F", secondary: "#2E6DA4", accent: "#C9A84C", background: "#FAFAFA", text: "#1A1A1A" },
    typography: { heading: "Georgia", body: "Times New Roman", style: "serif" },
    layout: "single-column",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Trustworthy", "Professional", "Prestigious"], voices: ["Formal", "Authoritative"], audiences: ["Corporate", "Legal", "HNW"], industries: ["Legal", "Finance", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Classic+CP", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Company+Profile+Classic", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 2, views: 280, selections: 38, previewsGenerated: 95, conversions: 15,
  },
  {
    templateCode: "CP-MIN-003",
    name: "Company Profile Minimalist",
    description: "White space-driven minimalist design. Communicates sophistication through restraint.",
    category: "Company Profile",
    style: "Minimalist",
    industry: null,
    colorTheme: { primary: "#111827", secondary: "#374151", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "DM Sans", body: "DM Sans", style: "sans-serif" },
    layout: "single-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Modern", "Clean", "Premium"], voices: ["Confident", "Direct"], audiences: ["SME", "Design-conscious", "Startup"], industries: ["Technology", "Design", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/111827/white?text=Minimal+CP", hero: "https://placehold.co/1200x630/111827/white?text=Minimalist+CP", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 3, views: 195, selections: 28, previewsGenerated: 80, conversions: 10,
  },

  // ── Pitch Deck ────────────────────────────────────────────────────────────────
  {
    templateCode: "PD-MOD-001",
    name: "Pitch Deck Modern Startup",
    description: "Investor-grade pitch deck with problem/solution/traction narrative. Dark mode available.",
    category: "Pitch Deck",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6D28D9", secondary: "#4C1D95", accent: "#F59E0B", background: "#0F0A1E", text: "#F9FAFB" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "presentation",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Innovative", "Bold", "Disruptive"], voices: ["Confident", "Visionary"], audiences: ["Investors", "VC", "Startup"], industries: ["Technology", "Startup", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6D28D9/white?text=Pitch+Deck", hero: "https://placehold.co/1200x630/6D28D9/white?text=Startup+Pitch+Deck", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 10, views: 510, selections: 72, previewsGenerated: 180, conversions: 32,
  },
  {
    templateCode: "PD-COR-002",
    name: "Pitch Deck Corporate",
    description: "Structured corporate pitch with executive summary, market analysis, and financial projections.",
    category: "Pitch Deck",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#1E40AF", secondary: "#1D4ED8", accent: "#FBBF24", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Calibri", body: "Arial", style: "sans-serif" },
    layout: "presentation",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Professional", "Trustworthy", "Data-driven"], voices: ["Analytical", "Formal"], audiences: ["Corporate", "Investors", "Board"], industries: ["Finance", "Manufacturing", "Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E40AF/white?text=Corp+Pitch", hero: "https://placehold.co/1200x630/1E40AF/white?text=Corporate+Pitch+Deck", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 11, views: 380, selections: 55, previewsGenerated: 140, conversions: 22,
  },

  // ── Proposal ──────────────────────────────────────────────────────────────────
  {
    templateCode: "PROP-PRO-001",
    name: "Business Proposal Professional",
    description: "Comprehensive business proposal with executive summary, scope, timeline, and pricing table.",
    category: "Proposal",
    style: "Professional",
    industry: null,
    colorTheme: { primary: "#0F766E", secondary: "#134E4A", accent: "#F59E0B", background: "#FFFFFF", text: "#1C1917" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Trustworthy", "Competent"], voices: ["Persuasive", "Clear"], audiences: ["Corporate", "SME", "Government"], industries: ["Consulting", "Construction", "Technology"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F766E/white?text=Proposal", hero: "https://placehold.co/1200x630/0F766E/white?text=Business+Proposal", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 20, views: 290, selections: 42, previewsGenerated: 110, conversions: 19,
  },

  // ── Product Catalog ───────────────────────────────────────────────────────────
  {
    templateCode: "CAT-MOD-001",
    name: "Product Catalog Modern Grid",
    description: "Grid-based product catalog with high-impact photography layout and pricing tables.",
    category: "Product Catalog",
    style: "Modern",
    industry: "Retail",
    colorTheme: { primary: "#DC2626", secondary: "#991B1B", accent: "#F97316", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Roboto", style: "sans-serif" },
    layout: "grid",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Dynamic", "Bold", "Commercial"], voices: ["Engaging", "Persuasive"], audiences: ["Consumer", "Retail", "B2C"], industries: ["Retail", "F&B", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/DC2626/white?text=Product+Catalog", hero: "https://placehold.co/1200x630/DC2626/white?text=Product+Catalog", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 30, views: 220, selections: 30, previewsGenerated: 75, conversions: 12,
  },
  {
    templateCode: "CAT-ELG-002",
    name: "Product Catalog Elegant",
    description: "Luxury product catalog with magazine-style layout. Ideal for premium goods and F&B.",
    category: "Product Catalog",
    style: "Elegant",
    industry: "F&B",
    colorTheme: { primary: "#78350F", secondary: "#92400E", accent: "#D97706", background: "#FFFBEB", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lora", style: "serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Luxury", "Premium", "Artisan"], voices: ["Refined", "Sensory"], audiences: ["Premium", "HNW", "Connoisseur"], industries: ["F&B", "Property", "Retail"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/78350F/white?text=Elegant+Catalog", hero: "https://placehold.co/1200x630/78350F/white?text=Elegant+Catalog", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 31, views: 175, selections: 25, previewsGenerated: 65, conversions: 9,
  },

  // ── Corporate Profile ─────────────────────────────────────────────────────────
  {
    templateCode: "CORP-PRO-001",
    name: "Corporate Profile Enterprise",
    description: "Full enterprise corporate profile: org chart, leadership, CSR, financials, and global presence.",
    category: "Corporate Profile",
    style: "Corporate",
    industry: "Manufacturing",
    colorTheme: { primary: "#1F2937", secondary: "#374151", accent: "#2563EB", background: "#F9FAFB", text: "#111827" },
    typography: { heading: "Arial Bold", body: "Arial", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Corporate", "Trustworthy", "Established"], voices: ["Authoritative", "Formal"], audiences: ["Enterprise", "Investors", "Government"], industries: ["Manufacturing", "Export", "Construction"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1F2937/white?text=Corp+Profile", hero: "https://placehold.co/1200x630/1F2937/white?text=Corporate+Profile", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 40, views: 430, selections: 62, previewsGenerated: 155, conversions: 27,
  },

  // ── Brochure ──────────────────────────────────────────────────────────────────
  {
    templateCode: "BRO-MOD-001",
    name: "Brochure Modern Tri-fold",
    description: "Tri-fold brochure with bold color blocks and infographic elements.",
    category: "Brochure",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#5B21B6", accent: "#EC4899", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Open Sans", style: "sans-serif" },
    layout: "tri-fold",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Dynamic", "Vibrant", "Modern"], voices: ["Engaging", "Punchy"], audiences: ["Consumer", "SME", "Event"], industries: ["Healthcare", "Education", "Retail"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/white?text=Brochure", hero: "https://placehold.co/1200x630/7C3AED/white?text=Modern+Brochure", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 50, views: 160, selections: 22, previewsGenerated: 60, conversions: 8,
  },

  // ── Flyer ─────────────────────────────────────────────────────────────────────
  {
    templateCode: "FLY-BOL-001",
    name: "Flyer Bold Event",
    description: "High-impact event flyer with large typography and vibrant color blocks.",
    category: "Flyer",
    style: "Bold",
    industry: "Education",
    colorTheme: { primary: "#EA580C", secondary: "#C2410C", accent: "#FBBF24", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto", style: "display" },
    layout: "single-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Bold", "Energetic", "Attention-grabbing"], voices: ["Direct", "Punchy"], audiences: ["Youth", "Consumer", "Event-goers"], industries: ["Education", "F&B", "Retail"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EA580C/white?text=Bold+Flyer", hero: "https://placehold.co/1200x630/EA580C/white?text=Event+Flyer", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 60, views: 140, selections: 20, previewsGenerated: 55, conversions: 7,
  },

  // ── Presentation ──────────────────────────────────────────────────────────────
  {
    templateCode: "PRES-COR-001",
    name: "Presentation Corporate Annual",
    description: "Annual presentation template with data visualization, charts, and KPI dashboards.",
    category: "Presentation",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Calibri", body: "Calibri", style: "sans-serif" },
    layout: "widescreen",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Data-driven", "Professional", "Analytical"], voices: ["Analytical", "Precise"], audiences: ["Board", "Executive", "Analyst"], industries: ["Finance", "Trading", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Presentation", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Corporate+Presentation", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 70, views: 310, selections: 44, previewsGenerated: 120, conversions: 18,
  },

  // ── Social Media ──────────────────────────────────────────────────────────────
  {
    templateCode: "SM-MOD-001",
    name: "Social Media Pack Modern",
    description: "Complete social media kit: feed posts, stories, highlights, and cover photos.",
    category: "Social Media",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#EC4899", secondary: "#BE185D", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "social",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Vibrant", "Social", "Engaging"], voices: ["Casual", "Friendly"], audiences: ["Consumer", "Youth", "Social-active"], industries: ["F&B", "Retail", "Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EC4899/white?text=Social+Media", hero: "https://placehold.co/1200x630/EC4899/white?text=Social+Media+Pack", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 80, views: 480, selections: 68, previewsGenerated: 195, conversions: 29,
  },
  {
    templateCode: "SM-MIN-002",
    name: "Social Media Pack Minimalist",
    description: "Clean, white-space-driven social media templates for premium brands.",
    category: "Social Media",
    style: "Minimalist",
    industry: null,
    colorTheme: { primary: "#111827", secondary: "#374151", accent: "#6366F1", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "DM Sans", body: "DM Sans", style: "sans-serif" },
    layout: "social",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Minimal", "Premium", "Clean"], voices: ["Confident", "Understated"], audiences: ["HNW", "Design-conscious", "Professional"], industries: ["Property", "Finance", "Legal"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/111827/white?text=Minimal+SM", hero: "https://placehold.co/1200x630/111827/white?text=Minimal+Social", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 81, views: 260, selections: 35, previewsGenerated: 95, conversions: 14,
  },

  // ── Banner ────────────────────────────────────────────────────────────────────
  {
    templateCode: "BAN-BOL-001",
    name: "Banner Digital Bold",
    description: "Digital banner suite: leaderboard, rectangle, skyscraper, and mobile banner formats.",
    category: "Banner",
    style: "Bold",
    industry: "Retail",
    colorTheme: { primary: "#16A34A", secondary: "#15803D", accent: "#FBBF24", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Roboto", style: "sans-serif" },
    layout: "banner",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Bold", "Commercial", "Promotional"], voices: ["Direct", "Action-oriented"], audiences: ["Consumer", "Shopper", "Online"], industries: ["Retail", "F&B", "Trading"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/16A34A/white?text=Banner", hero: "https://placehold.co/1200x630/16A34A/white?text=Digital+Banner", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 90, views: 195, selections: 28, previewsGenerated: 70, conversions: 11,
  },

  // ── Business Card ─────────────────────────────────────────────────────────────
  {
    templateCode: "BC-ELG-001",
    name: "Business Card Elegant Premium",
    description: "Premium business card with foil-stamping simulation, embossed logo area, and QR code.",
    category: "Business Card",
    style: "Elegant",
    industry: null,
    colorTheme: { primary: "#1C1917", secondary: "#292524", accent: "#D4AF37", background: "#1C1917", text: "#FFFFFF" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "business-card",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Prestigious", "Luxury", "Executive"], voices: ["Refined", "Formal"], audiences: ["Executive", "HNW", "Partner"], industries: ["Legal", "Finance", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1C1917/D4AF37?text=Business+Card", hero: "https://placehold.co/1200x630/1C1917/D4AF37?text=Premium+Business+Card", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 100, views: 390, selections: 55, previewsGenerated: 140, conversions: 24,
  },
  {
    templateCode: "BC-MOD-002",
    name: "Business Card Modern Tech",
    description: "Tech-forward business card with gradient and minimal personal info layout.",
    category: "Business Card",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#4F46E5", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "business-card",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Innovative", "Modern", "Tech-forward"], voices: ["Confident", "Direct"], audiences: ["Tech", "Startup", "Digital"], industries: ["Technology", "Startup", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/white?text=Tech+Card", hero: "https://placehold.co/1200x630/6366F1/white?text=Tech+Business+Card", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 101, views: 220, selections: 32, previewsGenerated: 80, conversions: 13,
  },

  // ── Letterhead ────────────────────────────────────────────────────────────────
  {
    templateCode: "LH-COR-001",
    name: "Letterhead Corporate Standard",
    description: "A4 letterhead with header/footer branding, watermark, and clean typography.",
    category: "Letterhead",
    style: "Corporate",
    industry: null,
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#C9A84C", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Arial", body: "Arial", style: "sans-serif" },
    layout: "letterhead",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Formal", "Professional", "Trustworthy"], voices: ["Formal", "Authoritative"], audiences: ["Corporate", "Legal", "Government"], industries: ["Legal", "Finance", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Letterhead", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Corporate+Letterhead", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 110, views: 145, selections: 22, previewsGenerated: 55, conversions: 9,
  },

  // ── Email Signature ───────────────────────────────────────────────────────────
  {
    templateCode: "ES-PRO-001",
    name: "Email Signature Professional",
    description: "HTML email signature with logo, contact details, social links, and CTA button.",
    category: "Email Signature",
    style: "Professional",
    industry: null,
    colorTheme: { primary: "#2563EB", secondary: "#1D4ED8", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Arial", body: "Arial", style: "sans-serif" },
    layout: "email-sig",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Trustworthy", "Modern"], voices: ["Formal", "Friendly"], audiences: ["B2B", "Corporate", "SME"], industries: ["Technology", "Finance", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/2563EB/white?text=Email+Sig", hero: "https://placehold.co/1200x630/2563EB/white?text=Email+Signature", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 120, views: 210, selections: 30, previewsGenerated: 80, conversions: 12,
  },

  // ── Website Hero ──────────────────────────────────────────────────────────────
  {
    templateCode: "WH-MOD-001",
    name: "Website Hero Modern SaaS",
    description: "SaaS website hero section with headline, subtext, CTA buttons, and dashboard mockup.",
    category: "Website Hero",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#4F46E5", accent: "#F59E0B", background: "#0F172A", text: "#F9FAFB" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "hero",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Innovative", "Tech-forward", "Bold"], voices: ["Confident", "Visionary"], audiences: ["Startup", "Tech", "SaaS buyers"], industries: ["Technology", "SaaS", "Startup"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/white?text=Website+Hero", hero: "https://placehold.co/1200x630/6366F1/white?text=SaaS+Hero+Section", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 130, views: 290, selections: 42, previewsGenerated: 110, conversions: 17,
  },

  // ── Landing Page ──────────────────────────────────────────────────────────────
  {
    templateCode: "LP-MOD-001",
    name: "Landing Page Product Launch",
    description: "Conversion-optimized product launch landing page with above-fold hero, features, testimonials, and CTA.",
    category: "Landing Page",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#5B21B6", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "landing",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Dynamic", "Conversion-focused", "Modern"], voices: ["Persuasive", "Action-oriented"], audiences: ["Consumer", "Lead", "Prospect"], industries: ["Technology", "Retail", "Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/white?text=Landing+Page", hero: "https://placehold.co/1200x630/7C3AED/white?text=Product+Landing+Page", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 140, views: 350, selections: 50, previewsGenerated: 135, conversions: 20,
  },

  // ── Packaging ─────────────────────────────────────────────────────────────────
  {
    templateCode: "PKG-ELG-001",
    name: "Packaging Premium Food & Beverage",
    description: "Premium F&B packaging design with label, box, and bag variants. Eco-friendly version included.",
    category: "Packaging",
    style: "Elegant",
    industry: "F&B",
    colorTheme: { primary: "#4C1D13", secondary: "#7C2D12", accent: "#D97706", background: "#FEF3C7", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lora", style: "serif" },
    layout: "packaging",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Artisan", "Premium", "Natural"], voices: ["Sensory", "Storytelling"], audiences: ["Premium", "Eco-conscious", "Foodie"], industries: ["F&B", "Retail", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/4C1D13/white?text=Packaging", hero: "https://placehold.co/1200x630/4C1D13/white?text=F%26B+Packaging", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 150, views: 260, selections: 37, previewsGenerated: 95, conversions: 16,
  },
  {
    templateCode: "PKG-MOD-002",
    name: "Packaging Modern Industrial",
    description: "Bold industrial packaging for hardware, tools, and manufacturing products.",
    category: "Packaging",
    style: "Bold",
    industry: "Manufacturing",
    colorTheme: { primary: "#B91C1C", secondary: "#991B1B", accent: "#FCD34D", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto Condensed", style: "display" },
    layout: "packaging",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Industrial", "Reliable", "Strong"], voices: ["Direct", "Technical"], audiences: ["B2B", "Industrial", "Contractor"], industries: ["Manufacturing", "Construction", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B91C1C/white?text=Industrial+Pkg", hero: "https://placehold.co/1200x630/B91C1C/white?text=Industrial+Packaging", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 151, views: 145, selections: 20, previewsGenerated: 50, conversions: 8,
  },

  // ── Infographic ───────────────────────────────────────────────────────────────
  {
    templateCode: "INFO-MOD-001",
    name: "Infographic Modern Data Story",
    description: "Data-driven infographic with charts, timelines, and process flows. Editable in Canva.",
    category: "Infographic",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "infographic",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Data-driven", "Educational", "Clear"], voices: ["Informative", "Visual"], audiences: ["B2B", "Corporate", "Media"], industries: ["Technology", "Healthcare", "Finance"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/white?text=Infographic", hero: "https://placehold.co/1200x630/0891B2/white?text=Data+Infographic", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 160, views: 185, selections: 26, previewsGenerated: 70, conversions: 10,
  },

  // ── Whitepaper ────────────────────────────────────────────────────────────────
  {
    templateCode: "WP-PRO-001",
    name: "Whitepaper Professional",
    description: "Academic-style whitepaper with abstract, executive summary, research sections, and bibliography.",
    category: "Whitepaper",
    style: "Professional",
    industry: "Technology",
    colorTheme: { primary: "#1E40AF", secondary: "#1D4ED8", accent: "#7C3AED", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Georgia", body: "Times New Roman", style: "serif" },
    layout: "document",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Academic", "Authoritative", "Research-driven"], voices: ["Expert", "Formal"], audiences: ["Enterprise", "Academic", "Policy-maker"], industries: ["Technology", "Healthcare", "Finance"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E40AF/white?text=Whitepaper", hero: "https://placehold.co/1200x630/1E40AF/white?text=Professional+Whitepaper", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 170, views: 120, selections: 18, previewsGenerated: 45, conversions: 7,
  },

  // ── Case Study ────────────────────────────────────────────────────────────────
  {
    templateCode: "CS-MOD-001",
    name: "Case Study Modern Impact",
    description: "Client success case study with challenge/solution/result structure and testimonial highlight.",
    category: "Case Study",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#059669", secondary: "#047857", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "single-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Results-driven", "Trustworthy", "Proof-based"], voices: ["Evidence-based", "Confident"], audiences: ["B2B", "Decision-maker", "Executive"], industries: ["Consulting", "Technology", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/059669/white?text=Case+Study", hero: "https://placehold.co/1200x630/059669/white?text=Case+Study", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 180, views: 155, selections: 22, previewsGenerated: 60, conversions: 9,
  },

  // ── Annual Report ─────────────────────────────────────────────────────────────
  {
    templateCode: "AR-COR-001",
    name: "Annual Report Corporate",
    description: "Full annual report with chairman's letter, financials, KPIs, ESG section, and photo essay.",
    category: "Annual Report",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Calibri", body: "Arial", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Corporate", "Transparent", "Data-driven"], voices: ["Formal", "Comprehensive"], audiences: ["Shareholders", "Regulator", "Investor"], industries: ["Finance", "Manufacturing", "Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Annual+Report", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Annual+Report", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 190, views: 200, selections: 28, previewsGenerated: 75, conversions: 11,
  },
  {
    templateCode: "AR-MOD-002",
    name: "Annual Report Modern Impact",
    description: "Modern annual report with infographic-heavy sections, data stories, and visual timelines.",
    category: "Annual Report",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#5B21B6", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Modern", "Impact-driven", "Innovative"], voices: ["Confident", "Visionary"], audiences: ["Stakeholder", "Media", "Investor"], industries: ["Technology", "Logistics", "Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/white?text=Modern+AR", hero: "https://placehold.co/1200x630/7C3AED/white?text=Modern+Annual+Report", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 191, views: 165, selections: 24, previewsGenerated: 65, conversions: 10,
  },

  // ── Healthcare-specific ───────────────────────────────────────────────────────
  {
    templateCode: "HC-CP-001",
    name: "Healthcare Company Profile",
    description: "Trust-first healthcare company profile with services, team credentials, and accreditations.",
    category: "Company Profile",
    style: "Professional",
    industry: "Healthcare",
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#10B981", background: "#F0F9FF", text: "#0C4A6E" },
    typography: { heading: "Nunito Sans", body: "Open Sans", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Trustworthy", "Caring", "Professional"], voices: ["Empathetic", "Authoritative"], audiences: ["Patient", "Physician", "Insurance"], industries: ["Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/white?text=Healthcare+CP", hero: "https://placehold.co/1200x630/0891B2/white?text=Healthcare+Profile", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 5, views: 280, selections: 40, previewsGenerated: 100, conversions: 16,
  },

  // ── Logistics ─────────────────────────────────────────────────────────────────
  {
    templateCode: "LOG-CP-001",
    name: "Logistics Company Profile Bold",
    description: "Bold, map-integrated logistics company profile with route coverage, fleet specs, and SLA commitments.",
    category: "Company Profile",
    style: "Bold",
    industry: "Logistics",
    colorTheme: { primary: "#EA580C", secondary: "#C2410C", accent: "#FCD34D", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto", style: "display" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Reliable", "Efficient", "Bold"], voices: ["Direct", "Technical"], audiences: ["B2B", "Operations", "Procurement"], industries: ["Logistics", "Manufacturing", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EA580C/white?text=Logistics+CP", hero: "https://placehold.co/1200x630/EA580C/white?text=Logistics+Profile", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 6, views: 195, selections: 28, previewsGenerated: 75, conversions: 12,
  },

  // ── Construction ──────────────────────────────────────────────────────────────
  {
    templateCode: "CON-CP-001",
    name: "Construction Corporate Profile",
    description: "Heavyweight construction corporate profile with project portfolio, certifications, and capability statement.",
    category: "Corporate Profile",
    style: "Corporate",
    industry: "Construction",
    colorTheme: { primary: "#B45309", secondary: "#92400E", accent: "#FBBF24", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Montserrat Bold", body: "Roboto", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Strong", "Reliable", "Professional"], voices: ["Confident", "Technical"], audiences: ["Developer", "Government", "Investor"], industries: ["Construction", "Property", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/white?text=Construction+CP", hero: "https://placehold.co/1200x630/B45309/white?text=Construction+Profile", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 45, views: 230, selections: 33, previewsGenerated: 85, conversions: 14,
  },

  // ── Export / Trade ────────────────────────────────────────────────────────────
  {
    templateCode: "EXP-CAT-001",
    name: "Export Product Catalog",
    description: "Bilingual export product catalog (ID/EN) with HS codes, MOQ, shipping, and certification seals.",
    category: "Product Catalog",
    style: "Professional",
    industry: "Export",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#DC2626", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "grid",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Professional", "Global", "Trustworthy"], voices: ["Formal", "Technical"], audiences: ["International buyer", "Importer", "Distributor"], industries: ["Export", "Manufacturing", "F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/white?text=Export+Catalog", hero: "https://placehold.co/1200x630/1D4ED8/white?text=Export+Catalog", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 35, views: 260, selections: 37, previewsGenerated: 95, conversions: 15,
  },

  // ── Education ─────────────────────────────────────────────────────────────────
  {
    templateCode: "EDU-BR-001",
    name: "Education Brochure Modern",
    description: "Modern school/university brochure with programs, facilities, and student life sections.",
    category: "Brochure",
    style: "Modern",
    industry: "Education",
    colorTheme: { primary: "#2563EB", secondary: "#1D4ED8", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Open Sans", style: "sans-serif" },
    layout: "tri-fold",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Educational", "Inspiring", "Trustworthy"], voices: ["Encouraging", "Clear"], audiences: ["Student", "Parent", "Institution"], industries: ["Education"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/2563EB/white?text=Education+Brochure", hero: "https://placehold.co/1200x630/2563EB/white?text=Education+Brochure", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 55, views: 175, selections: 25, previewsGenerated: 65, conversions: 9,
  },

  // ── Property ──────────────────────────────────────────────────────────────────
  {
    templateCode: "PROP-CAT-001",
    name: "Property Catalog Luxury",
    description: "Luxury property catalog with floor plans, amenities showcase, and investment ROI section.",
    category: "Product Catalog",
    style: "Elegant",
    industry: "Property",
    colorTheme: { primary: "#1E3A5F", secondary: "#2E6DA4", accent: "#D4AF37", background: "#FAFAFA", text: "#1A1A1A" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Prestigious", "Luxury", "Premium"], voices: ["Refined", "Aspirational"], audiences: ["HNW", "Investor", "Property buyer"], industries: ["Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/D4AF37?text=Property+Catalog", hero: "https://placehold.co/1200x630/1E3A5F/D4AF37?text=Property+Catalog", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 38, views: 310, selections: 44, previewsGenerated: 110, conversions: 19,
  },

  // ── Finance ───────────────────────────────────────────────────────────────────
  {
    templateCode: "FIN-WP-001",
    name: "Finance Whitepaper Investment",
    description: "Investment whitepaper with market analysis, risk factors, and performance projections.",
    category: "Whitepaper",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#0F172A", secondary: "#1E293B", accent: "#2563EB", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Merriweather", body: "Source Serif Pro", style: "serif" },
    layout: "document",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Conservative", "Analytical", "Trustworthy"], voices: ["Expert", "Formal"], audiences: ["Investor", "Regulator", "HNW"], industries: ["Finance", "Trading"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F172A/white?text=Finance+WP", hero: "https://placehold.co/1200x630/0F172A/white?text=Investment+Whitepaper", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: false, sortOrder: 175, views: 140, selections: 20, previewsGenerated: 55, conversions: 8,
  },

  // ── F&B Social Media ──────────────────────────────────────────────────────────
  {
    templateCode: "FNB-SM-001",
    name: "F&B Social Media Food Photography Pack",
    description: "Food photography social media kit with feed templates, story layouts, and menu card posts.",
    category: "Social Media",
    style: "Creative",
    industry: "F&B",
    colorTheme: { primary: "#B45309", secondary: "#78350F", accent: "#FCD34D", background: "#FFF7ED", text: "#1C1917" },
    typography: { heading: "Abril Fatface", body: "Nunito", style: "display" },
    layout: "social",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Artisan", "Vibrant", "Sensory"], voices: ["Warm", "Appetizing"], audiences: ["Foodie", "Consumer", "Local"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/white?text=F%26B+Social", hero: "https://placehold.co/1200x630/B45309/white?text=F%26B+Social+Media", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 85, views: 420, selections: 60, previewsGenerated: 170, conversions: 26,
  },

  // ── Retail ────────────────────────────────────────────────────────────────────
  {
    templateCode: "RET-LP-001",
    name: "Retail Landing Page Promo",
    description: "Promotional retail landing page with countdown timer, product grid, and urgency CTA.",
    category: "Landing Page",
    style: "Bold",
    industry: "Retail",
    colorTheme: { primary: "#DC2626", secondary: "#991B1B", accent: "#FCD34D", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Roboto", style: "sans-serif" },
    layout: "landing",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Promotional", "Urgency-driven", "Commercial"], voices: ["Persuasive", "Punchy"], audiences: ["Consumer", "Shopper", "Deal-seeker"], industries: ["Retail", "Trading"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/DC2626/white?text=Retail+LP", hero: "https://placehold.co/1200x630/DC2626/white?text=Retail+Landing+Page", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 145, views: 285, selections: 40, previewsGenerated: 105, conversions: 16,
  },

  // ── Trading ───────────────────────────────────────────────────────────────────
  {
    templateCode: "TRD-CP-001",
    name: "Trading Company Profile Professional",
    description: "B2B trading company profile with commodity catalog, global reach map, and partner logos.",
    category: "Company Profile",
    style: "Professional",
    industry: "Trading",
    colorTheme: { primary: "#0F766E", secondary: "#134E4A", accent: "#D97706", background: "#FFFFFF", text: "#1C1917" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Reliable", "Global", "Professional"], voices: ["Formal", "Trustworthy"], audiences: ["B2B", "Importer", "Distributor"], industries: ["Trading", "Export", "Logistics"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F766E/white?text=Trading+CP", hero: "https://placehold.co/1200x630/0F766E/white?text=Trading+Profile", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 7, views: 210, selections: 30, previewsGenerated: 80, conversions: 12,
  },
];

async function seedTemplates() {
  console.log(`🌱 Seeding ${TEMPLATES.length} templates…`);

  for (const template of TEMPLATES) {
    await db
      .insert(aiTemplatesTable)
      .values(template)
      .onConflictDoUpdate({
        target: aiTemplatesTable.templateCode,
        set: {
          name: template.name,
          description: template.description,
          style: template.style,
          industry: template.industry ?? null,
          colorTheme: template.colorTheme ?? null,
          typography: template.typography ?? null,
          layout: template.layout ?? null,
          supportedPackages: template.supportedPackages ?? null,
          brandDnaTags: template.brandDnaTags ?? null,
          previewImages: template.previewImages ?? null,
          featured: template.featured,
          status: template.status,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`✅ Seeded ${TEMPLATES.length} templates across 20 categories`);
}

seedTemplates().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
