/**
 * Seed V4.3 Template Library — 60 templates across 20 categories and 13 industries.
 * Idempotent (uses onConflictDoUpdate).
 * Run: pnpm seed:templates
 */
import { db, aiTemplatesTable } from "@workspace/db";

const STYLES = ["Modern", "Classic", "Minimalist", "Bold", "Elegant", "Professional", "Creative", "Corporate"];
const PACKAGES = ["starter", "standard", "professional", "enterprise"];

type TemplateRow = typeof aiTemplatesTable.$inferInsert;

const TEMPLATES: Omit<TemplateRow, "createdAt" | "updatedAt">[] = [
  // ── Company Profile ──────────────────────────────────────────────────────────
  {
    templateCode: "CP-MOD-001",
    name: "Company Profile Modern",
    description: "Sleek modern company profile with bold typography and clean sections. Ideal for tech and fintech brands.",
    category: "Company Profile",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#8B5CF6", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Innovative", "Modern"], voices: ["Authoritative", "Formal"], audiences: ["B2B", "Enterprise", "Corporate"], industries: ["Technology", "Finance", "Startup"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/white?text=Modern+CP", hero: "https://placehold.co/1200x630/6366F1/white?text=Company+Profile+Modern", gallery: ["https://placehold.co/800x600/6366F1/white?text=Page+1", "https://placehold.co/800x600/8B5CF6/white?text=Page+2"] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 1, views: 340, selections: 45, previewsGenerated: 120, conversions: 18,
  },
  {
    templateCode: "CP-CLS-002",
    name: "Company Profile Classic",
    description: "Timeless classic design with serif typography and structured layout. Perfect for law firms, consulting, and finance.",
    category: "Company Profile",
    style: "Classic",
    industry: "Legal",
    colorTheme: { primary: "#1E3A5F", secondary: "#2E6DA4", accent: "#C9A84C", background: "#FAFAFA", text: "#1A1A1A" },
    typography: { heading: "Georgia", body: "Times New Roman", style: "serif" },
    layout: "single-column",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Trustworthy", "Professional", "Prestigious"], voices: ["Formal", "Authoritative"], audiences: ["Corporate", "Legal", "HNW"], industries: ["Legal", "Finance", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Classic+CP", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Company+Profile+Classic", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 2, views: 280, selections: 38, previewsGenerated: 95, conversions: 15,
  },
  {
    templateCode: "CP-MIN-003",
    name: "Company Profile Minimalist",
    description: "White space-driven minimalist design. Communicates sophistication through restraint.",
    category: "Company Profile",
    style: "Minimalist",
    industry: null,
    colorTheme: { primary: "#111827", secondary: "#374151", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "DM Sans", body: "DM Sans", style: "sans-serif" },
    layout: "single-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Modern", "Clean", "Premium"], voices: ["Confident", "Direct"], audiences: ["SME", "Design-conscious", "Startup"], industries: ["Technology", "Design", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/111827/white?text=Minimal+CP", hero: "https://placehold.co/1200x630/111827/white?text=Minimalist+CP", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 3, views: 195, selections: 28, previewsGenerated: 80, conversions: 10,
  },

  // ── Pitch Deck ────────────────────────────────────────────────────────────────
  {
    templateCode: "PD-MOD-001",
    name: "Pitch Deck Modern Startup",
    description: "Investor-grade pitch deck with problem/solution/traction narrative. Dark mode available.",
    category: "Pitch Deck",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6D28D9", secondary: "#4C1D95", accent: "#F59E0B", background: "#0F0A1E", text: "#F9FAFB" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "presentation",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Innovative", "Bold", "Disruptive"], voices: ["Confident", "Visionary"], audiences: ["Investors", "VC", "Startup"], industries: ["Technology", "Startup", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6D28D9/white?text=Pitch+Deck", hero: "https://placehold.co/1200x630/6D28D9/white?text=Startup+Pitch+Deck", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 10, views: 510, selections: 72, previewsGenerated: 180, conversions: 32,
  },
  {
    templateCode: "PD-COR-002",
    name: "Pitch Deck Corporate",
    description: "Structured corporate pitch with executive summary, market analysis, and financial projections.",
    category: "Pitch Deck",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#1E40AF", secondary: "#1D4ED8", accent: "#FBBF24", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Calibri", body: "Arial", style: "sans-serif" },
    layout: "presentation",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Professional", "Trustworthy", "Data-driven"], voices: ["Analytical", "Formal"], audiences: ["Corporate", "Investors", "Board"], industries: ["Finance", "Manufacturing", "Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E40AF/white?text=Corp+Pitch", hero: "https://placehold.co/1200x630/1E40AF/white?text=Corporate+Pitch+Deck", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 11, views: 380, selections: 55, previewsGenerated: 140, conversions: 22,
  },

  // ── Proposal ──────────────────────────────────────────────────────────────────
  {
    templateCode: "PROP-PRO-001",
    name: "Business Proposal Professional",
    description: "Comprehensive business proposal with executive summary, scope, timeline, and pricing table.",
    category: "Proposal",
    style: "Professional",
    industry: null,
    colorTheme: { primary: "#0F766E", secondary: "#134E4A", accent: "#F59E0B", background: "#FFFFFF", text: "#1C1917" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Trustworthy", "Competent"], voices: ["Persuasive", "Clear"], audiences: ["Corporate", "SME", "Government"], industries: ["Consulting", "Construction", "Technology"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F766E/white?text=Proposal", hero: "https://placehold.co/1200x630/0F766E/white?text=Business+Proposal", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 20, views: 290, selections: 42, previewsGenerated: 110, conversions: 19,
  },

  // ── Product Catalog ───────────────────────────────────────────────────────────
  {
    templateCode: "CAT-MOD-001",
    name: "Product Catalog Modern Grid",
    description: "Grid-based product catalog with high-impact photography layout and pricing tables.",
    category: "Product Catalog",
    style: "Modern",
    industry: "Retail",
    colorTheme: { primary: "#DC2626", secondary: "#991B1B", accent: "#F97316", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Roboto", style: "sans-serif" },
    layout: "grid",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Dynamic", "Bold", "Commercial"], voices: ["Engaging", "Persuasive"], audiences: ["Consumer", "Retail", "B2C"], industries: ["Retail", "F&B", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/DC2626/white?text=Product+Catalog", hero: "https://placehold.co/1200x630/DC2626/white?text=Product+Catalog", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 30, views: 220, selections: 30, previewsGenerated: 75, conversions: 12,
  },
  {
    templateCode: "CAT-ELG-002",
    name: "Product Catalog Elegant",
    description: "Luxury product catalog with magazine-style layout. Ideal for premium goods and F&B.",
    category: "Product Catalog",
    style: "Elegant",
    industry: "F&B",
    colorTheme: { primary: "#78350F", secondary: "#92400E", accent: "#D97706", background: "#FFFBEB", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lora", style: "serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Luxury", "Premium", "Artisan"], voices: ["Refined", "Sensory"], audiences: ["Premium", "HNW", "Connoisseur"], industries: ["F&B", "Property", "Retail"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/78350F/white?text=Elegant+Catalog", hero: "https://placehold.co/1200x630/78350F/white?text=Elegant+Catalog", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 31, views: 175, selections: 25, previewsGenerated: 65, conversions: 9,
  },

  // ── Corporate Profile ─────────────────────────────────────────────────────────
  {
    templateCode: "CORP-PRO-001",
    name: "Corporate Profile Enterprise",
    description: "Full enterprise corporate profile: org chart, leadership, CSR, financials, and global presence.",
    category: "Corporate Profile",
    style: "Corporate",
    industry: "Manufacturing",
    colorTheme: { primary: "#1F2937", secondary: "#374151", accent: "#2563EB", background: "#F9FAFB", text: "#111827" },
    typography: { heading: "Arial Bold", body: "Arial", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Corporate", "Trustworthy", "Established"], voices: ["Authoritative", "Formal"], audiences: ["Enterprise", "Investors", "Government"], industries: ["Manufacturing", "Export", "Construction"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1F2937/white?text=Corp+Profile", hero: "https://placehold.co/1200x630/1F2937/white?text=Corporate+Profile", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 40, views: 430, selections: 62, previewsGenerated: 155, conversions: 27,
  },

  // ── Brochure ──────────────────────────────────────────────────────────────────
  {
    templateCode: "BRO-MOD-001",
    name: "Brochure Modern Tri-fold",
    description: "Tri-fold brochure with bold color blocks and infographic elements.",
    category: "Brochure",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#5B21B6", accent: "#EC4899", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Open Sans", style: "sans-serif" },
    layout: "tri-fold",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Dynamic", "Vibrant", "Modern"], voices: ["Engaging", "Punchy"], audiences: ["Consumer", "SME", "Event"], industries: ["Healthcare", "Education", "Retail"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/white?text=Brochure", hero: "https://placehold.co/1200x630/7C3AED/white?text=Modern+Brochure", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 50, views: 160, selections: 22, previewsGenerated: 60, conversions: 8,
  },

  // ── Flyer ─────────────────────────────────────────────────────────────────────
  {
    templateCode: "FLY-BOL-001",
    name: "Flyer Bold Event",
    description: "High-impact event flyer with large typography and vibrant color blocks.",
    category: "Flyer",
    style: "Bold",
    industry: "Education",
    colorTheme: { primary: "#EA580C", secondary: "#C2410C", accent: "#FBBF24", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto", style: "display" },
    layout: "single-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Bold", "Energetic", "Attention-grabbing"], voices: ["Direct", "Punchy"], audiences: ["Youth", "Consumer", "Event-goers"], industries: ["Education", "F&B", "Retail"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EA580C/white?text=Bold+Flyer", hero: "https://placehold.co/1200x630/EA580C/white?text=Event+Flyer", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 60, views: 140, selections: 20, previewsGenerated: 55, conversions: 7,
  },

  // ── Presentation ──────────────────────────────────────────────────────────────
  {
    templateCode: "PRES-COR-001",
    name: "Presentation Corporate Annual",
    description: "Annual presentation template with data visualization, charts, and KPI dashboards.",
    category: "Presentation",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Calibri", body: "Calibri", style: "sans-serif" },
    layout: "widescreen",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Data-driven", "Professional", "Analytical"], voices: ["Analytical", "Precise"], audiences: ["Board", "Executive", "Analyst"], industries: ["Finance", "Trading", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Presentation", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Corporate+Presentation", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 70, views: 310, selections: 44, previewsGenerated: 120, conversions: 18,
  },

  // ── Social Media ──────────────────────────────────────────────────────────────
  {
    templateCode: "SM-MOD-001",
    name: "Social Media Pack Modern",
    description: "Complete social media kit: feed posts, stories, highlights, and cover photos.",
    category: "Social Media",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#EC4899", secondary: "#BE185D", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "social",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Vibrant", "Social", "Engaging"], voices: ["Casual", "Friendly"], audiences: ["Consumer", "Youth", "Social-active"], industries: ["F&B", "Retail", "Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EC4899/white?text=Social+Media", hero: "https://placehold.co/1200x630/EC4899/white?text=Social+Media+Pack", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 80, views: 480, selections: 68, previewsGenerated: 195, conversions: 29,
  },
  {
    templateCode: "SM-MIN-002",
    name: "Social Media Pack Minimalist",
    description: "Clean, white-space-driven social media templates for premium brands.",
    category: "Social Media",
    style: "Minimalist",
    industry: null,
    colorTheme: { primary: "#111827", secondary: "#374151", accent: "#6366F1", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "DM Sans", body: "DM Sans", style: "sans-serif" },
    layout: "social",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Minimal", "Premium", "Clean"], voices: ["Confident", "Understated"], audiences: ["HNW", "Design-conscious", "Professional"], industries: ["Property", "Finance", "Legal"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/111827/white?text=Minimal+SM", hero: "https://placehold.co/1200x630/111827/white?text=Minimal+Social", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 81, views: 260, selections: 35, previewsGenerated: 95, conversions: 14,
  },

  // ── Banner ────────────────────────────────────────────────────────────────────
  {
    templateCode: "BAN-BOL-001",
    name: "Banner Digital Bold",
    description: "Digital banner suite: leaderboard, rectangle, skyscraper, and mobile banner formats.",
    category: "Banner",
    style: "Bold",
    industry: "Retail",
    colorTheme: { primary: "#16A34A", secondary: "#15803D", accent: "#FBBF24", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Roboto", style: "sans-serif" },
    layout: "banner",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Bold", "Commercial", "Promotional"], voices: ["Direct", "Action-oriented"], audiences: ["Consumer", "Shopper", "Online"], industries: ["Retail", "F&B", "Trading"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/16A34A/white?text=Banner", hero: "https://placehold.co/1200x630/16A34A/white?text=Digital+Banner", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 90, views: 195, selections: 28, previewsGenerated: 70, conversions: 11,
  },

  // ── Business Card ─────────────────────────────────────────────────────────────
  {
    templateCode: "BC-FNB-003",
    name: "Business Card F&B Warm",
    description: "Warm earthy tones for restaurant, café, and culinary brand business cards.",
    category: "Business Card",
    style: "Modern",
    industry: "F&B",
    colorTheme: { primary: "#7C2D12", secondary: "#9A3412", accent: "#F59E0B", background: "#FFF7ED", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lato", style: "mixed" },
    layout: "business-card",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Warm", "Inviting", "Artisan"], voices: ["Friendly", "Passionate"], audiences: ["Food Lover", "Local", "Dining"], industries: ["F&B", "Restaurant", "Café", "Catering"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C2D12/F59E0B?text=F%26B+Card", hero: "https://placehold.co/1200x630/7C2D12/F59E0B?text=F%26B+Business+Card", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 102, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "BC-MIN-004",
    name: "Business Card Minimalist White",
    description: "Ultra-clean white business card with subtle line accents. Works for any industry.",
    category: "Business Card",
    style: "Minimalist",
    industry: null,
    colorTheme: { primary: "#111827", secondary: "#374151", accent: "#6366F1", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Inter", body: "Inter", style: "sans-serif" },
    layout: "business-card",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Clean", "Modern", "Simple"], voices: ["Direct", "Clear"], audiences: ["Professional", "Freelancer", "Consultant"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/111827/6366F1?text=Minimal+Card", hero: "https://placehold.co/1200x630/111827/6366F1?text=Minimalist+Card", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 103, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "BC-ELG-001",
    name: "Business Card Elegant Premium",
    description: "Premium business card with foil-stamping simulation, embossed logo area, and QR code.",
    category: "Business Card",
    style: "Elegant",
    industry: null,
    colorTheme: { primary: "#1C1917", secondary: "#292524", accent: "#D4AF37", background: "#1C1917", text: "#FFFFFF" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "business-card",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Prestigious", "Luxury", "Executive"], voices: ["Refined", "Formal"], audiences: ["Executive", "HNW", "Partner"], industries: ["Legal", "Finance", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1C1917/D4AF37?text=Business+Card", hero: "https://placehold.co/1200x630/1C1917/D4AF37?text=Premium+Business+Card", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 100, views: 390, selections: 55, previewsGenerated: 140, conversions: 24,
  },
  {
    templateCode: "BC-MOD-002",
    name: "Business Card Modern Tech",
    description: "Tech-forward business card with gradient and minimal personal info layout.",
    category: "Business Card",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#4F46E5", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "business-card",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Innovative", "Modern", "Tech-forward"], voices: ["Confident", "Direct"], audiences: ["Tech", "Startup", "Digital"], industries: ["Technology", "Startup", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/white?text=Tech+Card", hero: "https://placehold.co/1200x630/6366F1/white?text=Tech+Business+Card", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 101, views: 220, selections: 32, previewsGenerated: 80, conversions: 13,
  },

  // ── Letterhead ────────────────────────────────────────────────────────────────
  {
    templateCode: "LH-COR-001",
    name: "Letterhead Corporate Standard",
    description: "A4 letterhead with header/footer branding, watermark, and clean typography.",
    category: "Letterhead",
    style: "Corporate",
    industry: null,
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#C9A84C", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Arial", body: "Arial", style: "sans-serif" },
    layout: "letterhead",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Formal", "Professional", "Trustworthy"], voices: ["Formal", "Authoritative"], audiences: ["Corporate", "Legal", "Government"], industries: ["Legal", "Finance", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Letterhead", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Corporate+Letterhead", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 110, views: 145, selections: 22, previewsGenerated: 55, conversions: 9,
  },

  // ── Email Signature ───────────────────────────────────────────────────────────
  {
    templateCode: "ES-PRO-001",
    name: "Email Signature Professional",
    description: "HTML email signature with logo, contact details, social links, and CTA button.",
    category: "Email Signature",
    style: "Professional",
    industry: null,
    colorTheme: { primary: "#2563EB", secondary: "#1D4ED8", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Arial", body: "Arial", style: "sans-serif" },
    layout: "email-sig",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Trustworthy", "Modern"], voices: ["Formal", "Friendly"], audiences: ["B2B", "Corporate", "SME"], industries: ["Technology", "Finance", "Consulting"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/2563EB/white?text=Email+Sig", hero: "https://placehold.co/1200x630/2563EB/white?text=Email+Signature", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 120, views: 210, selections: 30, previewsGenerated: 80, conversions: 12,
  },

  // ── Website Hero ──────────────────────────────────────────────────────────────
  {
    templateCode: "WH-MOD-001",
    name: "Website Hero Modern SaaS",
    description: "SaaS website hero section with headline, subtext, CTA buttons, and dashboard mockup.",
    category: "Website Hero",
    style: "Modern",
    industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#4F46E5", accent: "#F59E0B", background: "#0F172A", text: "#F9FAFB" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "hero",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Innovative", "Tech-forward", "Bold"], voices: ["Confident", "Visionary"], audiences: ["Startup", "Tech", "SaaS buyers"], industries: ["Technology", "SaaS", "Startup"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/white?text=Website+Hero", hero: "https://placehold.co/1200x630/6366F1/white?text=SaaS+Hero+Section", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 130, views: 290, selections: 42, previewsGenerated: 110, conversions: 17,
  },

  // ── Landing Page ──────────────────────────────────────────────────────────────
  {
    templateCode: "LP-MOD-001",
    name: "Landing Page Product Launch",
    description: "Conversion-optimized product launch landing page with above-fold hero, features, testimonials, and CTA.",
    category: "Landing Page",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#5B21B6", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "landing",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Dynamic", "Conversion-focused", "Modern"], voices: ["Persuasive", "Action-oriented"], audiences: ["Consumer", "Lead", "Prospect"], industries: ["Technology", "Retail", "Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/white?text=Landing+Page", hero: "https://placehold.co/1200x630/7C3AED/white?text=Product+Landing+Page", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 140, views: 350, selections: 50, previewsGenerated: 135, conversions: 20,
  },

  // ── Packaging ─────────────────────────────────────────────────────────────────
  {
    templateCode: "PKG-ELG-001",
    name: "Packaging Premium Food & Beverage",
    description: "Premium F&B packaging design with label, box, and bag variants. Eco-friendly version included.",
    category: "Packaging",
    style: "Elegant",
    industry: "F&B",
    colorTheme: { primary: "#4C1D13", secondary: "#7C2D12", accent: "#D97706", background: "#FEF3C7", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lora", style: "serif" },
    layout: "packaging",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Artisan", "Premium", "Natural"], voices: ["Sensory", "Storytelling"], audiences: ["Premium", "Eco-conscious", "Foodie"], industries: ["F&B", "Retail", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/4C1D13/white?text=Packaging", hero: "https://placehold.co/1200x630/4C1D13/white?text=F%26B+Packaging", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 150, views: 260, selections: 37, previewsGenerated: 95, conversions: 16,
  },
  {
    templateCode: "PKG-MOD-002",
    name: "Packaging Modern Industrial",
    description: "Bold industrial packaging for hardware, tools, and manufacturing products.",
    category: "Packaging",
    style: "Bold",
    industry: "Manufacturing",
    colorTheme: { primary: "#B91C1C", secondary: "#991B1B", accent: "#FCD34D", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto Condensed", style: "display" },
    layout: "packaging",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Industrial", "Reliable", "Strong"], voices: ["Direct", "Technical"], audiences: ["B2B", "Industrial", "Contractor"], industries: ["Manufacturing", "Construction", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B91C1C/white?text=Industrial+Pkg", hero: "https://placehold.co/1200x630/B91C1C/white?text=Industrial+Packaging", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 151, views: 145, selections: 20, previewsGenerated: 50, conversions: 8,
  },

  // ── Infographic ───────────────────────────────────────────────────────────────
  {
    templateCode: "INFO-MOD-001",
    name: "Infographic Modern Data Story",
    description: "Data-driven infographic with charts, timelines, and process flows. Editable in Canva.",
    category: "Infographic",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "infographic",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Data-driven", "Educational", "Clear"], voices: ["Informative", "Visual"], audiences: ["B2B", "Corporate", "Media"], industries: ["Technology", "Healthcare", "Finance"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/white?text=Infographic", hero: "https://placehold.co/1200x630/0891B2/white?text=Data+Infographic", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 160, views: 185, selections: 26, previewsGenerated: 70, conversions: 10,
  },

  // ── Whitepaper ────────────────────────────────────────────────────────────────
  {
    templateCode: "WP-PRO-001",
    name: "Whitepaper Professional",
    description: "Academic-style whitepaper with abstract, executive summary, research sections, and bibliography.",
    category: "Whitepaper",
    style: "Professional",
    industry: "Technology",
    colorTheme: { primary: "#1E40AF", secondary: "#1D4ED8", accent: "#7C3AED", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Georgia", body: "Times New Roman", style: "serif" },
    layout: "document",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Academic", "Authoritative", "Research-driven"], voices: ["Expert", "Formal"], audiences: ["Enterprise", "Academic", "Policy-maker"], industries: ["Technology", "Healthcare", "Finance"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E40AF/white?text=Whitepaper", hero: "https://placehold.co/1200x630/1E40AF/white?text=Professional+Whitepaper", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 170, views: 120, selections: 18, previewsGenerated: 45, conversions: 7,
  },

  // ── Case Study ────────────────────────────────────────────────────────────────
  {
    templateCode: "CS-MOD-001",
    name: "Case Study Modern Impact",
    description: "Client success case study with challenge/solution/result structure and testimonial highlight.",
    category: "Case Study",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#059669", secondary: "#047857", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "single-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Results-driven", "Trustworthy", "Proof-based"], voices: ["Evidence-based", "Confident"], audiences: ["B2B", "Decision-maker", "Executive"], industries: ["Consulting", "Technology", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/059669/white?text=Case+Study", hero: "https://placehold.co/1200x630/059669/white?text=Case+Study", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 180, views: 155, selections: 22, previewsGenerated: 60, conversions: 9,
  },

  // ── Annual Report ─────────────────────────────────────────────────────────────
  {
    templateCode: "AR-COR-001",
    name: "Annual Report Corporate",
    description: "Full annual report with chairman's letter, financials, KPIs, ESG section, and photo essay.",
    category: "Annual Report",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Calibri", body: "Arial", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Corporate", "Transparent", "Data-driven"], voices: ["Formal", "Comprehensive"], audiences: ["Shareholders", "Regulator", "Investor"], industries: ["Finance", "Manufacturing", "Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/white?text=Annual+Report", hero: "https://placehold.co/1200x630/1E3A5F/white?text=Annual+Report", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 190, views: 200, selections: 28, previewsGenerated: 75, conversions: 11,
  },
  {
    templateCode: "AR-MOD-002",
    name: "Annual Report Modern Impact",
    description: "Modern annual report with infographic-heavy sections, data stories, and visual timelines.",
    category: "Annual Report",
    style: "Modern",
    industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#5B21B6", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Modern", "Impact-driven", "Innovative"], voices: ["Confident", "Visionary"], audiences: ["Stakeholder", "Media", "Investor"], industries: ["Technology", "Logistics", "Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/white?text=Modern+AR", hero: "https://placehold.co/1200x630/7C3AED/white?text=Modern+Annual+Report", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 191, views: 165, selections: 24, previewsGenerated: 65, conversions: 10,
  },

  // ── Healthcare-specific ───────────────────────────────────────────────────────
  {
    templateCode: "HC-CP-001",
    name: "Healthcare Company Profile",
    description: "Trust-first healthcare company profile with services, team credentials, and accreditations.",
    category: "Company Profile",
    style: "Professional",
    industry: "Healthcare",
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#10B981", background: "#F0F9FF", text: "#0C4A6E" },
    typography: { heading: "Nunito Sans", body: "Open Sans", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Trustworthy", "Caring", "Professional"], voices: ["Empathetic", "Authoritative"], audiences: ["Patient", "Physician", "Insurance"], industries: ["Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/white?text=Healthcare+CP", hero: "https://placehold.co/1200x630/0891B2/white?text=Healthcare+Profile", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 5, views: 280, selections: 40, previewsGenerated: 100, conversions: 16,
  },

  // ── Logistics ─────────────────────────────────────────────────────────────────
  {
    templateCode: "LOG-CP-001",
    name: "Logistics Company Profile Bold",
    description: "Bold, map-integrated logistics company profile with route coverage, fleet specs, and SLA commitments.",
    category: "Company Profile",
    style: "Bold",
    industry: "Logistics",
    colorTheme: { primary: "#EA580C", secondary: "#C2410C", accent: "#FCD34D", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto", style: "display" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Reliable", "Efficient", "Bold"], voices: ["Direct", "Technical"], audiences: ["B2B", "Operations", "Procurement"], industries: ["Logistics", "Manufacturing", "Export"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EA580C/white?text=Logistics+CP", hero: "https://placehold.co/1200x630/EA580C/white?text=Logistics+Profile", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 6, views: 195, selections: 28, previewsGenerated: 75, conversions: 12,
  },

  // ── Construction ──────────────────────────────────────────────────────────────
  {
    templateCode: "CON-CP-001",
    name: "Construction Corporate Profile",
    description: "Heavyweight construction corporate profile with project portfolio, certifications, and capability statement.",
    category: "Corporate Profile",
    style: "Corporate",
    industry: "Construction",
    colorTheme: { primary: "#B45309", secondary: "#92400E", accent: "#FBBF24", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Montserrat Bold", body: "Roboto", style: "sans-serif" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Strong", "Reliable", "Professional"], voices: ["Confident", "Technical"], audiences: ["Developer", "Government", "Investor"], industries: ["Construction", "Property", "Manufacturing"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/white?text=Construction+CP", hero: "https://placehold.co/1200x630/B45309/white?text=Construction+Profile", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 45, views: 230, selections: 33, previewsGenerated: 85, conversions: 14,
  },

  // ── Export / Trade ────────────────────────────────────────────────────────────
  {
    templateCode: "EXP-CAT-001",
    name: "Export Product Catalog",
    description: "Bilingual export product catalog (ID/EN) with HS codes, MOQ, shipping, and certification seals.",
    category: "Product Catalog",
    style: "Professional",
    industry: "Export",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#DC2626", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "grid",
    supportedPackages: ["standard", "professional", "enterprise"],
    brandDnaTags: { personalities: ["Professional", "Global", "Trustworthy"], voices: ["Formal", "Technical"], audiences: ["International buyer", "Importer", "Distributor"], industries: ["Export", "Manufacturing", "F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/white?text=Export+Catalog", hero: "https://placehold.co/1200x630/1D4ED8/white?text=Export+Catalog", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 35, views: 260, selections: 37, previewsGenerated: 95, conversions: 15,
  },

  // ── Education ─────────────────────────────────────────────────────────────────
  {
    templateCode: "EDU-BR-001",
    name: "Education Brochure Modern",
    description: "Modern school/university brochure with programs, facilities, and student life sections.",
    category: "Brochure",
    style: "Modern",
    industry: "Education",
    colorTheme: { primary: "#2563EB", secondary: "#1D4ED8", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Open Sans", style: "sans-serif" },
    layout: "tri-fold",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Educational", "Inspiring", "Trustworthy"], voices: ["Encouraging", "Clear"], audiences: ["Student", "Parent", "Institution"], industries: ["Education"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/2563EB/white?text=Education+Brochure", hero: "https://placehold.co/1200x630/2563EB/white?text=Education+Brochure", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 55, views: 175, selections: 25, previewsGenerated: 65, conversions: 9,
  },

  // ── Property ──────────────────────────────────────────────────────────────────
  {
    templateCode: "PROP-CAT-001",
    name: "Property Catalog Luxury",
    description: "Luxury property catalog with floor plans, amenities showcase, and investment ROI section.",
    category: "Product Catalog",
    style: "Elegant",
    industry: "Property",
    colorTheme: { primary: "#1E3A5F", secondary: "#2E6DA4", accent: "#D4AF37", background: "#FAFAFA", text: "#1A1A1A" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "magazine",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Prestigious", "Luxury", "Premium"], voices: ["Refined", "Aspirational"], audiences: ["HNW", "Investor", "Property buyer"], industries: ["Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/D4AF37?text=Property+Catalog", hero: "https://placehold.co/1200x630/1E3A5F/D4AF37?text=Property+Catalog", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 38, views: 310, selections: 44, previewsGenerated: 110, conversions: 19,
  },

  // ── Finance ───────────────────────────────────────────────────────────────────
  {
    templateCode: "FIN-WP-001",
    name: "Finance Whitepaper Investment",
    description: "Investment whitepaper with market analysis, risk factors, and performance projections.",
    category: "Whitepaper",
    style: "Corporate",
    industry: "Finance",
    colorTheme: { primary: "#0F172A", secondary: "#1E293B", accent: "#2563EB", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Merriweather", body: "Source Serif Pro", style: "serif" },
    layout: "document",
    supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Conservative", "Analytical", "Trustworthy"], voices: ["Expert", "Formal"], audiences: ["Investor", "Regulator", "HNW"], industries: ["Finance", "Trading"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F172A/white?text=Finance+WP", hero: "https://placehold.co/1200x630/0F172A/white?text=Investment+Whitepaper", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: false, sortOrder: 175, views: 140, selections: 20, previewsGenerated: 55, conversions: 8,
  },

  // ── F&B Social Media ──────────────────────────────────────────────────────────
  {
    templateCode: "FNB-SM-001",
    name: "F&B Social Media Food Photography Pack",
    description: "Food photography social media kit with feed templates, story layouts, and menu card posts.",
    category: "Social Media",
    style: "Creative",
    industry: "F&B",
    colorTheme: { primary: "#B45309", secondary: "#78350F", accent: "#FCD34D", background: "#FFF7ED", text: "#1C1917" },
    typography: { heading: "Abril Fatface", body: "Nunito", style: "display" },
    layout: "social",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Artisan", "Vibrant", "Sensory"], voices: ["Warm", "Appetizing"], audiences: ["Foodie", "Consumer", "Local"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/white?text=F%26B+Social", hero: "https://placehold.co/1200x630/B45309/white?text=F%26B+Social+Media", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 85, views: 420, selections: 60, previewsGenerated: 170, conversions: 26,
  },

  // ── Retail ────────────────────────────────────────────────────────────────────
  {
    templateCode: "RET-LP-001",
    name: "Retail Landing Page Promo",
    description: "Promotional retail landing page with countdown timer, product grid, and urgency CTA.",
    category: "Landing Page",
    style: "Bold",
    industry: "Retail",
    colorTheme: { primary: "#DC2626", secondary: "#991B1B", accent: "#FCD34D", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Roboto", style: "sans-serif" },
    layout: "landing",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Promotional", "Urgency-driven", "Commercial"], voices: ["Persuasive", "Punchy"], audiences: ["Consumer", "Shopper", "Deal-seeker"], industries: ["Retail", "Trading"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/DC2626/white?text=Retail+LP", hero: "https://placehold.co/1200x630/DC2626/white?text=Retail+Landing+Page", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 145, views: 285, selections: 40, previewsGenerated: 105, conversions: 16,
  },

  // ── Pitch Deck (tambahan) ─────────────────────────────────────────────────────
  {
    templateCode: "PD-FNB-003",
    name: "Pitch Deck F&B Franchise",
    description: "Franchise pitch deck for food & beverage brand expansion — unit economics, territory map, ROI.",
    category: "Pitch Deck", style: "Bold", industry: "F&B",
    colorTheme: { primary: "#B45309", secondary: "#78350F", accent: "#FCD34D", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Poppins Bold", body: "Inter", style: "sans-serif" },
    layout: "presentation", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Entrepreneurial", "Bold", "Scalable"], voices: ["Energetic", "Confident"], audiences: ["Franchisee", "Investor", "Partner"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/FCD34D?text=F%26B+Pitch", hero: "https://placehold.co/1200x630/B45309/FCD34D?text=F%26B+Pitch+Deck", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: false, sortOrder: 12, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "PD-PROP-004",
    name: "Pitch Deck Property Investment",
    description: "Real estate investment pitch with project rendering, IRR model, absorption rate, and exit strategy.",
    category: "Pitch Deck", style: "Elegant", industry: "Property",
    colorTheme: { primary: "#1E3A5F", secondary: "#2E6DA4", accent: "#D4AF37", background: "#FAFAFA", text: "#1A1A1A" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "presentation", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Prestigious", "Analytical", "Premium"], voices: ["Refined", "Expert"], audiences: ["Investor", "HNW", "Developer"], industries: ["Property", "Finance"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/D4AF37?text=Property+Pitch", hero: "https://placehold.co/1200x630/1E3A5F/D4AF37?text=Property+Pitch+Deck", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 13, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "PD-TECH-005",
    name: "Pitch Deck SaaS Metrics",
    description: "SaaS pitch with MRR/ARR charts, churn, LTV/CAC ratio, product roadmap and team slide.",
    category: "Pitch Deck", style: "Minimalist", industry: "Technology",
    colorTheme: { primary: "#111827", secondary: "#1F2937", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Inter", body: "Inter", style: "sans-serif" },
    layout: "presentation", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Data-driven", "Innovative", "Scalable"], voices: ["Direct", "Technical"], audiences: ["VC", "Angel", "Accelerator"], industries: ["Technology", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/111827/10B981?text=SaaS+Pitch", hero: "https://placehold.co/1200x630/111827/10B981?text=SaaS+Pitch+Deck", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 14, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Proposal (tambahan) ───────────────────────────────────────────────────────
  {
    templateCode: "PROP-IT-002",
    name: "IT Project Proposal Modern",
    description: "Technical IT project proposal with scope, architecture diagram placeholder, timeline, and cost breakdown.",
    category: "Proposal", style: "Modern", industry: "Technology",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#06B6D4", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "document", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Technical", "Innovative", "Precise"], voices: ["Clear", "Expert"], audiences: ["CTO", "IT Manager", "Procurement"], industries: ["Technology"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/06B6D4?text=IT+Proposal", hero: "https://placehold.co/1200x630/1D4ED8/06B6D4?text=IT+Proposal", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 62, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "PROP-GOV-003",
    name: "Government Tender Proposal",
    description: "Formal government tender proposal with administrative requirements, capability statement, and pricing schedule.",
    category: "Proposal", style: "Corporate", industry: null,
    colorTheme: { primary: "#1E3A5F", secondary: "#374151", accent: "#C9A84C", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Arial", body: "Arial", style: "sans-serif" },
    layout: "document", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Formal", "Compliant", "Professional"], voices: ["Formal", "Authoritative"], audiences: ["Government", "Public sector", "Procurement"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/C9A84C?text=Gov+Proposal", hero: "https://placehold.co/1200x630/1E3A5F/C9A84C?text=Government+Proposal", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 63, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "PROP-MKT-004",
    name: "Marketing Agency Proposal",
    description: "Creative agency proposal with campaign concept, channel strategy, deliverables, and ROI projection.",
    category: "Proposal", style: "Creative", industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#6D28D9", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "magazine", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Creative", "Strategic", "Energetic"], voices: ["Persuasive", "Confident"], audiences: ["Brand Manager", "CEO", "Marketing Director"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/F59E0B?text=Agency+Proposal", hero: "https://placehold.co/1200x630/7C3AED/F59E0B?text=Marketing+Proposal", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 64, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Corporate Profile (tambahan) ──────────────────────────────────────────────
  {
    templateCode: "CORP-FIN-002",
    name: "Corporate Profile Finance & Banking",
    description: "Premium finance & banking corporate profile with trust indicators, AUM, products, and leadership.",
    category: "Corporate Profile", style: "Elegant", industry: "Finance",
    colorTheme: { primary: "#0F172A", secondary: "#1E293B", accent: "#C9A84C", background: "#FAFAFA", text: "#0F172A" },
    typography: { heading: "Merriweather", body: "Source Serif Pro", style: "serif" },
    layout: "magazine", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Conservative", "Prestigious", "Trustworthy"], voices: ["Formal", "Expert"], audiences: ["HNW", "Investor", "Corporate"], industries: ["Finance", "Banking"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F172A/C9A84C?text=Finance+Corp", hero: "https://placehold.co/1200x630/0F172A/C9A84C?text=Finance+Corporate", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: true, sortOrder: 46, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "CORP-LOG-003",
    name: "Corporate Profile Logistics Group",
    description: "Logistics group corporate profile with fleet overview, service coverage map, and ISO certifications.",
    category: "Corporate Profile", style: "Bold", industry: "Logistics",
    colorTheme: { primary: "#EA580C", secondary: "#C2410C", accent: "#FBBF24", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Bebas Neue", body: "Roboto", style: "display" },
    layout: "two-column", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Reliable", "Efficient", "Industrial"], voices: ["Direct", "Confident"], audiences: ["B2B", "Shipper", "Manufacturer"], industries: ["Logistics"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/EA580C/FBBF24?text=Logistics+Corp", hero: "https://placehold.co/1200x630/EA580C/FBBF24?text=Logistics+Corporate", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 47, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Brochure (tambahan) ───────────────────────────────────────────────────────
  {
    templateCode: "BRO-FNB-002",
    name: "Restaurant Menu Brochure",
    description: "Elegant restaurant menu brochure with food photography layout, pricing, and chef's special section.",
    category: "Brochure", style: "Elegant", industry: "F&B",
    colorTheme: { primary: "#1C1917", secondary: "#292524", accent: "#D4AF37", background: "#1C1917", text: "#F9FAFB" },
    typography: { heading: "Playfair Display", body: "Lato", style: "mixed" },
    layout: "bi-fold", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Warm", "Artisan", "Premium"], voices: ["Inviting", "Sensory"], audiences: ["Diner", "Local", "Tourist"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1C1917/D4AF37?text=Menu+Brochure", hero: "https://placehold.co/1200x630/1C1917/D4AF37?text=Restaurant+Menu", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 56, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "BRO-PROP-003",
    name: "Property Project Brochure",
    description: "Property project brochure with site plan, unit type breakdown, pricing, and payment scheme.",
    category: "Brochure", style: "Modern", industry: "Property",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#D4AF37", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Poppins", body: "Open Sans", style: "sans-serif" },
    layout: "tri-fold", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Aspirational", "Modern", "Trustworthy"], voices: ["Aspirational", "Clear"], audiences: ["Home buyer", "Investor", "Family"], industries: ["Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/D4AF37?text=Property+Brochure", hero: "https://placehold.co/1200x630/1D4ED8/D4AF37?text=Property+Brochure", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 57, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "BRO-CORP-004",
    name: "Corporate Services Brochure",
    description: "B2B corporate services brochure — services, team credentials, client logos, and contact CTA.",
    category: "Brochure", style: "Corporate", industry: null,
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "tri-fold", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Reliable", "Corporate"], voices: ["Formal", "Clear"], audiences: ["B2B", "Corporate", "Procurement"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/F59E0B?text=Corp+Brochure", hero: "https://placehold.co/1200x630/1E3A5F/F59E0B?text=Corporate+Brochure", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 58, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Flyer (tambahan) ──────────────────────────────────────────────────────────
  {
    templateCode: "FLY-PROMO-002",
    name: "Promo Sale Flyer",
    description: "High-impact promotional flyer for discount events, flash sales, and product launches.",
    category: "Flyer", style: "Bold", industry: "Retail",
    colorTheme: { primary: "#DC2626", secondary: "#991B1B", accent: "#FCD34D", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Roboto", style: "sans-serif" },
    layout: "flyer", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Promotional", "Urgent", "Vibrant"], voices: ["Punchy", "Energetic"], audiences: ["Consumer", "Shopper"], industries: ["Retail", "F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/DC2626/FCD34D?text=Promo+Flyer", hero: "https://placehold.co/1200x630/DC2626/FCD34D?text=Promo+Sale+Flyer", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 71, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "FLY-EVT-003",
    name: "Event Flyer Elegant",
    description: "Elegant event flyer for gala dinners, corporate events, and award nights.",
    category: "Flyer", style: "Elegant", industry: null,
    colorTheme: { primary: "#1C1917", secondary: "#292524", accent: "#D4AF37", background: "#1C1917", text: "#FFFFFF" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "flyer", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Prestigious", "Formal", "Luxury"], voices: ["Refined", "Exclusive"], audiences: ["Executive", "VIP", "Corporate"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1C1917/D4AF37?text=Event+Flyer", hero: "https://placehold.co/1200x630/1C1917/D4AF37?text=Event+Flyer", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 72, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "FLY-FNB-004",
    name: "Food & Beverage Flyer",
    description: "Mouth-watering F&B flyer with food photography focus, menu highlights, and opening promo.",
    category: "Flyer", style: "Creative", industry: "F&B",
    colorTheme: { primary: "#B45309", secondary: "#78350F", accent: "#FCD34D", background: "#FFF7ED", text: "#1C1917" },
    typography: { heading: "Abril Fatface", body: "Nunito", style: "display" },
    layout: "flyer", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Warm", "Artisan", "Vibrant"], voices: ["Appetizing", "Friendly"], audiences: ["Foodie", "Local", "Consumer"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/FCD34D?text=F%26B+Flyer", hero: "https://placehold.co/1200x630/B45309/FCD34D?text=F%26B+Flyer", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 73, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Presentation (tambahan) ───────────────────────────────────────────────────
  {
    templateCode: "PRES-TECH-002",
    name: "Tech Product Presentation",
    description: "Clean tech product presentation with feature showcase, demo flow, and competitive comparison.",
    category: "Presentation", style: "Modern", industry: "Technology",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#06B6D4", background: "#0F172A", text: "#F9FAFB" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "presentation", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Innovative", "Technical", "Clear"], voices: ["Confident", "Expert"], audiences: ["Tech Buyer", "Enterprise", "CTO"], industries: ["Technology", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/06B6D4?text=Tech+Pres", hero: "https://placehold.co/1200x630/1D4ED8/06B6D4?text=Tech+Presentation", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 77, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "PRES-SALES-003",
    name: "Sales Deck Presentation",
    description: "Persuasive sales deck with problem statement, solution pitch, social proof, and closing CTA.",
    category: "Presentation", style: "Bold", industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#6D28D9", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Inter", style: "sans-serif" },
    layout: "presentation", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Persuasive", "Confident", "Bold"], voices: ["Energetic", "Convincing"], audiences: ["Prospect", "Decision Maker", "Buyer"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/F59E0B?text=Sales+Deck", hero: "https://placehold.co/1200x630/7C3AED/F59E0B?text=Sales+Presentation", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 78, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Social Media (tambahan) ───────────────────────────────────────────────────
  {
    templateCode: "SM-PROP-003",
    name: "Property Social Media Kit",
    description: "Property listing social media kit — unit highlight, open house announcement, and testimonial post.",
    category: "Social Media", style: "Modern", industry: "Property",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#D4AF37", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "social", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Modern", "Aspirational", "Trustworthy"], voices: ["Aspirational", "Clear"], audiences: ["Home buyer", "Investor", "Renter"], industries: ["Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/D4AF37?text=Property+SM", hero: "https://placehold.co/1200x630/1D4ED8/D4AF37?text=Property+Social", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 88, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "SM-CORP-004",
    name: "Corporate Social Media Pack",
    description: "Professional corporate social media templates — thought leadership, company news, and hiring posts.",
    category: "Social Media", style: "Corporate", industry: null,
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "social", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Authoritative", "Trustworthy"], voices: ["Formal", "Informative"], audiences: ["Professional", "LinkedIn", "B2B"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/F59E0B?text=Corp+SM", hero: "https://placehold.co/1200x630/1E3A5F/F59E0B?text=Corporate+Social", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 89, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "SM-HEALTH-005",
    name: "Health & Wellness Social Kit",
    description: "Health clinic and wellness social media kit with tip posts, service highlights, and patient testimonials.",
    category: "Social Media", style: "Modern", industry: "Healthcare",
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#10B981", background: "#F0F9FF", text: "#0C4A6E" },
    typography: { heading: "Nunito Sans", body: "Open Sans", style: "sans-serif" },
    layout: "social", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Caring", "Trustworthy", "Professional"], voices: ["Empathetic", "Clear"], audiences: ["Patient", "Caregiver", "Community"], industries: ["Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/10B981?text=Health+SM", hero: "https://placehold.co/1200x630/0891B2/10B981?text=Health+Social", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 90, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Banner (tambahan) ─────────────────────────────────────────────────────────
  {
    templateCode: "BAN-SALE-002",
    name: "Sale Event Banner",
    description: "Eye-catching sale event digital banner with countdown, discount callout, and product showcase.",
    category: "Banner", style: "Bold", industry: "Retail",
    colorTheme: { primary: "#DC2626", secondary: "#991B1B", accent: "#FCD34D", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins Bold", body: "Roboto", style: "sans-serif" },
    layout: "banner", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Promotional", "Urgent", "Vibrant"], voices: ["Punchy", "Energetic"], audiences: ["Consumer", "Shopper"], industries: ["Retail", "F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/DC2626/FCD34D?text=Sale+Banner", hero: "https://placehold.co/1200x630/DC2626/FCD34D?text=Sale+Banner", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 95, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "BAN-CORP-003",
    name: "Corporate Event Banner",
    description: "Professional corporate event banner for conferences, seminars, and exhibitions.",
    category: "Banner", style: "Corporate", industry: null,
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#C9A84C", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "banner", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Professional", "Formal", "Prestigious"], voices: ["Authoritative", "Clear"], audiences: ["Corporate", "Executive", "B2B"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/C9A84C?text=Corp+Banner", hero: "https://placehold.co/1200x630/1E3A5F/C9A84C?text=Corporate+Banner", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 96, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Letterhead (tambahan) ─────────────────────────────────────────────────────
  {
    templateCode: "LH-MOD-002",
    name: "Letterhead Modern Startup",
    description: "Clean modern letterhead for startups and tech companies — minimalist with accent color bar.",
    category: "Letterhead", style: "Modern", industry: "Technology",
    colorTheme: { primary: "#7C3AED", secondary: "#6D28D9", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "letterhead", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Modern", "Innovative", "Clean"], voices: ["Direct", "Professional"], audiences: ["Client", "Partner", "Government"], industries: ["Technology", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/F59E0B?text=Modern+LH", hero: "https://placehold.co/1200x630/7C3AED/F59E0B?text=Modern+Letterhead", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 112, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "LH-FNB-003",
    name: "Letterhead F&B Brand",
    description: "Warm and inviting letterhead for restaurants, cafés, and food brands — earthy tones.",
    category: "Letterhead", style: "Elegant", industry: "F&B",
    colorTheme: { primary: "#7C2D12", secondary: "#9A3412", accent: "#D4AF37", background: "#FFFBF5", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lato", style: "mixed" },
    layout: "letterhead", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Warm", "Artisan", "Premium"], voices: ["Inviting", "Friendly"], audiences: ["Client", "Supplier", "Partner"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C2D12/D4AF37?text=F%26B+LH", hero: "https://placehold.co/1200x630/7C2D12/D4AF37?text=F%26B+Letterhead", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 113, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Email Signature (tambahan) ────────────────────────────────────────────────
  {
    templateCode: "ES-MOD-002",
    name: "Email Signature Modern Tech",
    description: "Minimal modern email signature with social links, profile photo, and CTA button.",
    category: "Email Signature", style: "Modern", industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#4F46E5", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Inter", body: "Inter", style: "sans-serif" },
    layout: "email-signature", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Modern", "Clean", "Professional"], voices: ["Direct", "Friendly"], audiences: ["Client", "Partner", "Prospect"], industries: ["Technology"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/F59E0B?text=Modern+ES", hero: "https://placehold.co/1200x630/6366F1/F59E0B?text=Modern+Email+Sig", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 125, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "ES-ELG-003",
    name: "Email Signature Executive Elegant",
    description: "Premium executive email signature with dark theme, gold accent, and company tagline.",
    category: "Email Signature", style: "Elegant", industry: null,
    colorTheme: { primary: "#1C1917", secondary: "#292524", accent: "#D4AF37", background: "#FFFFFF", text: "#1C1917" },
    typography: { heading: "Cormorant Garamond", body: "Montserrat", style: "mixed" },
    layout: "email-signature", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Prestigious", "Formal", "Executive"], voices: ["Refined", "Professional"], audiences: ["Client", "Partner", "VIP"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1C1917/D4AF37?text=Exec+ES", hero: "https://placehold.co/1200x630/1C1917/D4AF37?text=Executive+Email+Sig", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 126, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Website Hero (tambahan) ───────────────────────────────────────────────────
  {
    templateCode: "WH-FNB-002",
    name: "Website Hero F&B Restaurant",
    description: "Appetizing restaurant hero section with full-bleed food photography background and reservation CTA.",
    category: "Website Hero", style: "Creative", industry: "F&B",
    colorTheme: { primary: "#1C1917", secondary: "#292524", accent: "#D4AF37", background: "#1C1917", text: "#FFFFFF" },
    typography: { heading: "Playfair Display", body: "Lato", style: "mixed" },
    layout: "hero", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Warm", "Artisan", "Sensory"], voices: ["Inviting", "Appetizing"], audiences: ["Diner", "Foodie", "Local"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1C1917/D4AF37?text=F%26B+Hero", hero: "https://placehold.co/1200x630/1C1917/D4AF37?text=F%26B+Website+Hero", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 137, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "WH-PROP-003",
    name: "Website Hero Property",
    description: "Aspirational property website hero with project render, tagline, and find your unit CTA.",
    category: "Website Hero", style: "Modern", industry: "Property",
    colorTheme: { primary: "#1E3A5F", secondary: "#2563EB", accent: "#D4AF37", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Poppins", body: "Open Sans", style: "sans-serif" },
    layout: "hero", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Aspirational", "Modern", "Premium"], voices: ["Aspirational", "Clear"], audiences: ["Home buyer", "Investor", "Family"], industries: ["Property"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1E3A5F/D4AF37?text=Property+Hero", hero: "https://placehold.co/1200x630/1E3A5F/D4AF37?text=Property+Hero", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 138, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Landing Page (tambahan) ───────────────────────────────────────────────────
  {
    templateCode: "LP-HEALTH-002",
    name: "Healthcare Clinic Landing Page",
    description: "Healthcare clinic landing page with services, doctor profiles, booking form, and patient testimonials.",
    category: "Landing Page", style: "Modern", industry: "Healthcare",
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#10B981", background: "#F0F9FF", text: "#0C4A6E" },
    typography: { heading: "Nunito Sans", body: "Open Sans", style: "sans-serif" },
    layout: "landing", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Caring", "Trustworthy", "Clean"], voices: ["Empathetic", "Reassuring"], audiences: ["Patient", "Family", "Local"], industries: ["Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/10B981?text=Health+LP", hero: "https://placehold.co/1200x630/0891B2/10B981?text=Healthcare+Landing", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 146, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "LP-SAAS-003",
    name: "SaaS Product Landing Page",
    description: "High-converting SaaS landing page with hero, features, pricing table, FAQ, and signup CTA.",
    category: "Landing Page", style: "Modern", industry: "Technology",
    colorTheme: { primary: "#6366F1", secondary: "#4F46E5", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "landing", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Innovative", "Clear", "Scalable"], voices: ["Direct", "Confident"], audiences: ["Startup", "SME", "Enterprise"], industries: ["Technology", "SaaS"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/6366F1/F59E0B?text=SaaS+LP", hero: "https://placehold.co/1200x630/6366F1/F59E0B?text=SaaS+Landing", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: true, sortOrder: 147, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Infographic (tambahan) ────────────────────────────────────────────────────
  {
    templateCode: "INFO-FIN-002",
    name: "Finance Data Infographic",
    description: "Financial data infographic with charts, KPI highlights, and market comparison visuals.",
    category: "Infographic", style: "Corporate", industry: "Finance",
    colorTheme: { primary: "#0F172A", secondary: "#1E293B", accent: "#2563EB", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Montserrat", body: "Inter", style: "sans-serif" },
    layout: "infographic", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Analytical", "Precise", "Authoritative"], voices: ["Expert", "Formal"], audiences: ["Investor", "Analyst", "Executive"], industries: ["Finance"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F172A/2563EB?text=Finance+Info", hero: "https://placehold.co/1200x630/0F172A/2563EB?text=Finance+Infographic", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 157, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "INFO-PROC-003",
    name: "Process & Workflow Infographic",
    description: "Step-by-step process infographic for SOPs, service flows, and onboarding visuals.",
    category: "Infographic", style: "Modern", industry: null,
    colorTheme: { primary: "#7C3AED", secondary: "#6D28D9", accent: "#10B981", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Poppins", body: "Inter", style: "sans-serif" },
    layout: "infographic", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Clear", "Systematic", "Modern"], voices: ["Instructional", "Direct"], audiences: ["Internal", "Client", "Partner"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C3AED/10B981?text=Process+Info", hero: "https://placehold.co/1200x630/7C3AED/10B981?text=Process+Infographic", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 158, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Case Study (tambahan) ─────────────────────────────────────────────────────
  {
    templateCode: "CS-IT-002",
    name: "IT Implementation Case Study",
    description: "IT project case study with challenge, solution architecture, results metrics, and client quote.",
    category: "Case Study", style: "Modern", industry: "Technology",
    colorTheme: { primary: "#1D4ED8", secondary: "#1E40AF", accent: "#06B6D4", background: "#FFFFFF", text: "#0F172A" },
    typography: { heading: "Plus Jakarta Sans", body: "Inter", style: "sans-serif" },
    layout: "document", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Technical", "Results-driven", "Credible"], voices: ["Expert", "Clear"], audiences: ["CTO", "Buyer", "IT Manager"], industries: ["Technology"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/1D4ED8/06B6D4?text=IT+CS", hero: "https://placehold.co/1200x630/1D4ED8/06B6D4?text=IT+Case+Study", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 162, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "CS-FNB-003",
    name: "F&B Brand Growth Case Study",
    description: "F&B brand growth story case study — challenge, menu redesign, marketing campaign, revenue results.",
    category: "Case Study", style: "Creative", industry: "F&B",
    colorTheme: { primary: "#B45309", secondary: "#78350F", accent: "#FCD34D", background: "#FFF7ED", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lato", style: "mixed" },
    layout: "magazine", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Warm", "Results-driven", "Authentic"], voices: ["Story-driven", "Inspiring"], audiences: ["F&B owner", "Investor", "Franchisor"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/B45309/FCD34D?text=F%26B+CS", hero: "https://placehold.co/1200x630/B45309/FCD34D?text=F%26B+Case+Study", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 163, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Annual Report (tambahan) ──────────────────────────────────────────────────
  {
    templateCode: "AR-FIN-003",
    name: "Annual Report Finance & Banking",
    description: "Formal bank annual report with audited financials, board message, regulatory disclosures, and outlook.",
    category: "Annual Report", style: "Corporate", industry: "Finance",
    colorTheme: { primary: "#0F172A", secondary: "#1E293B", accent: "#C9A84C", background: "#FAFAFA", text: "#0F172A" },
    typography: { heading: "Merriweather", body: "Source Serif Pro", style: "serif" },
    layout: "magazine", supportedPackages: ["enterprise"],
    brandDnaTags: { personalities: ["Conservative", "Precise", "Authoritative"], voices: ["Formal", "Expert"], audiences: ["Shareholder", "Regulator", "Board"], industries: ["Finance", "Banking"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F172A/C9A84C?text=Finance+AR", hero: "https://placehold.co/1200x630/0F172A/C9A84C?text=Finance+Annual+Report", gallery: [] },
    editable: true, isPremium: true, version: "1.0", status: "published", featured: false, sortOrder: 192, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "AR-NGO-004",
    name: "Annual Report NGO & Foundation",
    description: "Impact-focused NGO annual report with program highlights, beneficiary stories, fund utilization, and donor thanks.",
    category: "Annual Report", style: "Modern", industry: null,
    colorTheme: { primary: "#059669", secondary: "#047857", accent: "#F59E0B", background: "#FFFFFF", text: "#111827" },
    typography: { heading: "Nunito Sans", body: "Open Sans", style: "sans-serif" },
    layout: "magazine", supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Empathetic", "Transparent", "Inspiring"], voices: ["Story-driven", "Warm"], audiences: ["Donor", "Government", "Community"], industries: [] },
    previewImages: { thumbnail: "https://placehold.co/400x300/059669/F59E0B?text=NGO+AR", hero: "https://placehold.co/1200x630/059669/F59E0B?text=NGO+Annual+Report", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 193, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Packaging (tambahan) ──────────────────────────────────────────────────────
  {
    templateCode: "PKG-FNB-003",
    name: "Packaging F&B Artisan",
    description: "Artisan food & beverage packaging design — kraft paper look, hand-lettering style, and ingredient list.",
    category: "Packaging", style: "Creative", industry: "F&B",
    colorTheme: { primary: "#7C2D12", secondary: "#9A3412", accent: "#D4AF37", background: "#FFF7ED", text: "#1C1917" },
    typography: { heading: "Playfair Display", body: "Lato", style: "mixed" },
    layout: "packaging", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Artisan", "Natural", "Authentic"], voices: ["Warm", "Story-driven"], audiences: ["Consumer", "Retailer", "Export buyer"], industries: ["F&B"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/7C2D12/D4AF37?text=F%26B+Pkg", hero: "https://placehold.co/1200x630/7C2D12/D4AF37?text=F%26B+Packaging", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 153, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },
  {
    templateCode: "PKG-HEALTH-004",
    name: "Health & Beauty Packaging",
    description: "Clean health & beauty product packaging with ingredient callout, certification badge, and usage instructions.",
    category: "Packaging", style: "Minimalist", industry: "Healthcare",
    colorTheme: { primary: "#0891B2", secondary: "#0E7490", accent: "#10B981", background: "#FFFFFF", text: "#0C4A6E" },
    typography: { heading: "Nunito Sans", body: "Open Sans", style: "sans-serif" },
    layout: "packaging", supportedPackages: ["professional", "enterprise"],
    brandDnaTags: { personalities: ["Clean", "Natural", "Trustworthy"], voices: ["Reassuring", "Clear"], audiences: ["Consumer", "Retailer", "Pharmacist"], industries: ["Healthcare"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0891B2/10B981?text=Health+Pkg", hero: "https://placehold.co/1200x630/0891B2/10B981?text=Health+Packaging", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 154, views: 0, selections: 0, previewsGenerated: 0, conversions: 0,
  },

  // ── Trading ───────────────────────────────────────────────────────────────────
  {
    templateCode: "TRD-CP-001",
    name: "Trading Company Profile Professional",
    description: "B2B trading company profile with commodity catalog, global reach map, and partner logos.",
    category: "Company Profile",
    style: "Professional",
    industry: "Trading",
    colorTheme: { primary: "#0F766E", secondary: "#134E4A", accent: "#D97706", background: "#FFFFFF", text: "#1C1917" },
    typography: { heading: "Montserrat", body: "Open Sans", style: "sans-serif" },
    layout: "two-column",
    supportedPackages: PACKAGES,
    brandDnaTags: { personalities: ["Reliable", "Global", "Professional"], voices: ["Formal", "Trustworthy"], audiences: ["B2B", "Importer", "Distributor"], industries: ["Trading", "Export", "Logistics"] },
    previewImages: { thumbnail: "https://placehold.co/400x300/0F766E/white?text=Trading+CP", hero: "https://placehold.co/1200x630/0F766E/white?text=Trading+Profile", gallery: [] },
    editable: true, isPremium: false, version: "1.0", status: "published", featured: false, sortOrder: 7, views: 210, selections: 30, previewsGenerated: 80, conversions: 12,
  },
];

async function seedTemplates() {
  console.log(`🌱 Seeding ${TEMPLATES.length} templates…`);

  for (const template of TEMPLATES) {
    await db
      .insert(aiTemplatesTable)
      .values(template)
      .onConflictDoUpdate({
        target: aiTemplatesTable.templateCode,
        set: {
          name: template.name,
          description: template.description,
          style: template.style,
          industry: template.industry ?? null,
          colorTheme: template.colorTheme ?? null,
          typography: template.typography ?? null,
          layout: template.layout ?? null,
          supportedPackages: template.supportedPackages ?? null,
          brandDnaTags: template.brandDnaTags ?? null,
          previewImages: template.previewImages ?? null,
          featured: template.featured,
          status: template.status,
          updatedAt: new Date(),
        },
      });
  }

  console.log(`✅ Seeded ${TEMPLATES.length} templates across 20 categories`);
}

seedTemplates().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
