/**
 * Team 32 — Design Rendering and Preview Adapters
 *
 * Contract types for the universal adapter layer between design artifacts
 * and the renderer/preview engines.
 *
 * Design principles:
 *  - Every render result carries an honest classification (see RenderClassification).
 *  - No renderer claims 3D capability if a 3D engine is unavailable.
 *  - Tenant isolation is a first-class invariant, not an afterthought.
 *  - Signed URLs are mandatory for any result that references object storage.
 *  - Filenames are always sanitized before reaching storage paths.
 */

import { createHmac, randomBytes } from "crypto";

// ── Formats ───────────────────────────────────────────────────────────────────

export type DesignRenderFormat =
  | "png"
  | "jpg"
  | "webp"
  | "pdf"
  | "pdf-print"
  | "svg"
  | "thumbnail"
  | "zip"
  | "composition";

export const SUPPORTED_FORMATS: ReadonlySet<DesignRenderFormat> = new Set([
  "png", "jpg", "webp", "pdf", "pdf-print", "svg", "thumbnail", "zip", "composition",
]);

// ── Render targets ────────────────────────────────────────────────────────────

/**
 * What the output will be used for.
 * This drives profile selection and honest classification.
 */
export type DesignRenderTarget =
  | "artifact_preview"     // Card / gallery preview of an artifact
  | "thumbnail"            // Small thumbnail (≤ 512 px on the long edge)
  | "workspace_image"      // Full workspace view (customer portal)
  | "review_preview"       // Review/approval lightbox
  | "document_page"        // A page from a document (PDF / DOCX)
  | "presentation_slide"   // A slide from a presentation
  | "technical_preview"    // Internal QA / admin preview
  | "mockup_preview"       // Mockup sandbox component preview
  | "3d_preview_placeholder"; // 3D artifact — no native 3D engine available

// ── Honesty classification ────────────────────────────────────────────────────

/**
 * Every render result MUST carry one of these labels.
 * Callers must expose this to users where the fidelity matters
 * (e.g. "PDF Preview" vs "Converted PDF").
 */
export type RenderClassification =
  | "native_conversion"       // Format-native output from a real converter (e.g. SVG→PDF)
  | "rasterized_preview"      // Rasterized from a vector/document source (e.g. PDF→PNG)
  | "spec_rendered"           // Built from a design spec (SVG pipeline → PNG/PDF)
  | "generated_approximation" // AI-generated visual approximation of the artifact
  | "unavailable"             // No renderer can handle this request
  | "placeholder";            // A generic placeholder image was returned

// ── Render profile ────────────────────────────────────────────────────────────

/**
 * Describes the desired output characteristics.
 * Renderers MUST NOT ignore maxFileSizeBytes, nor force high resolution
 * on every request.
 */
export interface DesignRenderProfile {
  /** Output pixel width. */
  widthPx: number;
  /** Output pixel height. */
  heightPx: number;
  /** Device pixel ratio for HiDPI outputs (default 1). */
  pixelRatio?: number;
  /** JPEG/WebP quality 0-100 (default 85 for full, 70 for preview). */
  quality?: number;
  /** CSS color string for the background, or "transparent". */
  background?: string;
  /** When true, output must support alpha transparency. */
  transparent?: boolean;
  /** Requested output format. */
  format: DesignRenderFormat;
  /** 1-based page index for multi-page documents. */
  page?: number;
  /** 1-based frame index for animated sources. */
  frame?: number;
  /** ICC color profile hint ("srgb" | "display-p3"). */
  colorProfile?: string;
  /** How the output will be used — drives renderer selection. */
  purpose: DesignRenderTarget;
  /** Hard cap on output file size. Renderer must reject if exceeded. */
  maxFileSizeBytes?: number;
  /**
   * true → lower resolution / quality is acceptable (preview).
   * false → full production quality.
   */
  previewQuality: boolean;
}

// ── Render request ────────────────────────────────────────────────────────────

export interface DesignRenderRequest {
  /** Stable unique ID for idempotency; generated by caller or registry. */
  requestId?: string;
  /** Tenant scope — MUST be validated server-side; never trust client input. */
  tenantId: string;
  /**
   * Kind of artifact being rendered.
   * Determines which adapter family is eligible.
   * Examples: "design_template", "document", "presentation", "image".
   */
  artifactKind: string;
  /** Artifact identifier (template ID, document ID, etc.). */
  artifactId: string;
  /** Desired output profile. */
  profile: DesignRenderProfile;
  /**
   * Variable data / row data for template-based renders.
   * Adapters must validate this against the artifact's schema.
   */
  sourceData?: Record<string, unknown>;
}

// ── Render job ────────────────────────────────────────────────────────────────

export type DesignRenderJobStatus =
  | "pending"
  | "processing"
  | "completed"
  | "failed"
  | "cancelled"
  | "timed_out";

export interface DesignRenderJob {
  jobId: string;
  requestId: string;
  tenantId: string;
  rendererId: string;
  profile: DesignRenderProfile;
  status: DesignRenderJobStatus;
  createdAt: string;
  startedAt?: string;
  completedAt?: string;
  errorCode?: DesignRenderErrorCode;
  errorMessage?: string;
}

// ── Render result ─────────────────────────────────────────────────────────────

export interface DesignRenderResult {
  requestId: string;
  rendererId: string;
  format: DesignRenderFormat;
  target: DesignRenderTarget;
  /**
   * Honest label for the kind of output produced.
   * NEVER label as "native_conversion" when spec_rendered.
   */
  classification: RenderClassification;
  /** Internal storage path — MUST NOT be exposed to clients. */
  storagePath?: string;
  /**
   * Short-lived signed URL for client download.
   * Must be absent if storagePath is absent.
   */
  signedUrl?: string;
  /** Long-lived public CDN URL (only if the object is public). */
  publicUrl?: string;
  fileSizeBytes?: number;
  widthPx?: number;
  heightPx?: number;
  mimeType: string;
  /** ISO-8601 expiry of the signed URL. */
  expiresAt?: string;
  durationMs: number;
  warnings: string[];
  tenantId: string;
}

// ── Preview descriptor ────────────────────────────────────────────────────────

/** Lightweight descriptor returned for quick, non-stored previews. */
export interface DesignPreviewDescriptor {
  requestId: string;
  rendererId: string;
  /** Inline data URL or public URL for the preview image. */
  previewUrl?: string;
  signedUrl?: string;
  widthPx: number;
  heightPx: number;
  format: DesignRenderFormat;
  classification: RenderClassification;
  expiresAt?: string;
  tenantId: string;
}

// ── Thumbnail descriptor ──────────────────────────────────────────────────────

export interface DesignThumbnailDescriptor {
  requestId: string;
  rendererId: string;
  thumbnailUrl?: string;
  signedUrl?: string;
  widthPx: number;
  heightPx: number;
  format: "png" | "jpg" | "webp";
  classification: RenderClassification;
  tenantId: string;
}

// ── Errors ────────────────────────────────────────────────────────────────────

export type DesignRenderErrorCode =
  | "UNSUPPORTED_FORMAT"
  | "UNSUPPORTED_ARTIFACT"
  | "RENDERER_UNAVAILABLE"
  | "RENDERER_CONFLICT"     // Duplicate renderer ID registration
  | "TENANT_MISMATCH"
  | "RESOURCE_LIMIT_EXCEEDED"
  | "FILENAME_UNSAFE"
  | "SIGNED_URL_EXPIRED"
  | "SIGNED_URL_INVALID"
  | "RENDER_TIMEOUT"
  | "RENDER_CANCELLED"
  | "RENDER_FAILED"
  | "PROFILE_INVALID"
  | "INPUT_VALIDATION_FAILED"
  | "UNKNOWN_ERROR";

export class DesignRenderError extends Error {
  readonly code: DesignRenderErrorCode;
  readonly retryable: boolean;
  readonly requestId?: string;
  readonly rendererId?: string;

  constructor(opts: {
    code: DesignRenderErrorCode;
    message: string;
    retryable?: boolean;
    requestId?: string;
    rendererId?: string;
  }) {
    super(opts.message);
    this.name = "DesignRenderError";
    this.code = opts.code;
    this.retryable = opts.retryable ?? NON_RETRYABLE_CODES.has(opts.code) === false;
    this.requestId = opts.requestId;
    this.rendererId = opts.rendererId;
  }

  toDescriptor(): {
    code: DesignRenderErrorCode;
    message: string;
    retryable: boolean;
    requestId?: string;
    rendererId?: string;
  } {
    return {
      code: this.code,
      message: this.message,
      retryable: this.retryable,
      requestId: this.requestId,
      rendererId: this.rendererId,
    };
  }
}

const NON_RETRYABLE_CODES = new Set<DesignRenderErrorCode>([
  "UNSUPPORTED_FORMAT",
  "UNSUPPORTED_ARTIFACT",
  "RENDERER_CONFLICT",
  "TENANT_MISMATCH",
  "FILENAME_UNSAFE",
  "SIGNED_URL_INVALID",
  "PROFILE_INVALID",
  "INPUT_VALIDATION_FAILED",
  "RENDER_CANCELLED",
]);

// ── Capability ────────────────────────────────────────────────────────────────

export interface DesignRenderCapability {
  /** Globally unique adapter identifier. */
  rendererId: string;
  /** Human-readable description for admin UI. */
  description: string;
  supportedFormats: DesignRenderFormat[];
  supportedTargets: DesignRenderTarget[];
  supportedArtifactKinds: string[];
  /** Maximum output width in pixels. */
  maxWidthPx: number;
  /** Maximum output height in pixels. */
  maxHeightPx: number;
  /** Maximum output file size in bytes (0 = no limit enforced by adapter). */
  maxFileSizeBytes: number;
  /** Wall-clock timeout in ms after which RENDER_TIMEOUT is raised. */
  timeoutMs: number;
  /** Whether a failed render with this adapter is worth retrying. */
  retryable: boolean;
  /**
   * Whether the adapter is currently operable.
   * A registry MUST NOT route to an unavailable adapter.
   */
  available: boolean;
  /** Required when available === false. */
  unavailableReason?: string;
  /**
   * Lower number = higher priority when multiple adapters match.
   * Deterministic: registry sorts ascending, then by rendererId for ties.
   */
  priority: number;
}

// ── Adapter interface ─────────────────────────────────────────────────────────

/**
 * All renderers implement this interface.
 *
 * Invariants:
 *  - render() must enforce tenant isolation (throw TENANT_MISMATCH if violated).
 *  - render() must sanitize output filenames.
 *  - render() must honour profile.maxFileSizeBytes.
 *  - render() must not load arbitrary modules at runtime.
 *  - canHandle() must be pure and synchronous.
 */
export interface DesignRendererAdapter {
  readonly rendererId: string;
  readonly capability: DesignRenderCapability;

  /** Synchronous eligibility check — called by registry during resolution. */
  canHandle(request: DesignRenderRequest): boolean;

  /** Execute the render. Must complete within capability.timeoutMs. */
  render(request: DesignRenderRequest): Promise<DesignRenderResult>;
}

// ── Filename safety ───────────────────────────────────────────────────────────

/**
 * Sanitize a filename component so it is safe for use in storage paths.
 * Strips path traversal, null bytes, and non-printable characters.
 * Returns a non-empty string or throws DesignRenderError(FILENAME_UNSAFE).
 */
export function sanitizeRenderFilename(raw: string): string {
  // Remove path separators, null bytes, control chars, and dangerous sequences
  const cleaned = raw
    .replace(/[/\\]/g, "_")          // No path separators
    .replace(/\.\./g, "_")           // No parent-dir traversal
    .replace(/\x00/g, "")           // No null bytes
    .replace(/[^\x20-\x7E]/g, "_")  // ASCII printable only
    .replace(/^\.+/, "_")           // No leading dots (hidden files)
    .trim()
    .slice(0, 200);                  // Reasonable length cap

  if (!cleaned || cleaned.replace(/_/g, "").length === 0) {
    throw new DesignRenderError({
      code: "FILENAME_UNSAFE",
      message: `Filename "${raw}" is not safe for storage use`,
      retryable: false,
    });
  }
  return cleaned;
}

// ── Signed URL ────────────────────────────────────────────────────────────────

const SIGNED_URL_SECRET =
  process.env["SESSION_SECRET"] ?? process.env["ADMIN_API_KEY"] ?? "dev-only-insecure-secret";

const SIGNED_URL_TTL_SECONDS = 3600; // 1 hour default

interface RenderSignedPayload {
  id: string;
  tenantId: string;
  storagePath: string;
  exp: number;
}

/**
 * Generate a short-lived, HMAC-signed URL token for a rendered output.
 * The storagePath MUST NOT be embedded verbatim in API responses —
 * only the signed token should be exposed to clients.
 */
export function generateRenderSignedToken(
  tenantId: string,
  storagePath: string,
  ttlSeconds = SIGNED_URL_TTL_SECONDS,
): { token: string; expiresAt: string } {
  const payload: RenderSignedPayload = {
    id: randomBytes(8).toString("hex"),
    tenantId,
    storagePath,
    exp: Math.floor(Date.now() / 1000) + ttlSeconds,
  };
  const encoded = Buffer.from(JSON.stringify(payload)).toString("base64url");
  const sig = createHmac("sha256", SIGNED_URL_SECRET).update(encoded).digest("base64url");
  const token = `${encoded}.${sig}`;
  const expiresAt = new Date((payload.exp) * 1000).toISOString();
  return { token, expiresAt };
}

export interface RenderSignedTokenVerifyResult {
  valid: boolean;
  tenantId?: string;
  storagePath?: string;
  reason?: string;
}

/**
 * Verify a render signed token.
 * Returns { valid: false } for malformed, tampered, or expired tokens.
 * Callers MUST check tenantId matches the requesting tenant.
 */
export function verifyRenderSignedToken(token: string): RenderSignedTokenVerifyResult {
  const parts = token.split(".");
  if (parts.length !== 2) return { valid: false, reason: "Malformed token" };

  const [encoded, sig] = parts as [string, string];
  const expectedSig = createHmac("sha256", SIGNED_URL_SECRET).update(encoded).digest("base64url");
  if (sig !== expectedSig) return { valid: false, reason: "Invalid signature" };

  let payload: RenderSignedPayload;
  try {
    payload = JSON.parse(Buffer.from(encoded, "base64url").toString("utf8")) as RenderSignedPayload;
  } catch {
    return { valid: false, reason: "Payload parse error" };
  }

  if (Math.floor(Date.now() / 1000) > payload.exp) {
    return { valid: false, reason: "Token expired" };
  }
  return { valid: true, tenantId: payload.tenantId, storagePath: payload.storagePath };
}

// ── Resource limits ───────────────────────────────────────────────────────────

export const DESIGN_RENDER_ADAPTER_LIMITS = {
  /** Maximum output pixel width accepted by any adapter. */
  MAX_OUTPUT_WIDTH_PX: 8_192,
  /** Maximum output pixel height accepted by any adapter. */
  MAX_OUTPUT_HEIGHT_PX: 8_192,
  /** Maximum output file size for raster formats (30 MB). */
  MAX_RASTER_BYTES: 30 * 1024 * 1024,
  /** Maximum output file size for PDF (50 MB). */
  MAX_PDF_BYTES: 50 * 1024 * 1024,
  /** Maximum thumbnail dimension (longer edge). */
  MAX_THUMBNAIL_PX: 512,
  /** Default thumbnail dimension. */
  DEFAULT_THUMBNAIL_PX: 256,
  /** Default wall-clock timeout for a single render (ms). */
  DEFAULT_TIMEOUT_MS: 60_000,
  /** Maximum adapters in a single registry. */
  MAX_REGISTRY_SIZE: 50,
} as const;

// ── Mime types ────────────────────────────────────────────────────────────────

export const MIME_FOR_FORMAT: Record<DesignRenderFormat, string> = {
  png:           "image/png",
  jpg:           "image/jpeg",
  webp:          "image/webp",
  pdf:           "application/pdf",
  "pdf-print":   "application/pdf",
  svg:           "image/svg+xml",
  thumbnail:     "image/png",
  zip:           "application/zip",
  composition:   "image/png",
};
