import type { Blueprint } from "../types.js";

export const fashionBlueprint: Blueprint = {
  id: "bp-fashion-v1",
  slug: "fashion-design-standard",
  schemaVersion: "1.0",
  domain: "fashion",
  name: "Fashion Design Standard",
  description: "Universal blueprint for fashion design documentation: garment tech packs, lookbooks, collection presentations, and spec sheets.",
  version: "1.0.0",
  status: "active",
  dimensions: { width: 2480, height: 3508, unit: "px", dpi: 300, aspectRatio: "A4" },
  zones: [
    { id: "z-garment-front", name: "Front View", description: "Front technical sketch of the garment", x: 0, y: 0, width: 1200, height: 2000, required: true, slotRefs: ["s-garment-sketch-front", "s-measurement-front"], zIndex: 1 },
    { id: "z-garment-back", name: "Back View", description: "Back technical sketch of the garment", x: 1280, y: 0, width: 1200, height: 2000, required: true, slotRefs: ["s-garment-sketch-back", "s-measurement-back"], zIndex: 1 },
    { id: "z-fabric-swatches", name: "Fabric & Color Swatches", description: "Fabric swatches, Pantone colors, and textures", x: 0, y: 2020, width: 1200, height: 1488, required: true, slotRefs: ["s-fabric-swatch", "s-pantone-color", "s-fabric-spec"], zIndex: 2 },
    { id: "z-construction-notes", name: "Construction Notes", description: "Seam allowances, stitch types, special instructions", x: 1280, y: 2020, width: 1200, height: 1488, required: false, slotRefs: ["s-construction-note", "s-stitch-detail"], zIndex: 2 },
  ],
  slots: [
    { id: "s-garment-sketch-front", name: "Front Sketch", type: "image", required: true, maxItems: 1, constraints: { allowedFormats: ["png", "svg", "jpg", "ai"], maxFileSizeMb: 20 } },
    { id: "s-garment-sketch-back", name: "Back Sketch", type: "image", required: true, maxItems: 1, constraints: { allowedFormats: ["png", "svg", "jpg", "ai"], maxFileSizeMb: 20 } },
    { id: "s-measurement-front", name: "Front Measurements", type: "annotation", required: false, maxItems: 20, constraints: { maxChars: 20, unit: "cm" } },
    { id: "s-measurement-back", name: "Back Measurements", type: "annotation", required: false, maxItems: 20, constraints: { maxChars: 20, unit: "cm" } },
    { id: "s-fabric-swatch", name: "Fabric Swatch", type: "image", required: true, maxItems: 6, constraints: { maxWidth: 300, maxHeight: 300, allowedFormats: ["jpg", "png", "webp"], maxFileSizeMb: 5 } },
    { id: "s-pantone-color", name: "Pantone Color", type: "color_swatch", required: false, maxItems: 8, constraints: { maxWidth: 120, maxHeight: 120 } },
    { id: "s-fabric-spec", name: "Fabric Specification", type: "text", required: true, maxItems: 6, constraints: { maxChars: 300, minFontSize: 8, maxFontSize: 12 } },
    { id: "s-construction-note", name: "Construction Note", type: "text", required: false, maxItems: 10, constraints: { maxChars: 400, minFontSize: 8, maxFontSize: 12 } },
    { id: "s-stitch-detail", name: "Stitch Detail Image", type: "image", required: false, maxItems: 4, constraints: { allowedFormats: ["png", "jpg", "svg"], maxFileSizeMb: 5 } },
  ],
  constraints: {
    maxZones: 8,
    maxSlots: 20,
    allowZoneOverlap: false,
    requiredZoneIds: ["z-garment-front", "z-garment-back", "z-fabric-swatches"],
    domainSpecific: { requiresPantoneColors: false, requiresSizeChart: false, defaultUnit: "cm" },
  },
  supportedComponents: [
    { type: "image-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["image"] },
    { type: "color-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["color_swatch"] },
    { type: "annotation-tool", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["annotation", "measurement"] },
    { type: "rich-text-editor", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["text"] },
  ],
  requiredData: [
    { key: "garmentName", label: "Garment Name", type: "string", required: true, maxLength: 100 },
    { key: "season", label: "Season / Collection", type: "string", required: true, maxLength: 60 },
    { key: "category", label: "Garment Category", type: "enum", required: true, allowedValues: ["tops", "bottoms", "outerwear", "dresses", "activewear", "accessories", "footwear", "lingerie"] },
    { key: "sizes", label: "Available Sizes", type: "string_array", required: true, description: "e.g. XS,S,M,L,XL" },
    { key: "fabricComposition", label: "Fabric Composition", type: "string", required: true, maxLength: 200 },
    { key: "careInstructions", label: "Care Instructions", type: "string", required: false, maxLength: 300 },
    { key: "designerName", label: "Designer", type: "string", required: false, maxLength: 100 },
    { key: "colorways", label: "Number of Colorways", type: "number", required: false, min: 1, max: 20, defaultValue: 1 },
  ],
  outputCapabilities: [
    { format: "pdf", maxDpi: 300, multiPage: false, colorSpace: "cmyk", bleedMm: 3 },
    { format: "png", maxDpi: 300, colorSpace: "rgb" },
    { format: "ai", colorSpace: "cmyk" },
  ],
  industryTags: ["fashion", "apparel", "luxury", "sportswear", "streetwear", "haute-couture"],
  styleTags: ["technical", "minimalist", "avant-garde", "classic", "streetwear", "sustainable"],
  createdAt: "2026-07-16T00:00:00.000Z",
  updatedAt: "2026-07-16T00:00:00.000Z",
};
