import type { Blueprint } from "../types.js";

export const interiorBlueprint: Blueprint = {
  id: "bp-interior-v1",
  slug: "interior-design-standard",
  schemaVersion: "1.0",
  domain: "interior",
  name: "Interior Design Standard",
  description: "Universal blueprint for interior design documentation: floor plans, mood boards, material specs, and room layout presentations.",
  version: "1.0.0",
  status: "active",
  dimensions: { width: 3508, height: 2480, unit: "px", dpi: 150, aspectRatio: "A3-landscape" },
  zones: [
    { id: "z-floor-plan", name: "Floor Plan", description: "Technical floor plan or spatial layout", x: 0, y: 0, width: 1800, height: 1800, required: true, slotRefs: ["s-floor-plan-image", "s-room-label", "s-dimension-annotation"], zIndex: 1 },
    { id: "z-material-palette", name: "Material Palette", description: "Material swatches, finishes, and textures", x: 1820, y: 0, width: 1688, height: 900, required: true, slotRefs: ["s-material-swatch", "s-material-spec"], zIndex: 2 },
    { id: "z-mood-board", name: "Mood Board", description: "Inspirational imagery and references", x: 1820, y: 920, width: 1688, height: 880, required: false, slotRefs: ["s-reference-image", "s-style-note"], zIndex: 2 },
    { id: "z-spec-table", name: "Specifications", description: "Material quantities, codes, and supplier info", x: 0, y: 1820, width: 3508, height: 660, required: false, slotRefs: ["s-spec-table", "s-project-info"], zIndex: 2 },
  ],
  slots: [
    { id: "s-floor-plan-image", name: "Floor Plan Image", type: "image", required: true, maxItems: 1, constraints: { allowedFormats: ["png", "svg", "jpg", "dxf"], maxFileSizeMb: 30 } },
    { id: "s-room-label", name: "Room Label", type: "annotation", required: false, maxItems: 20, constraints: { maxChars: 50, unit: "m²" } },
    { id: "s-dimension-annotation", name: "Dimension Annotation", type: "measurement", required: false, maxItems: 30, constraints: { unit: "m" } },
    { id: "s-material-swatch", name: "Material Swatch", type: "color_swatch", required: true, maxItems: 12, constraints: { maxWidth: 200, maxHeight: 200 } },
    { id: "s-material-spec", name: "Material Specification", type: "text", required: true, maxItems: 12, constraints: { maxChars: 200, minFontSize: 8, maxFontSize: 14 } },
    { id: "s-reference-image", name: "Reference / Inspiration Image", type: "image", required: false, maxItems: 6, constraints: { allowedFormats: ["jpg", "png", "webp"], maxFileSizeMb: 10 } },
    { id: "s-style-note", name: "Style Note", type: "text", required: false, maxItems: 3, constraints: { maxChars: 300 } },
    { id: "s-spec-table", name: "Specification Table", type: "data_table", required: false, maxItems: 1, constraints: { maxRows: 50, maxColumns: 8 } },
    { id: "s-project-info", name: "Project Information", type: "text", required: false, maxItems: 1, constraints: { maxChars: 300 } },
  ],
  constraints: {
    maxZones: 8,
    maxSlots: 24,
    allowZoneOverlap: false,
    requiredZoneIds: ["z-floor-plan", "z-material-palette"],
    domainSpecific: { requiresScaleBar: true, defaultScale: "1:50" },
  },
  supportedComponents: [
    { type: "image-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["image"] },
    { type: "color-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["color_swatch"] },
    { type: "annotation-tool", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["annotation", "measurement"] },
    { type: "data-table-editor", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["data_table"] },
    { type: "rich-text-editor", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["text"] },
  ],
  requiredData: [
    { key: "projectName", label: "Project Name", type: "string", required: true, maxLength: 150 },
    { key: "clientName", label: "Client Name", type: "string", required: true, maxLength: 100 },
    { key: "roomType", label: "Room Type", type: "enum", required: true, allowedValues: ["living_room", "bedroom", "kitchen", "bathroom", "office", "commercial", "full_floor"] },
    { key: "totalAreaM2", label: "Total Area (m²)", type: "number", required: true, min: 1, max: 100000 },
    { key: "style", label: "Design Style", type: "enum", required: true, allowedValues: ["modern", "minimalist", "scandinavian", "industrial", "traditional", "japandi", "maximalist"] },
    { key: "budget", label: "Budget Range", type: "enum", required: false, allowedValues: ["economy", "mid-range", "premium", "luxury"] },
    { key: "scale", label: "Drawing Scale", type: "string", required: false, defaultValue: "1:50" },
  ],
  outputCapabilities: [
    { format: "pdf", maxDpi: 300, multiPage: true, colorSpace: "rgb", bleedMm: 5 },
    { format: "png", maxDpi: 150, colorSpace: "rgb" },
    { format: "svg", colorSpace: "rgb" },
    { format: "dxf", colorSpace: "rgb" },
  ],
  industryTags: ["architecture", "real-estate", "hospitality", "residential", "commercial"],
  styleTags: ["modern", "minimalist", "scandinavian", "industrial", "traditional", "japandi"],
  createdAt: "2026-07-16T00:00:00.000Z",
  updatedAt: "2026-07-16T00:00:00.000Z",
};
