import type { Blueprint } from "../types.js";

export const packagingBlueprint: Blueprint = {
  id: "bp-packaging-v1",
  slug: "packaging-design-standard",
  schemaVersion: "1.0",
  domain: "packaging",
  name: "Packaging Design Standard",
  description: "Universal blueprint for packaging design: dieline layouts, product packaging, labels, and structural packaging documentation.",
  version: "1.0.0",
  status: "active",
  dimensions: { width: 3508, height: 2480, unit: "mm", dpi: 300, aspectRatio: "A3-landscape" },
  zones: [
    { id: "z-front-panel", name: "Front Panel", description: "Primary consumer-facing panel", x: 0, y: 0, width: 100, height: 150, required: true, slotRefs: ["s-product-name", "s-brand-logo", "s-front-visual", "s-tagline"], zIndex: 2 },
    { id: "z-back-panel", name: "Back Panel", description: "Ingredients, barcode, legal info", x: 110, y: 0, width: 100, height: 150, required: true, slotRefs: ["s-ingredients", "s-barcode", "s-legal-back", "s-nutritional-info"], zIndex: 2 },
    { id: "z-side-panel-left", name: "Left Side Panel", description: "Left lateral panel content", x: 220, y: 0, width: 40, height: 150, required: false, slotRefs: ["s-side-text", "s-side-image"], zIndex: 1 },
    { id: "z-side-panel-right", name: "Right Side Panel", description: "Right lateral panel content", x: 270, y: 0, width: 40, height: 150, required: false, slotRefs: ["s-side-text", "s-side-image"], zIndex: 1 },
    { id: "z-top-bottom-panels", name: "Top / Bottom Panels", description: "Closure, handle, or top-of-pack content", x: 320, y: 0, width: 60, height: 150, required: false, slotRefs: ["s-closure-note", "s-batch-code"], zIndex: 1 },
    { id: "z-dieline", name: "Dieline Overlay", description: "Structural cut and fold lines", x: 0, y: 0, width: 3508, height: 2480, required: true, slotRefs: ["s-dieline-image"], zIndex: 0 },
  ],
  slots: [
    { id: "s-product-name", name: "Product Name", type: "text", required: true, maxItems: 1, constraints: { maxChars: 80, minFontSize: 18, maxFontSize: 144 } },
    { id: "s-brand-logo", name: "Brand Logo", type: "image", required: true, maxItems: 1, constraints: { allowedFormats: ["png", "svg", "ai"], maxFileSizeMb: 10 } },
    { id: "s-front-visual", name: "Front Visual / Product Shot", type: "image", required: false, maxItems: 1, constraints: { allowedFormats: ["png", "jpg", "webp"], maxFileSizeMb: 20 } },
    { id: "s-tagline", name: "Tagline / Descriptor", type: "text", required: false, maxItems: 1, constraints: { maxChars: 100, minFontSize: 10, maxFontSize: 36 } },
    { id: "s-ingredients", name: "Ingredients / Contents", type: "text", required: false, maxItems: 1, constraints: { maxChars: 2000, minFontSize: 6, maxFontSize: 10 } },
    { id: "s-barcode", name: "Barcode / QR Code", type: "image", required: false, maxItems: 2, constraints: { maxWidth: 80, maxHeight: 60, allowedFormats: ["png", "svg"], maxFileSizeMb: 1 } },
    { id: "s-legal-back", name: "Legal / Compliance Text", type: "text", required: false, maxItems: 1, constraints: { maxChars: 1000, minFontSize: 5, maxFontSize: 8 } },
    { id: "s-nutritional-info", name: "Nutritional Information", type: "data_table", required: false, maxItems: 1, constraints: { maxRows: 20, maxColumns: 3 } },
    { id: "s-side-text", name: "Side Panel Text", type: "text", required: false, maxItems: 2, constraints: { maxChars: 300, minFontSize: 6, maxFontSize: 14 } },
    { id: "s-side-image", name: "Side Panel Image", type: "image", required: false, maxItems: 2, constraints: { allowedFormats: ["png", "jpg", "svg"], maxFileSizeMb: 5 } },
    { id: "s-closure-note", name: "Closure / Handle Note", type: "text", required: false, maxItems: 1, constraints: { maxChars: 100 } },
    { id: "s-batch-code", name: "Batch / Lot Code", type: "text", required: false, maxItems: 1, constraints: { maxChars: 30 } },
    { id: "s-dieline-image", name: "Dieline File", type: "image", required: true, maxItems: 1, constraints: { allowedFormats: ["svg", "pdf", "ai"], maxFileSizeMb: 50 } },
  ],
  constraints: {
    maxZones: 10,
    maxSlots: 24,
    allowZoneOverlap: true,
    requiredZoneIds: ["z-front-panel", "z-back-panel", "z-dieline"],
    domainSpecific: { requiresDieline: true, bleedRequired: true, defaultBleedMm: 3, safeZoneMm: 5 },
  },
  supportedComponents: [
    { type: "rich-text-editor", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["text"] },
    { type: "image-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["image"] },
    { type: "color-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["color_swatch"] },
    { type: "data-table-editor", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["data_table"] },
    { type: "dieline-editor", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["image", "shape"] },
  ],
  requiredData: [
    { key: "productName", label: "Product Name", type: "string", required: true, maxLength: 100 },
    { key: "brandName", label: "Brand Name", type: "string", required: true, maxLength: 100 },
    { key: "packagingType", label: "Packaging Type", type: "enum", required: true, allowedValues: ["box", "bag", "bottle", "can", "pouch", "tube", "label", "sleeve", "blister", "clamshell"] },
    { key: "primaryColor", label: "Primary Color", type: "color", required: true },
    { key: "dimensions", label: "Package Dimensions (LxWxH mm)", type: "string", required: true, description: "e.g. 120x80x40" },
    { key: "netWeight", label: "Net Weight / Volume", type: "string", required: false, maxLength: 30 },
    { key: "countryOfOrigin", label: "Country of Origin", type: "string", required: false, maxLength: 50 },
    { key: "certifications", label: "Certifications / Symbols", type: "string_array", required: false, description: "e.g. CE, FDA, Halal, Organic" },
  ],
  outputCapabilities: [
    { format: "pdf", maxDpi: 300, multiPage: false, colorSpace: "cmyk", bleedMm: 3, iccProfile: "ISOcoated_v2_eci" },
    { format: "ai", colorSpace: "cmyk" },
    { format: "svg", colorSpace: "rgb" },
    { format: "png", maxDpi: 300, colorSpace: "rgb" },
  ],
  industryTags: ["fmcg", "food-beverage", "cosmetics", "pharma", "retail", "e-commerce"],
  styleTags: ["clean", "premium", "bold", "eco-friendly", "playful", "luxury"],
  createdAt: "2026-07-16T00:00:00.000Z",
  updatedAt: "2026-07-16T00:00:00.000Z",
};
