import type { Blueprint } from "../types.js";

export const presentationBlueprint: Blueprint = {
  id: "bp-presentation-v1",
  slug: "presentation-standard",
  schemaVersion: "1.0",
  domain: "presentation",
  name: "Presentation Standard",
  description: "Universal blueprint for slide deck presentations: pitch decks, corporate, educational, and data-heavy decks.",
  version: "1.0.0",
  status: "active",
  dimensions: { width: 1920, height: 1080, unit: "px", dpi: 96, aspectRatio: "16:9" },
  zones: [
    { id: "z-slide-header", name: "Slide Header", description: "Slide title and section label", x: 0, y: 0, width: 1920, height: 180, required: true, slotRefs: ["s-slide-title", "s-slide-subtitle", "s-section-label"], zIndex: 2 },
    { id: "z-main-content", name: "Main Content", description: "Primary slide content area", x: 60, y: 200, width: 1800, height: 700, required: true, slotRefs: ["s-body-text", "s-data-table", "s-chart-image", "s-bullet-list"], zIndex: 1 },
    { id: "z-speaker-notes", name: "Speaker Notes Area", description: "Companion notes zone (not rendered on slide)", x: 0, y: 920, width: 1920, height: 160, required: false, slotRefs: ["s-speaker-note"], zIndex: 0 },
    { id: "z-slide-footer", name: "Slide Footer", description: "Slide number, logo, confidentiality label", x: 0, y: 1000, width: 1920, height: 80, required: true, slotRefs: ["s-slide-number", "s-footer-logo", "s-confidentiality"], zIndex: 2 },
  ],
  slots: [
    { id: "s-slide-title", name: "Slide Title", type: "text", required: true, maxItems: 1, constraints: { maxChars: 100, minFontSize: 28, maxFontSize: 80 } },
    { id: "s-slide-subtitle", name: "Slide Subtitle", type: "text", required: false, maxItems: 1, constraints: { maxChars: 160, minFontSize: 16, maxFontSize: 36 } },
    { id: "s-section-label", name: "Section Label", type: "text", required: false, maxItems: 1, constraints: { maxChars: 40, minFontSize: 12, maxFontSize: 20 } },
    { id: "s-body-text", name: "Body Text", type: "text", required: false, maxItems: 1, constraints: { maxChars: 600, minFontSize: 14, maxFontSize: 24 } },
    { id: "s-bullet-list", name: "Bullet List", type: "text", required: false, maxItems: 1, constraints: { maxChars: 800, minFontSize: 14, maxFontSize: 22 } },
    { id: "s-data-table", name: "Data Table", type: "data_table", required: false, maxItems: 1, constraints: { maxRows: 20, maxColumns: 8 } },
    { id: "s-chart-image", name: "Chart / Graph", type: "image", required: false, maxItems: 2, constraints: { allowedFormats: ["png", "svg", "webp"], maxFileSizeMb: 10 } },
    { id: "s-speaker-note", name: "Speaker Note", type: "text", required: false, maxItems: 1, constraints: { maxChars: 1000 } },
    { id: "s-slide-number", name: "Slide Number", type: "text", required: false, maxItems: 1, constraints: { maxChars: 10 } },
    { id: "s-footer-logo", name: "Footer Logo", type: "image", required: false, maxItems: 1, constraints: { maxWidth: 200, maxHeight: 60, allowedFormats: ["png", "svg"], maxFileSizeMb: 2 } },
    { id: "s-confidentiality", name: "Confidentiality Label", type: "text", required: false, maxItems: 1, constraints: { maxChars: 40 } },
  ],
  constraints: { maxZones: 6, maxSlots: 16, allowZoneOverlap: false, requiredZoneIds: ["z-slide-header", "z-main-content", "z-slide-footer"] },
  supportedComponents: [
    { type: "rich-text-editor", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["text"] },
    { type: "data-table-editor", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["data_table"] },
    { type: "image-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["image"] },
    { type: "chart-builder", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["data_table", "image"] },
  ],
  requiredData: [
    { key: "deckTitle", label: "Deck Title", type: "string", required: true, maxLength: 150 },
    { key: "presenter", label: "Presenter Name", type: "string", required: false, maxLength: 100 },
    { key: "totalSlides", label: "Total Slides", type: "number", required: false, min: 1, max: 500 },
    { key: "theme", label: "Deck Theme", type: "enum", required: true, allowedValues: ["corporate", "creative", "minimal", "data-heavy", "educational"] },
    { key: "logoUrl", label: "Logo URL", type: "image_url", required: false },
  ],
  outputCapabilities: [
    { format: "pptx", multiPage: true, colorSpace: "rgb" },
    { format: "pdf", maxDpi: 150, multiPage: true, colorSpace: "rgb" },
    { format: "png", maxDpi: 150, multiPage: false, colorSpace: "rgb" },
  ],
  industryTags: ["corporate", "startup", "education", "consulting", "finance"],
  styleTags: ["minimal", "data-driven", "bold", "academic", "investor-ready"],
  createdAt: "2026-07-16T00:00:00.000Z",
  updatedAt: "2026-07-16T00:00:00.000Z",
};
