import type { Blueprint } from "../types.js";

export const productDesignBlueprint: Blueprint = {
  id: "bp-product-design-v1",
  slug: "product-design-standard",
  schemaVersion: "1.0",
  domain: "product_design",
  name: "Product Design Standard",
  description: "Universal blueprint for industrial and consumer product design: concept sheets, engineering specs, CMF (color-material-finish) boards, and 3D render presentations.",
  version: "1.0.0",
  status: "active",
  dimensions: { width: 3508, height: 2480, unit: "px", dpi: 150, aspectRatio: "A3-landscape" },
  zones: [
    { id: "z-concept-render", name: "Concept Renders", description: "Primary 3D renders or sketches of the product", x: 0, y: 0, width: 2000, height: 1600, required: true, slotRefs: ["s-render-primary", "s-render-alternate", "s-sketch"], zIndex: 1 },
    { id: "z-cmf-board", name: "CMF Board", description: "Color, material, and finish specifications", x: 2020, y: 0, width: 1488, height: 1200, required: true, slotRefs: ["s-color-swatch", "s-material-sample", "s-finish-spec"], zIndex: 2 },
    { id: "z-dimensions-view", name: "Dimension Views", description: "Orthographic views with dimensions", x: 0, y: 1620, width: 2000, height: 860, required: true, slotRefs: ["s-ortho-view", "s-dimension-note"], zIndex: 2 },
    { id: "z-engineering-spec", name: "Engineering Specs", description: "Technical specifications, tolerances, BOM", x: 2020, y: 1220, width: 1488, height: 1260, required: false, slotRefs: ["s-spec-table", "s-tolerance-note", "s-bom-table"], zIndex: 2 },
  ],
  slots: [
    { id: "s-render-primary", name: "Primary 3D Render", type: "image", required: true, maxItems: 1, constraints: { allowedFormats: ["png", "jpg", "webp"], maxFileSizeMb: 30 } },
    { id: "s-render-alternate", name: "Alternate Angle Renders", type: "image", required: false, maxItems: 4, constraints: { allowedFormats: ["png", "jpg", "webp"], maxFileSizeMb: 20 } },
    { id: "s-sketch", name: "Concept Sketch", type: "image", required: false, maxItems: 2, constraints: { allowedFormats: ["png", "jpg", "svg"], maxFileSizeMb: 15 } },
    { id: "s-color-swatch", name: "Color Option", type: "color_swatch", required: true, maxItems: 8, constraints: { maxWidth: 150, maxHeight: 150 } },
    { id: "s-material-sample", name: "Material Sample", type: "image", required: true, maxItems: 6, constraints: { maxWidth: 200, maxHeight: 200, allowedFormats: ["jpg", "png"], maxFileSizeMb: 5 } },
    { id: "s-finish-spec", name: "Finish Specification", type: "text", required: false, maxItems: 6, constraints: { maxChars: 200 } },
    { id: "s-ortho-view", name: "Orthographic View", type: "image", required: true, maxItems: 3, constraints: { allowedFormats: ["png", "svg"], maxFileSizeMb: 20 } },
    { id: "s-dimension-note", name: "Dimension Annotation", type: "measurement", required: false, maxItems: 30, constraints: { unit: "mm" } },
    { id: "s-spec-table", name: "Specification Table", type: "data_table", required: false, maxItems: 1, constraints: { maxRows: 40, maxColumns: 6 } },
    { id: "s-tolerance-note", name: "Tolerance Notes", type: "text", required: false, maxItems: 5, constraints: { maxChars: 300 } },
    { id: "s-bom-table", name: "Bill of Materials", type: "data_table", required: false, maxItems: 1, constraints: { maxRows: 100, maxColumns: 8 } },
  ],
  constraints: {
    maxZones: 8,
    maxSlots: 24,
    allowZoneOverlap: false,
    requiredZoneIds: ["z-concept-render", "z-cmf-board", "z-dimensions-view"],
    domainSpecific: { requiresOrthographicViews: true, defaultUnit: "mm", ipProtectionNotice: true },
  },
  supportedComponents: [
    { type: "image-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["image"] },
    { type: "color-picker", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["color_swatch"] },
    { type: "annotation-tool", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["annotation", "measurement"] },
    { type: "data-table-editor", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["data_table"] },
    { type: "rich-text-editor", versionRange: ">=1.0.0", required: true, fillsSlotTypes: ["text"] },
    { type: "3d-viewer", versionRange: ">=1.0.0", required: false, fillsSlotTypes: ["image", "component"], config: { supportedFormats: ["obj", "glb", "stl"] } },
  ],
  requiredData: [
    { key: "productName", label: "Product Name", type: "string", required: true, maxLength: 100 },
    { key: "productCategory", label: "Category", type: "enum", required: true, allowedValues: ["consumer-electronics", "furniture", "appliance", "tool", "wearable", "toy", "sporting-goods", "medical-device", "automotive", "other"] },
    { key: "targetMarket", label: "Target Market", type: "string", required: false, maxLength: 100 },
    { key: "estimatedWeight", label: "Estimated Weight (g)", type: "number", required: false, min: 0.1, max: 500000 },
    { key: "keyMaterials", label: "Key Materials", type: "string_array", required: true },
    { key: "manufacturingProcess", label: "Manufacturing Process", type: "enum", required: false, allowedValues: ["injection-molding", "cnc-machining", "3d-printing", "die-casting", "stamping", "extrusion", "assembly", "other"] },
    { key: "sustainabilityGoals", label: "Sustainability Goals", type: "string", required: false, maxLength: 300 },
  ],
  outputCapabilities: [
    { format: "pdf", maxDpi: 300, multiPage: true, colorSpace: "rgb" },
    { format: "png", maxDpi: 150, colorSpace: "rgb" },
    { format: "svg", colorSpace: "rgb" },
    { format: "obj", colorSpace: "rgb" },
  ],
  industryTags: ["industrial-design", "consumer-electronics", "furniture", "automotive", "medical", "toy"],
  styleTags: ["technical", "futuristic", "ergonomic", "sustainable", "minimalist", "biomimicry"],
  createdAt: "2026-07-16T00:00:00.000Z",
  updatedAt: "2026-07-16T00:00:00.000Z",
};
